/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewAnimationDialog.java
 *
 * Created on 2011-3-30, 8:45:20
 */
package com.soyostar.pluginimpl.sprite.dialog;

import com.soyostar.pluginimpl.sprite.data.Proxy;
import com.soyostar.pluginimpl.sprite.model.Animation;
import com.soyostar.pluginimpl.sprite.model.Frame;
import com.soyostar.pluginimpl.sprite.model.Layer;
import com.soyostar.pluginimpl.sprite.model.ModuleLayer;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class NewAnimationDialog extends javax.swing.JDialog {

    /** Creates new form NewAnimationDialog */
    public NewAnimationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initialize();

    }

    private void initialize() {
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathFileChooser = new javax.swing.JFileChooser();
        aniNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pathTextField = new javax.swing.JTextField();
        pathButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cutComboBox = new javax.swing.JComboBox();

        pathFileChooser.setName("pathFileChooser"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(NewAnimationDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N

        aniNameTextField.setName("aniNameTextField"); // NOI18N

        jLabel1.setText("动画名称");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("存储路径");
        jLabel2.setName("jLabel2"); // NOI18N

        pathTextField.setName("pathTextField"); // NOI18N

        pathButton.setText("...");
        pathButton.setName("pathButton"); // NOI18N
        pathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathButtonActionPerformed(evt);
            }
        });

        cancleButton.setText("取消");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("切图模式");
        jLabel3.setName("jLabel3"); // NOI18N

        cutComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "手动切图", "自动切图" }));
        cutComboBox.setName("cutComboBox"); // NOI18N
        cutComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cutComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pathButton))
                            .addComponent(aniNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cutComboBox, 0, 226, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(cancleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(aniNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathButton)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancleButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathButtonActionPerformed
        // TODO add your handling code here:
        pathFileChooser.setCurrentDirectory(new java.io.File("."));// 设置当前目录
        pathFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);// 设置只能选择文件夹
        pathFileChooser.showOpenDialog(this);// 显示“打开”文件对话框
        java.io.File file = pathFileChooser.getSelectedFile();
        if (file != null) {
            pathTextField.setText(file.getPath());
        }
}//GEN-LAST:event_pathButtonActionPerformed

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_cancleButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        Animation ani = Animation.getInstance();

        if (!pathTextField.getText().equals("")) {
            ani.setPath(pathTextField.getText());
        } else {
            JOptionPane.showMessageDialog(this, "保存路径不能为空！", "警告",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!aniNameTextField.getText().equals("")) {
            ani.setName(aniNameTextField.getText());
        } else {
            ani.setName("未命名动画");
        }
        switch (cutComboBox.getSelectedIndex()) {
            case Animation.AUTOMATIC:
                ani.setType(Animation.AUTOMATIC);
//                ani.setFrameWidth(Integer.valueOf(frameWidthTextField.getText()));
//                ani.setFrameHeight(Integer.valueOf(frameHeightTextField.getText()));
                break;
            default:
                ani.setType(Animation.MANUAL);
                break;
        }
        ani.addAnimationChangeListener(Proxy.getInstance().getMainDialog());
//        Frame frame = new Frame();
//        frame.addFrameChangeListener(Proxy.getInstance().getMainDialog());
//        frame.setName("新建帧");
//        Layer layer = new ModuleLayer();
//        layer.addLayerChangeListener(Proxy.getInstance().getMainDialog());
//        layer.setName("新建层");
//        frame.addLayer(layer);
//        ani.addFrame(frame);
//        Proxy.getInstance().getMainDialog().addFrame();
        dispose();
}//GEN-LAST:event_okButtonActionPerformed

    private void cutComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cutComboBoxItemStateChanged
        // TODO add your handling code here:
//        System.out.println(cutComboBox.getSelectedItem());
        switch (cutComboBox.getSelectedIndex()) {
            case Animation.AUTOMATIC:
//                frameWidthTextField.setEditable(true);
//                frameHeightTextField.setEditable(true);
                break;
            case Animation.MANUAL:
//                frameWidthTextField.setEditable(false);
//                frameHeightTextField.setEditable(false);
                break;
        }

    }//GEN-LAST:event_cutComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NewAnimationDialog dialog = new NewAnimationDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aniNameTextField;
    private javax.swing.JButton cancleButton;
    private javax.swing.JComboBox cutComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton okButton;
    private javax.swing.JButton pathButton;
    private javax.swing.JFileChooser pathFileChooser;
    private javax.swing.JTextField pathTextField;
    // End of variables declaration//GEN-END:variables
}
