/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EnemyBattlerDialog.java
 *
 * Created on 2011-5-8, 22:27:01
 */
package com.soyomaker.data.ui;

import com.soyomaker.AppData;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import org.apache.log4j.Logger;

/**
 *
 * @author Administrator
 */
public class ChooseImageDialog extends javax.swing.JDialog {

    /** Creates new form EnemyBattlerDialog
     * @param parent 
     * @param modal
     * @param path
     */
    public ChooseImageDialog(JDialog parent, boolean modal, String path) {
        super(parent, modal);
        init(path);
        initComponents();
        initialize();
    }
    private DefaultListModel listModel;
    private ArrayList<Image> images = new ArrayList<Image>();

    private void init(String path) {
        File file = new File(AppData.getInstance().getCurProject().getPath() + File.separatorChar + path);
        listModel = new DefaultListModel();
        if (file != null) {
            File[] files = file.listFiles();
            try {
                for (int i = 0, n = files.length; i < n; i++) {
                    if (files[i].getName().toLowerCase().endsWith(".png")) {
                        listModel.addElement(files[i].getName());
                        images.add(ImageIO.read(new File(files[i].getPath())));
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(this.getClass().getName()).error("battler img load error！ ", ex);
//                Log.getLogger(ChooseImageDialog.class).error("battler img load error", ex);
            }
        }
    }

    private void initialize() {
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        imgPane = new javax.swing.JPanel(){
            public void paint(Graphics g){
                g.clearRect(0, 0, getWidth(),getHeight());
                if(imgList.getSelectedIndex()!=-1){

                    g.drawImage(images.get(imgList.getSelectedIndex()), 0, 0, null);
                }
            }
            public Dimension getPreferredSize(){
                if(imgList.getSelectedIndex()!=-1){
                    return new Dimension(images.get(imgList.getSelectedIndex()).getWidth(null),images.get(imgList.getSelectedIndex()).getHeight(null));
                }
                return new Dimension(0,0);
            }
        }
        ;
        jScrollPane1 = new javax.swing.JScrollPane();
        imgList = new javax.swing.JList();
        okButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSplitPane1.setName("jSplitPane1"); // NOI18N
        jSplitPane1.setOneTouchExpandable(true);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        imgPane.setName("imgPane"); // NOI18N

        javax.swing.GroupLayout imgPaneLayout = new javax.swing.GroupLayout(imgPane);
        imgPane.setLayout(imgPaneLayout);
        imgPaneLayout.setHorizontalGroup(
            imgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );
        imgPaneLayout.setVerticalGroup(
            imgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(imgPane);

        jSplitPane1.setRightComponent(jScrollPane2);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        imgList.setModel(listModel);
        imgList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        imgList.setName("imgList"); // NOI18N
        imgList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                imgListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(imgList);

        jSplitPane1.setLeftComponent(jScrollPane1);

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancleButton.setText("取消");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancleButton)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_imgListValueChanged
        // TODO add your handling code here:
        imgPane.updateUI();
}//GEN-LAST:event_imgListValueChanged
    /**
     *
     * @return
     */
    public String getSelectedImage() {
        if (!isOkButton) {//按下关闭按钮时，返回空字符串
            return "";
        }
        if (imgList.getSelectedIndex() != -1) {
//            System.out.println(imgList.getSelectedValue().toString());
            return imgList.getSelectedValue().toString();
        }
        return "";
    }
    private boolean isOkButton = false;
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
//        if (imgList.getSelectedIndex() != -1) {
//            System.out.println(imgList.getSelectedValue().toString());
//            enemy.battleImg = imgList.getSelectedValue().toString();
//            ded.enemyBattleImgPanel.updateUI();
//        }
        isOkButton = true;
        this.setVisible(false);
}//GEN-LAST:event_okButtonActionPerformed

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        isOkButton = false;
        this.setVisible(false);
}//GEN-LAST:event_cancleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ChooseImageDialog dialog = new ChooseImageDialog(null, true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancleButton;
    private javax.swing.JList imgList;
    private javax.swing.JPanel imgPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
