/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditSkillDialog.java
 *
 * Created on 2011-9-17, 8:57:59
 */
package com.soyomaker.data.ui;

import com.soyomaker.AppData;
import com.soyomaker.data.DataManager;
import com.soyomaker.data.model.ModelEffectTableModel;
import com.soyomaker.data.model.ModelStatusTableModel;
import com.soyomaker.data.model.Skill;
import com.soyomaker.data.model.Skill.BuffInfo;
import com.soyomaker.model.animation.Animation;
import javax.swing.ImageIcon;

/**
 *
 * @author Administrator
 */
public class EditSkillDialog extends javax.swing.JDialog {

    /** Creates new form EditSkillDialog
     * @param parent
     * @param modal
     * @param skill
     */
    public EditSkillDialog(SkillPanel parent, boolean modal, Skill skill) {
        //super(parent, modal);
        setModal(modal);
        ietm = new ModelEffectTableModel(skill.effects);
        mstm = new ModelStatusTableModel(skill.status);
        initComponents();
        setLocationRelativeTo(null);
        skillIcons = DataManager.listSkillIconName();
        skillIconComboBox.addItem("");
        for (int i = 0; i < skillIcons.length; i++) {
            skillIconComboBox.addItem(skillIcons[i]);
        }
//        skillSounds = DataManager.listSoundName();
//        skillAttributeComboBox.addItem("");
//        for (int i = 0; i < skillSounds.length; i++) {
//            skillAttributeComboBox.addItem(skillSounds[i]);
//        }
        skillUserAniComboBox.addItem("");
        java.util.Iterator it = AppData.getInstance().getCurProject().getAnimations().entrySet().iterator();
        while (it.hasNext()) {
            java.util.Map.Entry entry = (java.util.Map.Entry) it.next();
            skillUserAniComboBox.addItem(((Animation) entry.getValue()));
        }
        java.util.Iterator it1 = AppData.getInstance().getCurProject().getAnimations().entrySet().iterator();
        skillTargetAniComboBox.addItem("");
        while (it1.hasNext()) {
            java.util.Map.Entry entry = (java.util.Map.Entry) it1.next();
            skillTargetAniComboBox.addItem(((Animation) entry.getValue()));
        }
        setSkill(skill);
    }
    private ImageIcon[] skillIcons;
//    private String[] skillSounds;
    private Skill skill;
    private ModelEffectTableModel ietm;
    private ModelStatusTableModel mstm;

    private void setSkill(Skill skill) {
        this.skill = skill;
        skillNameTextField.setText(skill.name);
        skillIntroTextArea.setText(skill.intro);
        for (int i = 0; i < skillIcons.length; i++) {
            if (skill.icon.equals(skillIcons[i].getDescription())) {
                skillIconComboBox.setSelectedItem(skillIcons[i]);
                break;
            }
        }
        skillLevTextField.setText(skill.lev + "");
        skillTargetComboBox.setSelectedIndex(skill.target);
        skillTypeComboBox.setSelectedIndex(skill.type);
        skillUserAniComboBox.setSelectedItem((Animation) AppData.getInstance().getCurProject().getAnimation(skill.userAniIndex));
        skillTargetAniComboBox.setSelectedItem((Animation) AppData.getInstance().getCurProject().getAnimation(skill.targetAniIndex));
        skillEventComboBox.setSelectedIndex(skill.eventIndex);
        skillAttributeComboBox.setSelectedItem(skill.attributeId);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        skillNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        skillIconComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        skillLevTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        skillTargetComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        skillUserAniComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        skillTypeComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        skillTargetAniComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        skillAttributeComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        skillEventComboBox = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        statusTable = new javax.swing.JTable();
        jToolBar5 = new javax.swing.JToolBar();
        addStatusButton = new javax.swing.JButton();
        removeStatusButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        skillIntroTextArea = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        effectTable = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        addEffectButton = new javax.swing.JButton();
        removeEffectButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setName("jTable2"); // NOI18N
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("编辑技能");
        setResizable(false);

        jLabel1.setText("名称");
        jLabel1.setName("jLabel1"); // NOI18N

        skillNameTextField.setName("skillNameTextField"); // NOI18N

        jLabel2.setText("图标");
        jLabel2.setName("jLabel2"); // NOI18N

        skillIconComboBox.setName("skillIconComboBox"); // NOI18N

        jLabel3.setText("说明");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("限制等级");
        jLabel4.setName("jLabel4"); // NOI18N

        skillLevTextField.setName("skillLevTextField"); // NOI18N

        jLabel5.setText("使用目标");
        jLabel5.setName("jLabel5"); // NOI18N

        skillTargetComboBox.setModel(new javax.swing.DefaultComboBoxModel(Skill.targets));
        skillTargetComboBox.setName("skillTargetComboBox"); // NOI18N

        jLabel6.setText("目标动画");
        jLabel6.setName("jLabel6"); // NOI18N

        skillUserAniComboBox.setName("skillUserAniComboBox"); // NOI18N

        jLabel7.setText("使用动画");
        jLabel7.setName("jLabel7"); // NOI18N

        skillTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(Skill.types));
        skillTypeComboBox.setName("skillTypeComboBox"); // NOI18N

        jLabel8.setText("类型");
        jLabel8.setName("jLabel8"); // NOI18N

        skillTargetAniComboBox.setName("skillTargetAniComboBox"); // NOI18N

        jLabel9.setText("属性");
        jLabel9.setName("jLabel9"); // NOI18N

        skillAttributeComboBox.setName("skillAttributeComboBox"); // NOI18N

        jLabel10.setText("公共事件编号");
        jLabel10.setName("jLabel10"); // NOI18N

        skillEventComboBox.setName("skillEventComboBox"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buff列表"));
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        statusTable.setModel(mstm);
        statusTable.setName("statusTable"); // NOI18N
        statusTable.setRowHeight(20);
        jScrollPane3.setViewportView(statusTable);

        jToolBar5.setFloatable(false);
        jToolBar5.setRollover(true);
        jToolBar5.setName("jToolBar5"); // NOI18N

        addStatusButton.setText("添加状态");
        addStatusButton.setFocusable(false);
        addStatusButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addStatusButton.setName("addStatusButton"); // NOI18N
        addStatusButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStatusButtonActionPerformed(evt);
            }
        });
        jToolBar5.add(addStatusButton);

        removeStatusButton.setText("删除状态");
        removeStatusButton.setFocusable(false);
        removeStatusButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeStatusButton.setName("removeStatusButton"); // NOI18N
        removeStatusButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStatusButtonActionPerformed(evt);
            }
        });
        jToolBar5.add(removeStatusButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );

        jScrollPane7.setName("jScrollPane7"); // NOI18N

        skillIntroTextArea.setColumns(20);
        skillIntroTextArea.setLineWrap(true);
        skillIntroTextArea.setRows(5);
        skillIntroTextArea.setName("skillIntroTextArea"); // NOI18N
        jScrollPane7.setViewportView(skillIntroTextArea);

        closeButton.setText("关闭");
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("数据列表"));
        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        effectTable.setModel(ietm);
        effectTable.setName("effectTable"); // NOI18N
        effectTable.setRowHeight(20);
        jScrollPane6.setViewportView(effectTable);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        addEffectButton.setText("添加效果");
        addEffectButton.setFocusable(false);
        addEffectButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addEffectButton.setName("addEffectButton"); // NOI18N
        addEffectButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addEffectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEffectButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(addEffectButton);

        removeEffectButton.setText("删除效果");
        removeEffectButton.setFocusable(false);
        removeEffectButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeEffectButton.setName("removeEffectButton"); // NOI18N
        removeEffectButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeEffectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEffectButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(removeEffectButton);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );

        jLabel11.setText("攻击距离");
        jLabel11.setName("jLabel11"); // NOI18N

        jTextField1.setName("jTextField1"); // NOI18N

        jLabel12.setText("消耗Sp");
        jLabel12.setName("jLabel12"); // NOI18N

        jTextField2.setName("jTextField2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(skillNameTextField)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(skillEventComboBox, 0, 151, Short.MAX_VALUE)
                            .addComponent(skillTargetComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(skillIconComboBox, 0, 140, Short.MAX_VALUE)
                            .addComponent(skillUserAniComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(skillAttributeComboBox, 0, 166, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(skillTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(skillTargetAniComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(skillLevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {skillAttributeComboBox, skillEventComboBox, skillIconComboBox, skillLevTextField, skillTargetAniComboBox, skillTargetComboBox, skillTypeComboBox, skillUserAniComboBox});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {closeButton, okButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(skillNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, 0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(skillIconComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(skillTargetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(skillUserAniComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(skillLevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(skillTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(skillTargetAniComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(skillEventComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(skillAttributeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(okButton)
                        .addComponent(closeButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {skillAttributeComboBox, skillEventComboBox, skillIconComboBox, skillLevTextField, skillTargetAniComboBox, skillTargetComboBox, skillTypeComboBox, skillUserAniComboBox});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        skill.name = skillNameTextField.getText();
        skill.intro = skillIntroTextArea.getText();
        skill.icon = skillIconComboBox.getSelectedItem().toString();
        skill.lev = Integer.parseInt(skillLevTextField.getText());
        skill.target = skillTargetComboBox.getSelectedIndex();
        skill.type = skillTypeComboBox.getSelectedIndex();
        if (skillUserAniComboBox.getSelectedItem() == null || skillUserAniComboBox.getSelectedItem().toString().equals("")) {
            skill.userAniIndex = -1;
        } else {
            skill.userAniIndex = ((Animation) skillUserAniComboBox.getSelectedItem()).getIndex();
        }
        if (skillTargetAniComboBox.getSelectedItem() == null || skillTargetAniComboBox.getSelectedItem().toString().equals("")) {
            skill.targetAniIndex = -1;
        } else {
            skill.targetAniIndex = ((Animation) skillTargetAniComboBox.getSelectedItem()).getIndex();
        }
        skill.eventIndex = skillEventComboBox.getSelectedIndex();
        skill.attributeId = Integer.parseInt(skillAttributeComboBox.getSelectedItem().toString());
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void addEffectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEffectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEffectButtonActionPerformed

    private void removeEffectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEffectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeEffectButtonActionPerformed

    private void addStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStatusButtonActionPerformed
        // TODO add your handling code here:
        AddModelBuffDialog etd = new AddModelBuffDialog(this, true);
        etd.setVisible(true);
        if (etd.getBuff() != null) {
            BuffInfo buffInfo = new BuffInfo();
            buffInfo.buff = etd.getBuff();
            buffInfo.rate = etd.getRate();
            skill.status.add(buffInfo);
            statusTable.updateUI();
        }
    }//GEN-LAST:event_addStatusButtonActionPerformed

    private void removeStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStatusButtonActionPerformed
        // TODO add your handling code here:
        if (statusTable.getSelectedRow() >= 0 && statusTable.getSelectedRow() < skill.status.size()) {
            skill.status.remove(statusTable.getSelectedRow());
            statusTable.updateUI();
        }
    }//GEN-LAST:event_removeStatusButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEffectButton;
    private javax.swing.JButton addStatusButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTable effectTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JButton okButton;
    private javax.swing.JButton removeEffectButton;
    private javax.swing.JButton removeStatusButton;
    private javax.swing.JComboBox skillAttributeComboBox;
    private javax.swing.JComboBox skillEventComboBox;
    private javax.swing.JComboBox skillIconComboBox;
    private javax.swing.JTextArea skillIntroTextArea;
    private javax.swing.JTextField skillLevTextField;
    private javax.swing.JTextField skillNameTextField;
    private javax.swing.JComboBox skillTargetAniComboBox;
    private javax.swing.JComboBox skillTargetComboBox;
    private javax.swing.JComboBox skillTypeComboBox;
    private javax.swing.JComboBox skillUserAniComboBox;
    private javax.swing.JTable statusTable;
    // End of variables declaration//GEN-END:variables
}
