/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditItemDialog.java
 *
 * Created on 2011-9-18, 23:55:21
 */
package com.soyomaker.data.ui;

import com.soyomaker.AppData;
import com.soyomaker.data.DataManager;
import com.soyomaker.data.model.Cost;
import com.soyomaker.data.model.Effect;
import com.soyomaker.data.model.Factor;
import com.soyomaker.data.model.Item;
import com.soyomaker.data.model.ModelCostTableModel;
import com.soyomaker.data.model.ModelEffectTableModel;
import com.soyomaker.data.model.ModelFactorTableModel;
import com.soyomaker.data.model.ModelAttributeTableModel;
import com.soyomaker.data.model.ModelStatusTableModel;
import com.soyomaker.model.animation.Animation;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class EditItemDialog extends javax.swing.JDialog {

    /** Creates new form EditItemDialog
     * @param parent
     * @param modal
     * @param item
     */
    public EditItemDialog(ItemPanel parent, boolean modal, Item item) {
        setModal(modal);
//        ictm = new ModelCostTableModel(item.costs);
//        ietm = new ModelEffectTableModel(item.effects);
//        iftm = new ModelFactorTableModel(item.factors);
//        matm = new ModelAttributeTableModel(item.attributes);
//        mstm = new ModelStatusTableModel(item.status);
        initComponents();
        setLocationRelativeTo(null);
        itemIcons = DataManager.listItemIconName();
        itemIconComboBox.addItem("");
        for (int i = 0; i < itemIcons.length; i++) {
            itemIconComboBox.addItem(itemIcons[i]);
        }
//        itemSounds = DataManager.listSoundName();
//        itemMenuSoundComboBox.addItem("");
//        for (int i = 0; i < itemSounds.length; i++) {
//            itemMenuSoundComboBox.addItem(itemSounds[i]);
//        }
//        itemUserAniComboBox.addItem("");
//        java.util.Iterator it = AppData.getInstance().getCurProject().getAnimations().entrySet().iterator();
//        while (it.hasNext()) {
//            java.util.Map.Entry entry = (java.util.Map.Entry) it.next();
//            itemUserAniComboBox.addItem(((Animation) entry.getValue()));
//        }
//        java.util.Iterator it1 = AppData.getInstance().getCurProject().getAnimations().entrySet().iterator();
//        itemTargetAniComboBox.addItem("");
//        while (it1.hasNext()) {
//            java.util.Map.Entry entry = (java.util.Map.Entry) it1.next();
//            itemTargetAniComboBox.addItem(((Animation) entry.getValue()));
//        }
        setItem(item);
    }
    private ImageIcon[] itemIcons;
//    private String[] itemSounds;
    private Item item;
//    private ModelCostTableModel ictm;
//    private ModelEffectTableModel ietm;
//    private ModelFactorTableModel iftm;
//    private ModelAttributeTableModel matm;
//    private ModelStatusTableModel mstm;

    private void setItem(Item item) {
        this.item = item;
        itemNameTextField.setText(item.name);
        itemIntroTextArea.setText(item.intro);
        for (int i = 0; i < itemIcons.length; i++) {
            if (item.icon.equals(itemIcons[i].getDescription())) {
                itemIconComboBox.setSelectedItem(itemIcons[i]);
                break;
            }
        }
        itemLevTextField.setText(item.lev + "");
        itemTypeComboBox.setSelectedIndex(item.type);
//        itemLimitComboBox.setSelectedIndex(item.limit);
//        itemUserAniComboBox.setSelectedItem((Animation) AppData.getInstance().getCurProject().getAnimation(item.userAniIndex));
//        itemTargetAniComboBox.setSelectedItem((Animation) AppData.getInstance().getCurProject().getAnimation(item.targetAniIndex));
//        itemEventComboBox.setSelectedIndex(item.eventIndex);
//        itemMenuSoundComboBox.setSelectedItem(item.menuUseSound);
        itemPriceTextField.setText(item.price + "");
//        itemUseableCheckBox.setSelected(item.consumable);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        itemNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemIntroTextArea = new javax.swing.JTextArea();
        okButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        itemIconComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        itemLevTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        itemTypeComboBox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        itemPriceTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        addSkillButton = new javax.swing.JButton();
        removeSkillButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        skillTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("编辑物品"); // NOI18N
        setResizable(false);

        jLabel1.setText("名称");
        jLabel1.setName("jLabel1"); // NOI18N

        itemNameTextField.setName("itemNameTextField"); // NOI18N

        jLabel2.setText("说明");
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        itemIntroTextArea.setColumns(20);
        itemIntroTextArea.setLineWrap(true);
        itemIntroTextArea.setRows(5);
        itemIntroTextArea.setName("itemIntroTextArea"); // NOI18N
        jScrollPane2.setViewportView(itemIntroTextArea);

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        closeButton.setText("关闭");
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        itemIconComboBox.setName("itemIconComboBox"); // NOI18N

        jLabel3.setText("图标");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("限制等级");
        jLabel4.setName("jLabel4"); // NOI18N

        itemLevTextField.setText("0");
        itemLevTextField.setName("itemLevTextField"); // NOI18N

        jLabel5.setText("类型");
        jLabel5.setName("jLabel5"); // NOI18N

        itemTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(Item.types));
        itemTypeComboBox.setName("itemTypeComboBox"); // NOI18N

        jLabel11.setText("价格");
        jLabel11.setName("jLabel11"); // NOI18N

        itemPriceTextField.setText("0");
        itemPriceTextField.setName("itemPriceTextField"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("技能列表"));
        jPanel1.setName("jPanel1"); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        addSkillButton.setText("添加技能");
        addSkillButton.setFocusable(false);
        addSkillButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addSkillButton.setName("addSkillButton"); // NOI18N
        addSkillButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(addSkillButton);

        removeSkillButton.setText("删除技能");
        removeSkillButton.setFocusable(false);
        removeSkillButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeSkillButton.setName("removeSkillButton"); // NOI18N
        removeSkillButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(removeSkillButton);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        skillTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        skillTable.setName("skillTable"); // NOI18N
        jScrollPane1.setViewportView(skillTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(itemNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemPriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(itemLevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemIconComboBox, 0, 177, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {itemIconComboBox, itemLevTextField, itemPriceTextField, itemTypeComboBox});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(itemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(itemIconComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(itemTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(itemLevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(itemPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(closeButton)
                        .addComponent(okButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {itemIconComboBox, itemLevTextField, itemPriceTextField, itemTypeComboBox});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        item.name = itemNameTextField.getText();
        item.intro = itemIntroTextArea.getText();
        item.icon = itemIconComboBox.getSelectedItem().toString();
        item.lev = Integer.parseInt(itemLevTextField.getText());
        item.type = itemTypeComboBox.getSelectedIndex();
//        item.limit = itemLimitComboBox.getSelectedIndex();
//        if (itemUserAniComboBox.getSelectedItem() == null || itemUserAniComboBox.getSelectedItem().toString().equals("")) {
//            item.userAniIndex = -1;
//        } else {
//            item.userAniIndex = ((Animation) itemUserAniComboBox.getSelectedItem()).getIndex();
//        }
//        if (itemTargetAniComboBox.getSelectedItem() == null || itemTargetAniComboBox.getSelectedItem().toString().equals("")) {
//            item.targetAniIndex = -1;
//        } else {
//            item.targetAniIndex = ((Animation) itemTargetAniComboBox.getSelectedItem()).getIndex();
//        }
//        item.eventIndex = itemEventComboBox.getSelectedIndex();
//        item.menuUseSound = itemMenuSoundComboBox.getSelectedItem().toString();
        item.price = Integer.parseInt(itemPriceTextField.getText());
//        item.consumable = itemUseableCheckBox.isSelected();
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSkillButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox itemIconComboBox;
    private javax.swing.JTextArea itemIntroTextArea;
    private javax.swing.JTextField itemLevTextField;
    private javax.swing.JTextField itemNameTextField;
    private javax.swing.JTextField itemPriceTextField;
    private javax.swing.JComboBox itemTypeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton okButton;
    private javax.swing.JButton removeSkillButton;
    private javax.swing.JTable skillTable;
    // End of variables declaration//GEN-END:variables
}
