/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditBuffDialog.java
 *
 * Created on 2011-9-23, 23:15:16
 */
package com.soyomaker.data.ui;

import com.soyomaker.AppData;
import com.soyomaker.data.DataManager;
import com.soyomaker.data.model.Condition;
import com.soyomaker.data.model.ModelAttributeTableModel;
import com.soyomaker.data.model.ModelConditionTableModel;
import com.soyomaker.data.model.ModelParameterTableModel;
import com.soyomaker.data.model.ModelStatusTableModel;
import com.soyomaker.data.model.Parameter;
import com.soyomaker.data.model.Buff;
import com.soyomaker.model.animation.Animation;
import javax.swing.ImageIcon;

/**
 *
 * @author Administrator
 */
public class EditBuffDialog extends javax.swing.JDialog {

    /** Creates new form EditBuffDialog
     * @param parent
     * @param modal
     * @param status
     */
    public EditBuffDialog(StatusPanel parent, boolean modal, Buff status) {
        setModal(modal);
        mctm = new ModelConditionTableModel(status.conds);
        mptm = new ModelParameterTableModel(status.paras);
        initComponents();
        setLocationRelativeTo(null);
        statusIcons = DataManager.listStatusIconName();
        statusIconComboBox.addItem("");
        for (int i = 0; i < statusIcons.length; i++) {
            statusIconComboBox.addItem(statusIcons[i]);
        }
        statusAniComboBox.addItem("");
        java.util.Iterator it = AppData.getInstance().getCurProject().getAnimations().entrySet().iterator();
        while (it.hasNext()) {
            java.util.Map.Entry entry = (java.util.Map.Entry) it.next();
            statusAniComboBox.addItem(((Animation) entry.getValue()));
        }
        setStatus(status);
    }
    private Buff status;
    private ImageIcon[] statusIcons;
    private ModelAttributeTableModel matm;
    private ModelStatusTableModel mstm;
    private ModelConditionTableModel mctm;
    private ModelParameterTableModel mptm;

    private void setStatus(Buff status) {
        this.status = status;
        statusNameTextField.setText(status.name);
        statusIntroTextArea.setText(status.description);
        for (int i = 0; i < statusIcons.length; i++) {
            if (status.icon.equals(statusIcons[i].getDescription())) {
                statusIconComboBox.setSelectedItem(statusIcons[i]);
                break;
            }
        }
        statusLevTextField.setText(status.lev + "");
        statusAniComboBox.setSelectedItem((Animation) AppData.getInstance().getCurProject().getAnimation(status.aniIndex));
        statusKindComboBox.setSelectedIndex(status.limitType);
        statusLastTypeComboBox.setSelectedIndex(status.type);
        statusLastValueTextField.setText(status.typeParam + "");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        statusNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusIntroTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        statusIconComboBox = new javax.swing.JComboBox();
        statusKindComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        statusLevTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        statusAniComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        statusLastTypeComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        statusLastValueTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        addParameterButton = new javax.swing.JButton();
        removeParameterButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        parameterTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        conditionTable = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        addConditionButton = new javax.swing.JButton();
        removeConditionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(EditBuffDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setResizable(false);

        jLabel1.setText("名称");
        jLabel1.setName("jLabel1"); // NOI18N

        statusNameTextField.setName("statusNameTextField"); // NOI18N

        jLabel2.setText("说明");
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        statusIntroTextArea.setColumns(20);
        statusIntroTextArea.setLineWrap(true);
        statusIntroTextArea.setRows(5);
        statusIntroTextArea.setName("statusIntroTextArea"); // NOI18N
        jScrollPane1.setViewportView(statusIntroTextArea);

        jLabel3.setText("图标");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("限制类型");
        jLabel4.setName("jLabel4"); // NOI18N

        statusIconComboBox.setName("statusIconComboBox"); // NOI18N

        statusKindComboBox.setModel(new javax.swing.DefaultComboBoxModel(com.soyomaker.data.model.Buff.limitKinds));
        statusKindComboBox.setName("statusKindComboBox"); // NOI18N

        jLabel5.setText("等级");
        jLabel5.setName("jLabel5"); // NOI18N

        statusLevTextField.setText("0");
        statusLevTextField.setName("statusLevTextField"); // NOI18N

        jLabel6.setText("动画");
        jLabel6.setName("jLabel6"); // NOI18N

        statusAniComboBox.setName("statusAniComboBox"); // NOI18N

        jLabel7.setText("类型");
        jLabel7.setName("jLabel7"); // NOI18N

        statusLastTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(com.soyomaker.data.model.Buff.lastKinds));
        statusLastTypeComboBox.setName("statusLastTypeComboBox"); // NOI18N
        statusLastTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                statusLastTypeComboBoxItemStateChanged(evt);
            }
        });

        jLabel8.setText("类型参数");
        jLabel8.setName("jLabel8"); // NOI18N

        statusLastValueTextField.setText("0");
        statusLastValueTextField.setName("statusLastValueTextField"); // NOI18N

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        closeButton.setText("关闭");
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("数据列表"));
        jPanel2.setName("jPanel2"); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        addParameterButton.setText("添加参数");
        addParameterButton.setFocusable(false);
        addParameterButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addParameterButton.setName("addParameterButton"); // NOI18N
        addParameterButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addParameterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addParameterButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(addParameterButton);

        removeParameterButton.setText("删除参数");
        removeParameterButton.setFocusable(false);
        removeParameterButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeParameterButton.setName("removeParameterButton"); // NOI18N
        removeParameterButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeParameterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeParameterButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(removeParameterButton);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        parameterTable.setModel(mptm);
        parameterTable.setRowHeight(20);
        jScrollPane2.setViewportView(parameterTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("解除条件列表"));
        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        conditionTable.setModel(mctm);
        conditionTable.setName("conditionTable"); // NOI18N
        conditionTable.setRowHeight(20);
        jScrollPane3.setViewportView(conditionTable);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setName("jToolBar2"); // NOI18N

        addConditionButton.setText("添加条件");
        addConditionButton.setFocusable(false);
        addConditionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addConditionButton.setName("addConditionButton"); // NOI18N
        addConditionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addConditionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConditionButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(addConditionButton);

        removeConditionButton.setText("删除条件");
        removeConditionButton.setFocusable(false);
        removeConditionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeConditionButton.setName("removeConditionButton"); // NOI18N
        removeConditionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeConditionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeConditionButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(removeConditionButton);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(statusNameTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statusLastTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusIconComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusKindComboBox, 0, 197, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusLastValueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(statusAniComboBox, 0, 172, Short.MAX_VALUE)
                            .addComponent(statusLevTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel2, jPanel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(statusNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(statusIconComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(statusLevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(statusKindComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(statusAniComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusLastTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(statusLastValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(closeButton)
                        .addComponent(okButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel2, jPanel3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        status.name = statusNameTextField.getText();
        status.description = statusIntroTextArea.getText();
        status.icon = statusIconComboBox.getSelectedItem().toString();
        status.lev = Integer.parseInt(statusLevTextField.getText());
        if (statusAniComboBox.getSelectedItem() == null || statusAniComboBox.getSelectedItem().toString().equals("")) {
            status.aniIndex = -1;
        } else {
            status.aniIndex = ((Animation) statusAniComboBox.getSelectedItem()).getIndex();
        }
        status.type = statusKindComboBox.getSelectedIndex();
        status.type = statusLastTypeComboBox.getSelectedIndex();
        status.typeParam = Integer.parseInt(statusLastValueTextField.getText());
        dispose();
}//GEN-LAST:event_okButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_closeButtonActionPerformed

    private void addParameterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addParameterButtonActionPerformed
        // TODO add your handling code here:
        Parameter para = new Parameter();
        para.type = status.paras.size();
        status.paras.add(para);
        parameterTable.updateUI();
    }//GEN-LAST:event_addParameterButtonActionPerformed

    private void removeParameterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeParameterButtonActionPerformed
        // TODO add your handling code here:
        if (parameterTable.getSelectedRow() >= 0 && parameterTable.getSelectedRow() < status.paras.size()) {
            status.paras.remove(parameterTable.getSelectedRow());
        }
        parameterTable.updateUI();
    }//GEN-LAST:event_removeParameterButtonActionPerformed

    private void addConditionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConditionButtonActionPerformed
        // TODO add your handling code here:
        Condition cond = new Condition();
        cond.conditionType = status.conds.size();
        status.conds.add(cond);
        conditionTable.updateUI();
    }//GEN-LAST:event_addConditionButtonActionPerformed

    private void removeConditionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeConditionButtonActionPerformed
        // TODO add your handling code here:
        if (conditionTable.getSelectedRow() >= 0 && conditionTable.getSelectedRow() < status.conds.size()) {
            status.conds.remove(conditionTable.getSelectedRow());
        }
        conditionTable.updateUI();
    }//GEN-LAST:event_removeConditionButtonActionPerformed

    private void statusLastTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_statusLastTypeComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_statusLastTypeComboBoxItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addConditionButton;
    private javax.swing.JButton addParameterButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTable conditionTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton okButton;
    private javax.swing.JTable parameterTable;
    private javax.swing.JButton removeConditionButton;
    private javax.swing.JButton removeParameterButton;
    private javax.swing.JComboBox statusAniComboBox;
    private javax.swing.JComboBox statusIconComboBox;
    private javax.swing.JTextArea statusIntroTextArea;
    private javax.swing.JComboBox statusKindComboBox;
    private javax.swing.JComboBox statusLastTypeComboBox;
    private javax.swing.JTextField statusLastValueTextField;
    private javax.swing.JTextField statusLevTextField;
    private javax.swing.JTextField statusNameTextField;
    // End of variables declaration//GEN-END:variables
}
