/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditEnemyDialog.java
 *
 * Created on 2011-9-30, 22:15:26
 */
package com.soyomaker.data.ui;

import com.soyomaker.data.model.Enemy;
import com.soyomaker.data.model.Enemy.ItemInfo;
import com.soyomaker.data.model.ModelActionTableModel;
import com.soyomaker.data.model.ModelItemTableModel;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author Administrator
 */
public class EditEnemyDialog extends javax.swing.JDialog {

    /** Creates new form EditEnemyDialog
     * @param parent
     * @param enemy
     * @param modal
     */
    public EditEnemyDialog(EnemyPanel parent, boolean modal, Enemy enemy) {
        setModal(modal);
        mttm = new ModelItemTableModel(enemy.treasures);
        mactm = new ModelActionTableModel(enemy.actions);
        initComponents();
        setLocationRelativeTo(null);
        setEnemy(enemy);
    }
    private Enemy enemy;
    private ModelItemTableModel mttm;
    private ModelActionTableModel mactm;

    private void setEnemy(Enemy enemy) {
        this.enemy = enemy;
        enemyNameTextField.setText(enemy.name);
        enemyIntroTextArea.setText(enemy.intro);
        enemyLevTextField.setText("" + enemy.lev);
        enemyBodyTextField.setText("" + enemy.body);
        enemyStreTextField.setText("" + enemy.stre);
        enemyInteTextField.setText("" + enemy.inte);
        enemyAgilTextField.setText("" + enemy.agil);
        enemyDexTextField.setText("" + enemy.dex);
        enemyLuckTextField.setText("" + enemy.luck);
        enemyExpTextField.setText("" + enemy.exp);
        enemyMoneyTextField.setText("" + enemy.money);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enemyNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enemyIntroTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        enemyLevTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        enemyStreTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        enemyInteTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        enemyAgilTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        enemyDexTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        enemyLuckTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        enemyExpTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        enemyMoneyTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        enemyBodyTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        addTreasureButton = new javax.swing.JButton();
        removeTreasureButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        treasureTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        actionTable = new javax.swing.JTable();
        jToolBar4 = new javax.swing.JToolBar();
        addActionButton = new javax.swing.JButton();
        removeActionButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        enemyCharImgPanel = new javax.swing.JPanel(){
            public void paint(Graphics g){
                g.setColor(new Color(255,153,153));
                g.fillRect(0, 0, this.getWidth(), this.getHeight());
                Image img;
                if(enemy.charImg.equals("")){
                    return;
                }
                try{
                    img = ImageIO.read(new File(com.soyomaker.AppData.getInstance().getCurProject().getPath()
                        +File.separator+"image"+File.separator+"character"+File.separator+
                        enemy.charImg));
                g.drawImage(img, this.getWidth()/2-img.getWidth(null)/2,
                    this.getHeight()/2-img.getHeight(null)/2, null);
            }catch(IOException e){
            }
        }
    };
    chooseEnemyCharImgButton = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jPanel6 = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(EditEnemyDialog.class);
    setTitle(resourceMap.getString("title")); // NOI18N
    setResizable(false);

    jLabel1.setText("名称");
    jLabel1.setName("jLabel1"); // NOI18N

    enemyNameTextField.setName("enemyNameTextField"); // NOI18N

    jLabel2.setText("说明");
    jLabel2.setName("jLabel2"); // NOI18N

    jScrollPane1.setName("jScrollPane1"); // NOI18N

    enemyIntroTextArea.setColumns(20);
    enemyIntroTextArea.setLineWrap(true);
    enemyIntroTextArea.setRows(5);
    enemyIntroTextArea.setName("enemyIntroTextArea"); // NOI18N
    jScrollPane1.setViewportView(enemyIntroTextArea);

    jLabel3.setText("等级");
    jLabel3.setName("jLabel3"); // NOI18N

    enemyLevTextField.setName("enemyLevTextField"); // NOI18N

    jLabel6.setText("力量");
    jLabel6.setName("jLabel6"); // NOI18N

    enemyStreTextField.setName("enemyStreTextField"); // NOI18N

    jLabel7.setText("智力");
    jLabel7.setName("jLabel7"); // NOI18N

    enemyInteTextField.setName("enemyInteTextField"); // NOI18N

    jLabel8.setText("敏捷");
    jLabel8.setName("jLabel8"); // NOI18N

    enemyAgilTextField.setName("enemyAgilTextField"); // NOI18N

    jLabel9.setText("灵巧");
    jLabel9.setName("jLabel9"); // NOI18N

    enemyDexTextField.setName("enemyDexTextField"); // NOI18N

    jLabel10.setText("幸运");
    jLabel10.setName("jLabel10"); // NOI18N

    enemyLuckTextField.setName("enemyLuckTextField"); // NOI18N

    jLabel11.setText("经验");
    jLabel11.setName("jLabel11"); // NOI18N

    enemyExpTextField.setName("enemyExpTextField"); // NOI18N

    jLabel12.setText("金钱");
    jLabel12.setName("jLabel12"); // NOI18N

    enemyMoneyTextField.setName("enemyMoneyTextField"); // NOI18N

    okButton.setText("确定");
    okButton.setName("okButton"); // NOI18N
    okButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            okButtonActionPerformed(evt);
        }
    });

    closeButton.setText("关闭");
    closeButton.setName("closeButton"); // NOI18N
    closeButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            closeButtonActionPerformed(evt);
        }
    });

    jLabel13.setText("体力");
    jLabel13.setName("jLabel13"); // NOI18N

    enemyBodyTextField.setName("enemyBodyTextField"); // NOI18N

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("宝物列表"));
    jPanel2.setName("jPanel2"); // NOI18N

    jToolBar3.setFloatable(false);
    jToolBar3.setRollover(true);
    jToolBar3.setName("jToolBar3"); // NOI18N

    addTreasureButton.setText("添加宝物");
    addTreasureButton.setFocusable(false);
    addTreasureButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    addTreasureButton.setName("addTreasureButton"); // NOI18N
    addTreasureButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    addTreasureButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addTreasureButtonActionPerformed(evt);
        }
    });
    jToolBar3.add(addTreasureButton);

    removeTreasureButton.setText("删除宝物");
    removeTreasureButton.setFocusable(false);
    removeTreasureButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    removeTreasureButton.setName("removeTreasureButton"); // NOI18N
    removeTreasureButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    removeTreasureButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            removeTreasureButtonActionPerformed(evt);
        }
    });
    jToolBar3.add(removeTreasureButton);

    jScrollPane4.setName("jScrollPane4"); // NOI18N

    treasureTable.setModel(mttm);
    treasureTable.setName("treasureTable"); // NOI18N
    treasureTable.setRowHeight(20);
    jScrollPane4.setViewportView(treasureTable);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
    );

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("动作列表"));
    jPanel4.setName("jPanel4"); // NOI18N

    jScrollPane2.setName("jScrollPane2"); // NOI18N

    actionTable.setModel(mactm);
    actionTable.setName("actionTable"); // NOI18N
    actionTable.setRowHeight(20);
    jScrollPane2.setViewportView(actionTable);

    jToolBar4.setFloatable(false);
    jToolBar4.setRollover(true);
    jToolBar4.setName("jToolBar4"); // NOI18N

    addActionButton.setText("添加动作");
    addActionButton.setFocusable(false);
    addActionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    addActionButton.setName("addActionButton"); // NOI18N
    addActionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    addActionButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addActionButtonActionPerformed(evt);
        }
    });
    jToolBar4.add(addActionButton);

    removeActionButton.setText("删除动作");
    removeActionButton.setFocusable(false);
    removeActionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    removeActionButton.setName("removeActionButton"); // NOI18N
    removeActionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    removeActionButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            removeActionButtonActionPerformed(evt);
        }
    });
    jToolBar4.add(removeActionButton);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jToolBar4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
    );

    jLabel4.setText("攻击距离");
    jLabel4.setName("jLabel4"); // NOI18N

    jTextField1.setName("jTextField1"); // NOI18N

    jLabel5.setText("属性");
    jLabel5.setName("jLabel5"); // NOI18N

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox1.setName("jComboBox1"); // NOI18N

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("音效"));
    jPanel3.setName("jPanel3"); // NOI18N

    jLabel14.setText("攻击音效");
    jLabel14.setName("jLabel14"); // NOI18N

    jLabel15.setText("受击音效");
    jLabel15.setName("jLabel15"); // NOI18N

    jLabel16.setText("死亡音效");
    jLabel16.setName("jLabel16"); // NOI18N

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox2.setName("jComboBox2"); // NOI18N

    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox3.setName("jComboBox3"); // NOI18N

    jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox4.setName("jComboBox4"); // NOI18N

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel14)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jComboBox2, 0, 226, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel15)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jComboBox3, 0, 226, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jComboBox4, 0, 226, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel14)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel15)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel16)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("图像"));
    jPanel5.setName("jPanel5"); // NOI18N

    enemyCharImgPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    enemyCharImgPanel.setName("enemyCharImgPanel"); // NOI18N

    javax.swing.GroupLayout enemyCharImgPanelLayout = new javax.swing.GroupLayout(enemyCharImgPanel);
    enemyCharImgPanel.setLayout(enemyCharImgPanelLayout);
    enemyCharImgPanelLayout.setHorizontalGroup(
        enemyCharImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 137, Short.MAX_VALUE)
    );
    enemyCharImgPanelLayout.setVerticalGroup(
        enemyCharImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 178, Short.MAX_VALUE)
    );

    chooseEnemyCharImgButton.setText("设置行走图");
    chooseEnemyCharImgButton.setFocusable(false);
    chooseEnemyCharImgButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    chooseEnemyCharImgButton.setName("chooseEnemyCharImgButton"); // NOI18N
    chooseEnemyCharImgButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    chooseEnemyCharImgButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            chooseEnemyCharImgButtonActionPerformed(evt);
        }
    });

    jButton1.setText("设置动作图");
    jButton1.setName("jButton1"); // NOI18N

    jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    jPanel6.setName("jPanel6"); // NOI18N

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 137, Short.MAX_VALUE)
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 178, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(chooseEnemyCharImgButton)
                .addComponent(enemyCharImgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(6, 6, 6)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1))
            .addContainerGap())
    );

    jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {enemyCharImgPanel, jPanel6});

    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jButton1)
                    .addGap(10, 10, 10)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(chooseEnemyCharImgButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(enemyCharImgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );

    jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {enemyCharImgPanel, jPanel6});

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(enemyNameTextField))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel12)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(enemyLevTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(enemyMoneyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(jComboBox1, 0, 171, Short.MAX_VALUE))))
            .addGap(10, 10, 10)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel10)
                    .addGap(18, 18, 18)
                    .addComponent(enemyLuckTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel7)
                    .addGap(18, 18, 18)
                    .addComponent(enemyInteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel11)
                    .addGap(18, 18, 18)
                    .addComponent(enemyExpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel6)
                    .addGap(18, 18, 18)
                    .addComponent(enemyStreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(enemyBodyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(enemyAgilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(enemyDexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {enemyAgilTextField, enemyBodyTextField, enemyDexTextField, enemyExpTextField, enemyInteTextField, enemyLuckTextField, enemyStreTextField});

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel2, jPanel4});

    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(enemyLevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(enemyMoneyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(closeButton)
                        .addComponent(okButton)))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(enemyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(enemyStreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(enemyInteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(enemyAgilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(enemyBodyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(enemyDexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(enemyLuckTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(enemyExpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {enemyAgilTextField, enemyBodyTextField, enemyDexTextField, enemyExpTextField, enemyInteTextField, enemyLuckTextField, enemyMoneyTextField, enemyStreTextField, jComboBox1, jTextField1});

    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel2, jPanel4});

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        enemy.name = enemyNameTextField.getText();
        enemy.intro = enemyIntroTextArea.getText();
        enemy.lev = Integer.parseInt(enemyLevTextField.getText());
        enemy.body = Integer.parseInt(enemyBodyTextField.getText());
        enemy.stre = Integer.parseInt(enemyStreTextField.getText());
        enemy.inte = Integer.parseInt(enemyInteTextField.getText());
        enemy.agil = Integer.parseInt(enemyAgilTextField.getText());
        enemy.dex = Integer.parseInt(enemyDexTextField.getText());
        enemy.luck = Integer.parseInt(enemyLuckTextField.getText());
        enemy.exp = Integer.parseInt(enemyExpTextField.getText());
        enemy.money = Integer.parseInt(enemyMoneyTextField.getText());
        dispose();
}//GEN-LAST:event_okButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_closeButtonActionPerformed

    private void chooseEnemyCharImgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseEnemyCharImgButtonActionPerformed
        // TODO add your handling code here:
        ChooseImageDialog ebd = new ChooseImageDialog(this, true, "image" + File.separator + "character");
        ebd.setVisible(true);
        if (!ebd.getSelectedImage().equals("")) {
            enemy.charImg = ebd.getSelectedImage();
            enemyCharImgPanel.updateUI();
        }
    }//GEN-LAST:event_chooseEnemyCharImgButtonActionPerformed

    private void addTreasureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTreasureButtonActionPerformed
        // TODO add your handling code here:
        AddModelTreasureDialog etd = new AddModelTreasureDialog(this, true);
        etd.setVisible(true);
        if (etd.getItem() != null) {
            ItemInfo ii = new ItemInfo();
            ii.item = etd.getItem();
            ii.rate = etd.getRate();
            enemy.treasures.add(ii);
            treasureTable.updateUI();
        }
    }//GEN-LAST:event_addTreasureButtonActionPerformed

    private void removeTreasureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTreasureButtonActionPerformed
        // TODO add your handling code here:
        if (treasureTable.getSelectedRow() >= 0 && treasureTable.getSelectedRow() < enemy.treasures.size()) {
            enemy.treasures.remove(treasureTable.getSelectedRow());
            treasureTable.updateUI();
        }
    }//GEN-LAST:event_removeTreasureButtonActionPerformed

    private void addActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionButtonActionPerformed
        // TODO add your handling code here:
        AddModelActionDialog etd = new AddModelActionDialog(this, true);
        etd.setVisible(true);
        if (etd.getSelectAction() != null) {
            enemy.actions.add(etd.getSelectAction());
            actionTable.updateUI();
        }
    }//GEN-LAST:event_addActionButtonActionPerformed

    private void removeActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionButtonActionPerformed
        // TODO add your handling code here:
        if (actionTable.getSelectedRow() >= 0 && actionTable.getSelectedRow() < enemy.actions.size()) {
            enemy.actions.remove(actionTable.getSelectedRow());
            actionTable.updateUI();
        }
    }//GEN-LAST:event_removeActionButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable actionTable;
    private javax.swing.JButton addActionButton;
    private javax.swing.JButton addTreasureButton;
    private javax.swing.JButton chooseEnemyCharImgButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField enemyAgilTextField;
    private javax.swing.JTextField enemyBodyTextField;
    public javax.swing.JPanel enemyCharImgPanel;
    private javax.swing.JTextField enemyDexTextField;
    private javax.swing.JTextField enemyExpTextField;
    private javax.swing.JTextField enemyInteTextField;
    private javax.swing.JTextArea enemyIntroTextArea;
    private javax.swing.JTextField enemyLevTextField;
    private javax.swing.JTextField enemyLuckTextField;
    private javax.swing.JTextField enemyMoneyTextField;
    private javax.swing.JTextField enemyNameTextField;
    private javax.swing.JTextField enemyStreTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JButton okButton;
    private javax.swing.JButton removeActionButton;
    private javax.swing.JButton removeTreasureButton;
    private javax.swing.JTable treasureTable;
    // End of variables declaration//GEN-END:variables
}
