/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditPlayerDialog.java
 *
 * Created on 2011-9-30, 22:16:00
 */
package com.soyomaker.data.ui;

import com.soyomaker.AppData;
import com.soyomaker.data.model.Model;
import com.soyomaker.data.model.Player;
import com.soyomaker.data.model.Vocation;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author Administrator
 */
public class EditPlayerDialog extends javax.swing.JDialog {

    /** Creates new form EditPlayerDialog
     * @param parent
     * @param modal
     * @param player
     */
    public EditPlayerDialog(PlayerPanel parent, boolean modal, Player player) {
        setModal(modal);
        initComponents();
        setLocationRelativeTo(null);
        setPlayer(player);
    }
    private Player player;

    private void setPlayer(Player player) {
        this.player = player;
        playerNameTextField.setText(player.name);
        playerIntroTextArea.setText(player.intro);
        playerStartLevTextField.setText(player.startLev + "");
        playerMaxLevTextField.setText(player.maxLev + "");
        playerVocationComboBox.removeAllItems();
        playerVocationComboBox.addItem("");
        for (int i = 0; i < AppData.getInstance().getCurProject().getDataManager().size(Model.VOCATION); i++) {
            playerVocationComboBox.addItem((Vocation) AppData.getInstance().getCurProject().getDataManager().getModels(Model.VOCATION)[i]);
        }
        playerVocationComboBox.setSelectedIndex(player.vocationIndex + 1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        playerNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerIntroTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        headImgSetButton = new javax.swing.JButton();
        playerHeadImgPanel = new javax.swing.JPanel(){
            public void paint(Graphics g){
                g.setColor(new Color(255,153,153));
                g.fillRect(0, 0, this.getWidth(), this.getHeight());
                Image img;
                if(player.headImg.equals("")){
                    return;
                }
                try{
                    img = ImageIO.read(new File(com.soyomaker.AppData.getInstance().getCurProject().getPath()
                        +File.separator+"image"+File.separator+"face"+File.separator+
                        player.headImg));
                g.drawImage(img, this.getWidth()/2-img.getWidth(null)/2,
                    this.getHeight()/2-img.getHeight(null)/2, null);
            }catch(IOException e){
            }
        }
    }
    ;
    jPanel3 = new javax.swing.JPanel();
    jToolBar2 = new javax.swing.JToolBar();
    charImgSetButton = new javax.swing.JButton();
    playerCharImgPanel = new javax.swing.JPanel(){
        public void paint(Graphics g){
            g.setColor(new Color(255,153,153));
            g.fillRect(0, 0, this.getWidth(), this.getHeight());
            Image img;
            if(player.charImg.equals("")){
                return;
            }
            try{
                img = ImageIO.read(new File(com.soyomaker.AppData.getInstance().getCurProject().getPath()
                    +File.separator+"image"+File.separator+"character"+File.separator+
                    player.charImg));
            g.drawImage(img, this.getWidth()/2-img.getWidth(null)/2,
                this.getHeight()/2-img.getHeight(null)/2, null);
        }catch(IOException e){
        }
    }
    };
    jPanel5 = new javax.swing.JPanel();
    jToolBar3 = new javax.swing.JToolBar();
    battleImgSetButton = new javax.swing.JButton();
    playerBattleImgPanel = new javax.swing.JPanel(){
        public void paint(Graphics g){
            g.setColor(new Color(255,153,153));
            g.fillRect(0, 0, this.getWidth(), this.getHeight());
            Image img;
            if(player.battleImg.equals("")){
                return;
            }
            try{
                img = ImageIO.read(new File(com.soyomaker.AppData.getInstance().getCurProject().getPath()
                    +File.separator+"image"+File.separator+"battler"+File.separator+
                    player.battleImg));
            g.drawImage(img, this.getWidth()/2-img.getWidth(null)/2,
                this.getHeight()/2-img.getHeight(null)/2, null);
        }catch(IOException e){
        }
    }
    };
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    playerStartLevTextField = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    playerMaxLevTextField = new javax.swing.JTextField();
    jPanel7 = new javax.swing.JPanel();
    strePanel = new javax.swing.JPanel();
    jLabel8 = new javax.swing.JLabel();
    bodyPanel = new javax.swing.JPanel();
    jLabel13 = new javax.swing.JLabel();
    dexPanel = new javax.swing.JPanel();
    jLabel12 = new javax.swing.JLabel();
    agilPanel = new javax.swing.JPanel();
    jLabel11 = new javax.swing.JLabel();
    intePanel = new javax.swing.JPanel();
    jLabel9 = new javax.swing.JLabel();
    luckPanel = new javax.swing.JPanel();
    jLabel14 = new javax.swing.JLabel();
    expPanel = new javax.swing.JPanel();
    jLabel10 = new javax.swing.JLabel();
    closeButton = new javax.swing.JButton();
    okButton = new javax.swing.JButton();
    playerVocationComboBox = new javax.swing.JComboBox();
    applyButton = new javax.swing.JButton();
    jLabel15 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox();
    jLabel16 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(EditPlayerDialog.class);
    setTitle(resourceMap.getString("title")); // NOI18N
    setResizable(false);

    jLabel1.setText("名称");
    jLabel1.setName("jLabel1"); // NOI18N

    playerNameTextField.setName("playerNameTextField"); // NOI18N

    jLabel2.setText("介绍");
    jLabel2.setName("jLabel2"); // NOI18N

    jScrollPane1.setName("jScrollPane1"); // NOI18N

    playerIntroTextArea.setColumns(20);
    playerIntroTextArea.setLineWrap(true);
    playerIntroTextArea.setRows(5);
    playerIntroTextArea.setName("playerIntroTextArea"); // NOI18N
    jScrollPane1.setViewportView(playerIntroTextArea);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("头像"));
    jPanel1.setName("jPanel1"); // NOI18N

    jToolBar1.setFloatable(false);
    jToolBar1.setRollover(true);
    jToolBar1.setName("jToolBar1"); // NOI18N

    headImgSetButton.setText("设置");
    headImgSetButton.setFocusable(false);
    headImgSetButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    headImgSetButton.setName("headImgSetButton"); // NOI18N
    headImgSetButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    headImgSetButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            headImgSetButtonActionPerformed(evt);
        }
    });
    jToolBar1.add(headImgSetButton);

    playerHeadImgPanel.setName("playerHeadImgPanel"); // NOI18N

    javax.swing.GroupLayout playerHeadImgPanelLayout = new javax.swing.GroupLayout(playerHeadImgPanel);
    playerHeadImgPanel.setLayout(playerHeadImgPanelLayout);
    playerHeadImgPanelLayout.setHorizontalGroup(
        playerHeadImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 172, Short.MAX_VALUE)
    );
    playerHeadImgPanelLayout.setVerticalGroup(
        playerHeadImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 111, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        .addComponent(playerHeadImgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(playerHeadImgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("行走图"));
    jPanel3.setName("jPanel3"); // NOI18N

    jToolBar2.setFloatable(false);
    jToolBar2.setRollover(true);
    jToolBar2.setName("jToolBar2"); // NOI18N

    charImgSetButton.setText("设置");
    charImgSetButton.setFocusable(false);
    charImgSetButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    charImgSetButton.setName("charImgSetButton"); // NOI18N
    charImgSetButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    charImgSetButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            charImgSetButtonActionPerformed(evt);
        }
    });
    jToolBar2.add(charImgSetButton);

    playerCharImgPanel.setName("playerCharImgPanel"); // NOI18N

    javax.swing.GroupLayout playerCharImgPanelLayout = new javax.swing.GroupLayout(playerCharImgPanel);
    playerCharImgPanel.setLayout(playerCharImgPanelLayout);
    playerCharImgPanelLayout.setHorizontalGroup(
        playerCharImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 172, Short.MAX_VALUE)
    );
    playerCharImgPanelLayout.setVerticalGroup(
        playerCharImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 111, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        .addComponent(playerCharImgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(playerCharImgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("战斗图"));
    jPanel5.setName("jPanel5"); // NOI18N

    jToolBar3.setFloatable(false);
    jToolBar3.setRollover(true);
    jToolBar3.setName("jToolBar3"); // NOI18N

    battleImgSetButton.setText("设置");
    battleImgSetButton.setFocusable(false);
    battleImgSetButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    battleImgSetButton.setName("battleImgSetButton"); // NOI18N
    battleImgSetButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    battleImgSetButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            battleImgSetButtonActionPerformed(evt);
        }
    });
    jToolBar3.add(battleImgSetButton);

    playerBattleImgPanel.setName("playerBattleImgPanel"); // NOI18N

    javax.swing.GroupLayout playerBattleImgPanelLayout = new javax.swing.GroupLayout(playerBattleImgPanel);
    playerBattleImgPanel.setLayout(playerBattleImgPanelLayout);
    playerBattleImgPanelLayout.setHorizontalGroup(
        playerBattleImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 172, Short.MAX_VALUE)
    );
    playerBattleImgPanelLayout.setVerticalGroup(
        playerBattleImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 123, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jToolBar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        .addComponent(playerBattleImgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(playerBattleImgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(7, Short.MAX_VALUE))
    );

    jLabel3.setText("职业");
    jLabel3.setName("jLabel3"); // NOI18N

    jLabel4.setText("初始等级");
    jLabel4.setName("jLabel4"); // NOI18N

    playerStartLevTextField.setText("0");
    playerStartLevTextField.setName("playerStartLevTextField"); // NOI18N

    jLabel5.setText("最大等级");
    jLabel5.setName("jLabel5"); // NOI18N

    playerMaxLevTextField.setText("99");
    playerMaxLevTextField.setName("playerMaxLevTextField"); // NOI18N

    jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("成长曲线"));
    jPanel7.setName("jPanel7"); // NOI18N

    strePanel.setBackground(new java.awt.Color(255, 255, 255));
    strePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    strePanel.setName("strePanel"); // NOI18N
    strePanel.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            strePanelMouseClicked(evt);
        }
    });

    jLabel8.setText("点击设置力量");
    jLabel8.setName("jLabel8"); // NOI18N

    javax.swing.GroupLayout strePanelLayout = new javax.swing.GroupLayout(strePanel);
    strePanel.setLayout(strePanelLayout);
    strePanelLayout.setHorizontalGroup(
        strePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(strePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
            .addContainerGap())
    );
    strePanelLayout.setVerticalGroup(
        strePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(strePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel8)
            .addContainerGap(80, Short.MAX_VALUE))
    );

    bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
    bodyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    bodyPanel.setName("bodyPanel"); // NOI18N
    bodyPanel.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            bodyPanelMouseClicked(evt);
        }
    });

    jLabel13.setText("点击设置体力");
    jLabel13.setName("jLabel13"); // NOI18N

    javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
    bodyPanel.setLayout(bodyPanelLayout);
    bodyPanelLayout.setHorizontalGroup(
        bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(bodyPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
            .addContainerGap())
    );
    bodyPanelLayout.setVerticalGroup(
        bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(bodyPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel13)
            .addContainerGap(80, Short.MAX_VALUE))
    );

    dexPanel.setBackground(new java.awt.Color(255, 255, 255));
    dexPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    dexPanel.setName("dexPanel"); // NOI18N
    dexPanel.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            dexPanelMouseClicked(evt);
        }
    });

    jLabel12.setText("点击设置灵巧");
    jLabel12.setName("jLabel12"); // NOI18N

    javax.swing.GroupLayout dexPanelLayout = new javax.swing.GroupLayout(dexPanel);
    dexPanel.setLayout(dexPanelLayout);
    dexPanelLayout.setHorizontalGroup(
        dexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(dexPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
            .addContainerGap())
    );
    dexPanelLayout.setVerticalGroup(
        dexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(dexPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel12)
            .addContainerGap(80, Short.MAX_VALUE))
    );

    agilPanel.setBackground(new java.awt.Color(255, 255, 255));
    agilPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    agilPanel.setName("agilPanel"); // NOI18N
    agilPanel.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            agilPanelMouseClicked(evt);
        }
    });

    jLabel11.setText("点击设置敏捷");
    jLabel11.setName("jLabel11"); // NOI18N

    javax.swing.GroupLayout agilPanelLayout = new javax.swing.GroupLayout(agilPanel);
    agilPanel.setLayout(agilPanelLayout);
    agilPanelLayout.setHorizontalGroup(
        agilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(agilPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
            .addContainerGap())
    );
    agilPanelLayout.setVerticalGroup(
        agilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(agilPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel11)
            .addContainerGap(80, Short.MAX_VALUE))
    );

    intePanel.setBackground(new java.awt.Color(255, 255, 255));
    intePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    intePanel.setName("intePanel"); // NOI18N
    intePanel.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            intePanelMouseClicked(evt);
        }
    });

    jLabel9.setText("点击设置智力");
    jLabel9.setName("jLabel9"); // NOI18N

    javax.swing.GroupLayout intePanelLayout = new javax.swing.GroupLayout(intePanel);
    intePanel.setLayout(intePanelLayout);
    intePanelLayout.setHorizontalGroup(
        intePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(intePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
            .addContainerGap())
    );
    intePanelLayout.setVerticalGroup(
        intePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(intePanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel9)
            .addContainerGap(80, Short.MAX_VALUE))
    );

    luckPanel.setBackground(new java.awt.Color(255, 255, 255));
    luckPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    luckPanel.setName("luckPanel"); // NOI18N
    luckPanel.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            luckPanelMouseClicked(evt);
        }
    });

    jLabel14.setText("点击设置幸运");
    jLabel14.setName("jLabel14"); // NOI18N

    javax.swing.GroupLayout luckPanelLayout = new javax.swing.GroupLayout(luckPanel);
    luckPanel.setLayout(luckPanelLayout);
    luckPanelLayout.setHorizontalGroup(
        luckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(luckPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
            .addContainerGap())
    );
    luckPanelLayout.setVerticalGroup(
        luckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(luckPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel14)
            .addContainerGap(80, Short.MAX_VALUE))
    );

    expPanel.setBackground(new java.awt.Color(255, 255, 255));
    expPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    expPanel.setName("expPanel"); // NOI18N
    expPanel.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            expPanelMouseClicked(evt);
        }
    });

    jLabel10.setText("点击设置经验值");
    jLabel10.setName("jLabel10"); // NOI18N

    javax.swing.GroupLayout expPanelLayout = new javax.swing.GroupLayout(expPanel);
    expPanel.setLayout(expPanelLayout);
    expPanelLayout.setHorizontalGroup(
        expPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(expPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
            .addContainerGap())
    );
    expPanelLayout.setVerticalGroup(
        expPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(expPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel10)
            .addContainerGap(80, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dexPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(intePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addComponent(expPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(strePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(agilPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(luckPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );

    jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {agilPanel, bodyPanel, dexPanel, expPanel, intePanel, luckPanel, strePanel});

    jPanel7Layout.setVerticalGroup(
        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel7Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(strePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(intePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(expPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(agilPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(dexPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(luckPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(20, Short.MAX_VALUE))
    );

    jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {agilPanel, bodyPanel, dexPanel, expPanel, intePanel, luckPanel, strePanel});

    closeButton.setText("关闭");
    closeButton.setName("closeButton"); // NOI18N
    closeButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            closeButtonActionPerformed(evt);
        }
    });

    okButton.setText("确定");
    okButton.setName("okButton"); // NOI18N
    okButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            okButtonActionPerformed(evt);
        }
    });

    playerVocationComboBox.setName("playerVocationComboBox"); // NOI18N

    applyButton.setText("应用");
    applyButton.setName("applyButton"); // NOI18N
    applyButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            applyButtonActionPerformed(evt);
        }
    });

    jLabel15.setText("属性");
    jLabel15.setName("jLabel15"); // NOI18N

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBox1.setName("jComboBox1"); // NOI18N

    jLabel16.setText("攻击距离");
    jLabel16.setName("jLabel16"); // NOI18N

    jTextField1.setText("0");
    jTextField1.setName("jTextField1"); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(playerMaxLevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(applyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                                .addComponent(playerNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                .addComponent(playerVocationComboBox, 0, 233, Short.MAX_VALUE)
                                .addComponent(playerStartLevTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel3, jPanel5});

    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel5, 0, 187, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(playerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(playerVocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(playerStartLevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(playerMaxLevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(applyButton)
                                .addComponent(jLabel16)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(closeButton)
                .addComponent(okButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel3});

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        player.name = playerNameTextField.getText();
        player.intro = playerIntroTextArea.getText();
        player.startLev = Integer.parseInt(playerStartLevTextField.getText());
        player.maxLev = Integer.parseInt(playerMaxLevTextField.getText());
        if (playerVocationComboBox.getSelectedItem() == null || playerVocationComboBox.getSelectedItem().toString().equals("")) {
            player.vocationIndex = -1;
        } else {
            player.vocationIndex = playerVocationComboBox.getSelectedIndex() - 1;
        }
        dispose();
}//GEN-LAST:event_okButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_closeButtonActionPerformed

    private void headImgSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headImgSetButtonActionPerformed
        // TODO add your handling code here:
        ChooseImageDialog ebd = new ChooseImageDialog(this, true, "image" + File.separator + "face");
        ebd.setVisible(true);
        if (!ebd.getSelectedImage().equals("")) {
            player.headImg = ebd.getSelectedImage();
            playerHeadImgPanel.updateUI();
        }
    }//GEN-LAST:event_headImgSetButtonActionPerformed

    private void charImgSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charImgSetButtonActionPerformed
        // TODO add your handling code here:
        ChooseImageDialog ebd = new ChooseImageDialog(this, true, "image" + File.separator + "character");
        ebd.setVisible(true);
        if (!ebd.getSelectedImage().equals("")) {
            player.charImg = ebd.getSelectedImage();
            playerCharImgPanel.updateUI();
        }
    }//GEN-LAST:event_charImgSetButtonActionPerformed

    private void battleImgSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battleImgSetButtonActionPerformed
        // TODO add your handling code here:
        ChooseImageDialog ebd = new ChooseImageDialog(this, true, "image" + File.separator + "battler");
        ebd.setVisible(true);
        if (!ebd.getSelectedImage().equals("")) {
            player.battleImg = ebd.getSelectedImage();
            playerBattleImgPanel.updateUI();
        }
    }//GEN-LAST:event_battleImgSetButtonActionPerformed

    private void strePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_strePanelMouseClicked
        // TODO add your handling code here:
        PlayerPowerDialog ped = new PlayerPowerDialog(this, true, player, Player.STRE);
        ped.setVisible(true);
    }//GEN-LAST:event_strePanelMouseClicked

    private void intePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_intePanelMouseClicked
        // TODO add your handling code here:
        PlayerPowerDialog ped = new PlayerPowerDialog(this, true, player, Player.ITEM);
        ped.setVisible(true);
    }//GEN-LAST:event_intePanelMouseClicked

    private void expPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expPanelMouseClicked
        // TODO add your handling code here:
        PlayerPowerDialog ped = new PlayerPowerDialog(this, true, player, Player.EXP);
        ped.setVisible(true);
    }//GEN-LAST:event_expPanelMouseClicked

    private void agilPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agilPanelMouseClicked
        // TODO add your handling code here:
        PlayerPowerDialog ped = new PlayerPowerDialog(this, true, player, Player.AGIL);
        ped.setVisible(true);
    }//GEN-LAST:event_agilPanelMouseClicked

    private void dexPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dexPanelMouseClicked
        // TODO add your handling code here:
        PlayerPowerDialog ped = new PlayerPowerDialog(this, true, player, Player.DEX);
        ped.setVisible(true);
    }//GEN-LAST:event_dexPanelMouseClicked

    private void bodyPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bodyPanelMouseClicked
        // TODO add your handling code here:
        PlayerPowerDialog ped = new PlayerPowerDialog(this, true, player, Player.BODY);
        ped.setVisible(true);
    }//GEN-LAST:event_bodyPanelMouseClicked

    private void luckPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_luckPanelMouseClicked
        // TODO add your handling code here:
        PlayerPowerDialog ped = new PlayerPowerDialog(this, true, player, Player.LUCK);
        ped.setVisible(true);
    }//GEN-LAST:event_luckPanelMouseClicked

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        // TODO add your handling code here:
        player.maxLev = Integer.parseInt(playerMaxLevTextField.getText());
    }//GEN-LAST:event_applyButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agilPanel;
    private javax.swing.JButton applyButton;
    private javax.swing.JButton battleImgSetButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton charImgSetButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel dexPanel;
    private javax.swing.JPanel expPanel;
    private javax.swing.JButton headImgSetButton;
    private javax.swing.JPanel intePanel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JPanel luckPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel playerBattleImgPanel;
    private javax.swing.JPanel playerCharImgPanel;
    private javax.swing.JPanel playerHeadImgPanel;
    private javax.swing.JTextArea playerIntroTextArea;
    private javax.swing.JTextField playerMaxLevTextField;
    private javax.swing.JTextField playerNameTextField;
    private javax.swing.JTextField playerStartLevTextField;
    private javax.swing.JComboBox playerVocationComboBox;
    private javax.swing.JPanel strePanel;
    // End of variables declaration//GEN-END:variables
}
