/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatusPanel.java
 *
 * Created on 2011-9-3, 23:39:54
 */
package com.soyomaker.data.ui;

import com.soyomaker.AppData;
import com.soyomaker.data.listener.DataChangeListener;
import com.soyomaker.data.listener.DataChangedEvent;
import com.soyomaker.data.model.Config;
import com.soyomaker.data.model.Enemy;
import com.soyomaker.data.model.EnemyTroop;
import com.soyomaker.data.model.Equip;
import com.soyomaker.data.model.Item;
import com.soyomaker.data.model.Model;
import com.soyomaker.data.model.Player;
import com.soyomaker.data.model.Skill;
import com.soyomaker.data.model.Buff;
import com.soyomaker.data.model.BuffTableModel;
import com.soyomaker.data.model.Vocation;
import com.soyomaker.widget.JTabelComboBoxRender;
import com.soyomaker.widget.JTableComboBoxEditor;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Administrator
 */
public class StatusPanel extends javax.swing.JPanel implements DataChangeListener {

    /** Creates new form StatusPanel */
    public StatusPanel() {
        initComponents();
        AppData.getInstance().getCurProject().getDataManager().addDataChangeListener(this);
        TableColumnModel tcm = statusTable.getColumnModel();
        TableColumn targetC = tcm.getColumn(4);
        JTabelComboBoxRender strT = new JTabelComboBoxRender(Buff.lastKinds);
        JTableComboBoxEditor steT = new JTableComboBoxEditor(Buff.lastKinds);
        targetC.setCellRenderer(strT);
        targetC.setCellEditor(steT);
    }
    private BuffTableModel stm = new BuffTableModel();

    /**
     *
     */
    public void refresh() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        addStatusButton = new javax.swing.JButton();
        editStatusButton = new javax.swing.JButton();
        removeStatusButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusTable = new javax.swing.JTable();

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        addStatusButton.setText("添加状态");
        addStatusButton.setFocusable(false);
        addStatusButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addStatusButton.setName("addStatusButton"); // NOI18N
        addStatusButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStatusButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(addStatusButton);

        editStatusButton.setText("编辑状态");
        editStatusButton.setFocusable(false);
        editStatusButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editStatusButton.setName("editStatusButton"); // NOI18N
        editStatusButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStatusButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(editStatusButton);

        removeStatusButton.setText("删除状态");
        removeStatusButton.setFocusable(false);
        removeStatusButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeStatusButton.setName("removeStatusButton"); // NOI18N
        removeStatusButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStatusButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(removeStatusButton);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        statusTable.setModel(stm);
        statusTable.setName("statusTable"); // NOI18N
        statusTable.setRowHeight(20);
        jScrollPane1.setViewportView(statusTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStatusButtonActionPerformed
        // TODO add your handling code here:
        Buff status = new Buff();
        status.setIndex(AppData.getInstance().getCurProject().getDataManager().allocateIndex(Model.STATUS));
        AppData.getInstance().getCurProject().getDataManager().saveModel(Model.STATUS, status);
        EditBuffDialog eid = new EditBuffDialog(this, true, status);
        eid.setVisible(true);
    }//GEN-LAST:event_addStatusButtonActionPerformed

    private void editStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStatusButtonActionPerformed
        // TODO add your handling code here:
        int id = statusTable.getSelectedRow();
        if (id < 0 || id >= AppData.getInstance().getCurProject().getDataManager().size(Model.STATUS)) {
            return;
        }
        Buff status = (Buff) AppData.getInstance().getCurProject().getDataManager().getModels(Model.STATUS)[id];
        EditBuffDialog eid = new EditBuffDialog(this, true, status);
        eid.setVisible(true);
    }//GEN-LAST:event_editStatusButtonActionPerformed

    private void removeStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStatusButtonActionPerformed
        // TODO add your handling code here:
        int id = statusTable.getSelectedRow();
        if (id < 0 || id >= AppData.getInstance().getCurProject().getDataManager().size(Model.STATUS)) {
            return;
        }
        AppData.getInstance().getCurProject().getDataManager().removeModel(Model.STATUS, AppData.getInstance().getCurProject().getDataManager().getModels(Model.STATUS)[id].getIndex());
    }//GEN-LAST:event_removeStatusButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStatusButton;
    private javax.swing.JButton editStatusButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton removeStatusButton;
    private javax.swing.JTable statusTable;
    // End of variables declaration//GEN-END:variables

    public void configChanged(DataChangedEvent sce, Config config) {
    }

    public void playerAdded(DataChangedEvent sce, Player player) {
    }

    public void playerRemoved(DataChangedEvent sce, int id) {
    }

    public void vocationAdded(DataChangedEvent sce, Vocation vocation) {
    }

    public void vocationRemoved(DataChangedEvent sce, int id) {
    }

    public void statusAdded(DataChangedEvent sce, Buff status) {
        statusTable.updateUI();
    }

    public void statusRemoved(DataChangedEvent sce, int id) {
        statusTable.updateUI();
    }

    public void skillAdded(DataChangedEvent sce, Skill skill) {
    }

    public void skillRemoved(DataChangedEvent sce, int id) {
    }

    public void enemyAdded(DataChangedEvent sce, Enemy enemy) {
    }

    public void enemyRemoved(DataChangedEvent sce, int id) {
    }

    public void enemyTroopAdded(DataChangedEvent sce, EnemyTroop enemytroop) {
    }

    public void enemyTroopRemoved(DataChangedEvent sce, int id) {
    }

    public void equipAdded(DataChangedEvent sce, Equip equip) {
    }

    public void equipRemoved(DataChangedEvent sce, int id) {
    }

    public void itemAdded(DataChangedEvent sce, Item item) {
    }

    public void itemRemoved(DataChangedEvent sce, int id) {
    }
}
