/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddModelEquipDialog.java
 *
 * Created on 2011-10-9, 0:29:15
 */
package com.soyomaker.data.ui;

import com.soyomaker.AppData;
import com.soyomaker.data.model.Equip;
import com.soyomaker.data.model.Model;
import java.util.ArrayList;

/**
 *
 * @author Administrator
 */
public class AddModelEquipDialog extends javax.swing.JDialog {

    /** Creates new form AddModelEquipDialog
     * @param parent
     * @param modal
     */
    public AddModelEquipDialog(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        Equip[] equips = (Equip[]) AppData.getInstance().getCurProject().getDataManager().getModels(Model.EQUIP);
        for (int i = 0; i < equips.length; i++) {
            if (equips[i].equipType == Equip.HELM) {
                helmComboBox.addItem(equips[i]);
            }
        }
        for (int i = 0; i < equips.length; i++) {
            if (equips[i].equipType == Equip.JEWELRY) {
                jewelryComboBox.addItem(equips[i]);
            }
        }
        for (int i = 0; i < equips.length; i++) {
            if (equips[i].equipType == Equip.WEAPON) {
                weaponComboBox.addItem(equips[i]);
            }
        }
        for (int i = 0; i < equips.length; i++) {
            if (equips[i].equipType == Equip.SHIELD) {
                shieldComboBox.addItem(equips[i]);
            }
        }
        for (int i = 0; i < equips.length; i++) {
            if (equips[i].equipType == Equip.ARMOUR) {
                armourComboBox.addItem(equips[i]);
            }
        }
        for (int i = 0; i < equips.length; i++) {
            if (equips[i].equipType == Equip.BOOTS) {
                bootsComboBox.addItem(equips[i]);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        helmComboBox = new javax.swing.JComboBox();
        okButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rateTextField = new javax.swing.JTextField();
        helmRadioButton = new javax.swing.JRadioButton();
        jewelryRadioButton = new javax.swing.JRadioButton();
        weaponRadioButton = new javax.swing.JRadioButton();
        shieldRadioButton = new javax.swing.JRadioButton();
        armourRadioButton = new javax.swing.JRadioButton();
        bootsRadioButton = new javax.swing.JRadioButton();
        jewelryComboBox = new javax.swing.JComboBox();
        weaponComboBox = new javax.swing.JComboBox();
        shieldComboBox = new javax.swing.JComboBox();
        armourComboBox = new javax.swing.JComboBox();
        bootsComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(AddModelEquipDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setResizable(false);

        helmComboBox.setName("helmComboBox"); // NOI18N

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancleButton.setText("关闭");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("掉落率");
        jLabel2.setName("jLabel2"); // NOI18N

        rateTextField.setText("0");
        rateTextField.setName("rateTextField"); // NOI18N

        buttonGroup1.add(helmRadioButton);
        helmRadioButton.setSelected(true);
        helmRadioButton.setText("头盔");
        helmRadioButton.setName("helmRadioButton"); // NOI18N
        helmRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                helmRadioButtonStateChanged(evt);
            }
        });

        buttonGroup1.add(jewelryRadioButton);
        jewelryRadioButton.setText("饰品");
        jewelryRadioButton.setName("jewelryRadioButton"); // NOI18N
        jewelryRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jewelryRadioButtonStateChanged(evt);
            }
        });

        buttonGroup1.add(weaponRadioButton);
        weaponRadioButton.setText("武器");
        weaponRadioButton.setName("weaponRadioButton"); // NOI18N
        weaponRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                weaponRadioButtonStateChanged(evt);
            }
        });

        buttonGroup1.add(shieldRadioButton);
        shieldRadioButton.setText("盾牌");
        shieldRadioButton.setName("shieldRadioButton"); // NOI18N
        shieldRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shieldRadioButtonStateChanged(evt);
            }
        });

        buttonGroup1.add(armourRadioButton);
        armourRadioButton.setText("铠甲");
        armourRadioButton.setName("armourRadioButton"); // NOI18N
        armourRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                armourRadioButtonStateChanged(evt);
            }
        });

        buttonGroup1.add(bootsRadioButton);
        bootsRadioButton.setText("战靴");
        bootsRadioButton.setName("bootsRadioButton"); // NOI18N
        bootsRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bootsRadioButtonStateChanged(evt);
            }
        });

        jewelryComboBox.setEnabled(false);
        jewelryComboBox.setName("jewelryComboBox"); // NOI18N

        weaponComboBox.setEnabled(false);
        weaponComboBox.setName("weaponComboBox"); // NOI18N

        shieldComboBox.setEnabled(false);
        shieldComboBox.setName("shieldComboBox"); // NOI18N

        armourComboBox.setEnabled(false);
        armourComboBox.setName("armourComboBox"); // NOI18N

        bootsComboBox.setEnabled(false);
        bootsComboBox.setName("bootsComboBox"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(helmRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(helmComboBox, 0, 200, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jewelryRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(jewelryComboBox, 0, 200, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weaponRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(weaponComboBox, 0, 200, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shieldRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(shieldComboBox, 0, 200, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(armourRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(armourComboBox, 0, 200, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bootsRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(bootsComboBox, 0, 200, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(rateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(cancleButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(helmRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jewelryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jewelryRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(weaponRadioButton)
                    .addComponent(weaponComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shieldRadioButton)
                    .addComponent(shieldComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(armourRadioButton)
                    .addComponent(armourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bootsRadioButton)
                    .addComponent(bootsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancleButton)
                    .addComponent(okButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @return
     */
    public Equip getSelectEquip() {
        if (!isOk) {
            return null;
        }
        return equip;
    }
    private Equip equip;
    private boolean isOk;
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        if (helmRadioButton.isSelected()) {
            if (helmComboBox.getSelectedIndex() != -1) {
                equip = (Equip) helmComboBox.getSelectedItem();
                equip.rate = Integer.parseInt(rateTextField.getText());
            }
        }
        if (jewelryRadioButton.isSelected()) {
            if (jewelryComboBox.getSelectedIndex() != -1) {
                equip = (Equip) jewelryComboBox.getSelectedItem();
                equip.rate = Integer.parseInt(rateTextField.getText());
            }
        }
        if (weaponRadioButton.isSelected()) {
            if (weaponComboBox.getSelectedIndex() != -1) {
                equip = (Equip) weaponComboBox.getSelectedItem();
                equip.rate = Integer.parseInt(rateTextField.getText());
            }
        }
        if (shieldRadioButton.isSelected()) {
            if (shieldComboBox.getSelectedIndex() != -1) {
                equip = (Equip) shieldComboBox.getSelectedItem();
                equip.rate = Integer.parseInt(rateTextField.getText());
            }
        }
        if (armourRadioButton.isSelected()) {
            if (armourComboBox.getSelectedIndex() != -1) {
                equip = (Equip) armourComboBox.getSelectedItem();
                equip.rate = Integer.parseInt(rateTextField.getText());
            }
        }
        if (bootsRadioButton.isSelected()) {
            if (bootsComboBox.getSelectedIndex() != -1) {
                equip = (Equip) bootsComboBox.getSelectedItem();
                equip.rate = Integer.parseInt(rateTextField.getText());
            }
        }
        isOk = true;
        dispose();
}//GEN-LAST:event_okButtonActionPerformed

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        isOk = false;
        dispose();
}//GEN-LAST:event_cancleButtonActionPerformed

    private void helmRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_helmRadioButtonStateChanged
        // TODO add your handling code here:
        helmComboBox.setEnabled(helmRadioButton.isSelected());
    }//GEN-LAST:event_helmRadioButtonStateChanged

    private void jewelryRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jewelryRadioButtonStateChanged
        // TODO add your handling code here:
        jewelryComboBox.setEnabled(jewelryRadioButton.isSelected());
    }//GEN-LAST:event_jewelryRadioButtonStateChanged

    private void weaponRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_weaponRadioButtonStateChanged
        // TODO add your handling code here:
        weaponComboBox.setEnabled(weaponRadioButton.isSelected());
    }//GEN-LAST:event_weaponRadioButtonStateChanged

    private void armourRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_armourRadioButtonStateChanged
        // TODO add your handling code here:
        armourComboBox.setEnabled(armourRadioButton.isSelected());
    }//GEN-LAST:event_armourRadioButtonStateChanged

    private void bootsRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bootsRadioButtonStateChanged
        // TODO add your handling code here:
        bootsComboBox.setEnabled(bootsRadioButton.isSelected());
    }//GEN-LAST:event_bootsRadioButtonStateChanged

    private void shieldRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_shieldRadioButtonStateChanged
        // TODO add your handling code here:
        shieldComboBox.setEnabled(shieldRadioButton.isSelected());
    }//GEN-LAST:event_shieldRadioButtonStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AddModelEquipDialog dialog = new AddModelEquipDialog(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox armourComboBox;
    private javax.swing.JRadioButton armourRadioButton;
    private javax.swing.JComboBox bootsComboBox;
    private javax.swing.JRadioButton bootsRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancleButton;
    private javax.swing.JComboBox helmComboBox;
    private javax.swing.JRadioButton helmRadioButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox jewelryComboBox;
    private javax.swing.JRadioButton jewelryRadioButton;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField rateTextField;
    private javax.swing.JComboBox shieldComboBox;
    private javax.swing.JRadioButton shieldRadioButton;
    private javax.swing.JComboBox weaponComboBox;
    private javax.swing.JRadioButton weaponRadioButton;
    // End of variables declaration//GEN-END:variables
}
