/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NpcStatePane.java
 *
 * Created on 2011-6-7, 1:45:46
 */
package com.soyostar.widge;

import com.soyostar.dialog.EventManagerDialog;
import com.soyostar.dialog.NpcMoveImageDialog;
import com.soyostar.dialog.ScriptDialog;
import com.soyostar.dialog.event.gameperformance.MoveDialog;
import com.soyostar.model.map.NpcState;
import com.soyostar.script.ScriptManagerDialog;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class NpcStatePane extends javax.swing.JPanel implements TableModelListener {

    /** Creates new form NpcStatePane
     * @param emd 
     */
    public NpcStatePane(EventManagerDialog emd) {
        this.emd = emd;
        initComponents();
//        addScript();
    }
    private NpcState npcState = new NpcState();
    private String[] col = {"执行内容"};
    /**
     * 
     */
    public DefaultTableModel eventTM = new javax.swing.table.DefaultTableModel(col, 0) {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * 
     * @return
     */
    public NpcState getNpcState() {
        return npcState;
    }

    /**
     * 
     * @param state
     */
    public void setNpcState(NpcState state) {

        npcState = state;
        switch (state.getFace()) {
            case NpcState.UP:
                upRadioButton.setSelected(true);
                break;
            case NpcState.DOWN:
                downRadioButton.setSelected(true);
                break;
            case NpcState.LEFT:
                leftRadioButton.setSelected(true);
                break;
            case NpcState.RIGHT:
                rightRadioButton.setSelected(true);
                break;
        }
        typeComboBox.setSelectedIndex(state.getMove());
        if (typeComboBox.getSelectedIndex() == 3) {
            setMoveButton.setEnabled(true);
        } else {
            setMoveButton.setEnabled(false);
        }
        speedComboBox.setSelectedIndex(state.getSpeed());
        switch (state.getStartType()) {
            case NpcState.AUTOMATIC:
                automaticRadioButton.setSelected(true);
                break;
            case NpcState.BUTTON:
                buttonRadioButton.setSelected(true);
                break;
            case NpcState.CONTACT:
                contactRadioButton.setSelected(true);
                break;
        }
        crossCheckBox.setSelected(state.isCross());
        playerImgPane.repaint();
        int n = 0;
        String[] s = state.getScript().getFunc().split("\n");
        if(!state.getScript().getFunc().equals("")){
            n = s.length;
        }
        eventTM.getDataVector().clear();
        for (int i = 0; i < n; i++) {
            String[] ss = {s[i]};
            eventTM.addRow(ss);
            eventTable.getSelectionModel().setSelectionInterval(i, i);
        }
        String[] sss = {""};
        eventTM.addRow(sss);
        eventTable.getSelectionModel().setSelectionInterval(s.length, s.length);
    }
    private EventManagerDialog emd;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        eventPopupMenu = new javax.swing.JPopupMenu();
        addMenuItem = new javax.swing.JMenuItem();
        insertMenuItem = new javax.swing.JMenuItem();
        removeMenuItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        switchCheckBox = new javax.swing.JCheckBox();
        varCheckBox = new javax.swing.JCheckBox();
        switchComboBox = new javax.swing.JComboBox();
        varComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        upVarTextField = new javax.swing.JTextField();
        varOperationTypeComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        onComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        playerImgPane = new javax.swing.JPanel(){
            public void paint(Graphics g){
                g.setColor(new Color(255,153,153));
                g.fillRect(0, 0, this.getWidth(), this.getHeight());
                if(npcState.getImg()!=null){
                    g.drawImage(npcState.getImg(), this.getWidth()/2-npcState.getImg().getWidth(null)/2,
                        this.getHeight()/2-npcState.getImg().getHeight(null)/2, null);
                }
            }
        }
        ;
        jPanel3 = new javax.swing.JPanel();
        upRadioButton = new javax.swing.JRadioButton();
        downRadioButton = new javax.swing.JRadioButton();
        leftRadioButton = new javax.swing.JRadioButton();
        rightRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();
        speedComboBox = new javax.swing.JComboBox();
        setMoveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        automaticRadioButton = new javax.swing.JRadioButton();
        contactRadioButton = new javax.swing.JRadioButton();
        buttonRadioButton = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        crossCheckBox = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        parallelRadioButton = new javax.swing.JRadioButton();
        serialRadioButton = new javax.swing.JRadioButton();
        jToolBar1 = new javax.swing.JToolBar();
        addScriptButton = new javax.swing.JButton();
        insertScriptButton = new javax.swing.JButton();
        removeScriptButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        eventPopupMenu.setName("eventPopupMenu"); // NOI18N

        addMenuItem.setText("添加脚本");
        addMenuItem.setName("addMenuItem"); // NOI18N
        addMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuItemActionPerformed(evt);
            }
        });
        eventPopupMenu.add(addMenuItem);

        insertMenuItem.setText("插入脚本");
        insertMenuItem.setName("insertMenuItem"); // NOI18N
        insertMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertMenuItemActionPerformed(evt);
            }
        });
        eventPopupMenu.add(insertMenuItem);

        removeMenuItem.setText("删除脚本");
        removeMenuItem.setName("removeMenuItem"); // NOI18N
        removeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMenuItemActionPerformed(evt);
            }
        });
        eventPopupMenu.add(removeMenuItem);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("事件出现条件"));
        jPanel1.setName("jPanel1"); // NOI18N

        switchCheckBox.setText("开关");
        switchCheckBox.setName("switchCheckBox"); // NOI18N
        switchCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchCheckBoxActionPerformed(evt);
            }
        });

        varCheckBox.setText("变量");
        varCheckBox.setName("varCheckBox"); // NOI18N
        varCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varCheckBoxActionPerformed(evt);
            }
        });

        switchComboBox.setEnabled(false);
        switchComboBox.setFocusTraversalPolicyProvider(true);
        switchComboBox.setName("switchComboBox"); // NOI18N
        for(int i =0;i<100;i++){
            switchComboBox.addItem(i);
        }

        varComboBox.setEnabled(false);
        varComboBox.setName("varComboBox"); // NOI18N
        for(int i =0;i<100;i++){
            varComboBox.addItem(i);
        }

        jLabel1.setText("值为");
        jLabel1.setName("jLabel1"); // NOI18N

        upVarTextField.setEnabled(false);
        upVarTextField.setName("upVarTextField"); // NOI18N

        varOperationTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "等于", "大于", "小于", "大于等于", "小于等于", "不等于" }));
        varOperationTypeComboBox.setEnabled(false);
        varOperationTypeComboBox.setName("varOperationTypeComboBox"); // NOI18N

        jLabel3.setText("时");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel2.setText("为");
        jLabel2.setName("jLabel2"); // NOI18N

        onComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ON", "OFF" }));
        onComboBox.setEnabled(false);
        onComboBox.setName("onComboBox"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(switchCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(switchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(varCheckBox)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(varOperationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(upVarTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                            .addComponent(varComboBox, 0, 151, Short.MAX_VALUE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(onComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(switchCheckBox)
                    .addComponent(switchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varCheckBox)
                    .addComponent(varComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upVarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varOperationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("角色图片：");
        jLabel4.setName("jLabel4"); // NOI18N

        playerImgPane.setBackground(new java.awt.Color(255, 153, 153));
        playerImgPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        playerImgPane.setName("playerImgPane"); // NOI18N
        playerImgPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerImgPaneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout playerImgPaneLayout = new javax.swing.GroupLayout(playerImgPane);
        playerImgPane.setLayout(playerImgPaneLayout);
        playerImgPaneLayout.setHorizontalGroup(
            playerImgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );
        playerImgPaneLayout.setVerticalGroup(
            playerImgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("角色面向"));
        jPanel3.setName("jPanel3"); // NOI18N

        buttonGroup1.add(upRadioButton);
        upRadioButton.setText("上");
        upRadioButton.setName("upRadioButton"); // NOI18N
        upRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(downRadioButton);
        downRadioButton.setSelected(true);
        downRadioButton.setText("下");
        downRadioButton.setName("downRadioButton"); // NOI18N
        downRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(leftRadioButton);
        leftRadioButton.setText("左");
        leftRadioButton.setName("leftRadioButton"); // NOI18N
        leftRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(rightRadioButton);
        rightRadioButton.setText("右");
        rightRadioButton.setName("rightRadioButton"); // NOI18N
        rightRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(upRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(leftRadioButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(downRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(rightRadioButton)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upRadioButton)
                    .addComponent(leftRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightRadioButton)
                    .addComponent(downRadioButton))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("移动规则"));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel5.setText("类型:");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("速度:");
        jLabel6.setName("jLabel6"); // NOI18N

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "固定", "随机", "接近", "自定义" }));
        typeComboBox.setName("typeComboBox"); // NOI18N
        typeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeComboBoxItemStateChanged(evt);
            }
        });

        speedComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "快", "中", "慢" }));
        speedComboBox.setName("speedComboBox"); // NOI18N
        speedComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                speedComboBoxItemStateChanged(evt);
            }
        });

        setMoveButton.setText("设置移动路线");
        setMoveButton.setEnabled(false);
        setMoveButton.setName("setMoveButton"); // NOI18N
        setMoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(speedComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(setMoveButton)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setMoveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(speedComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        eventTable.setModel(eventTM);
        eventTable.setComponentPopupMenu(eventPopupMenu);
        eventTable.setName("eventTable"); // NOI18N
        eventTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        eventTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventTableMouseClicked(evt);
            }
        });
        eventTable.getModel().addTableModelListener(this);
        jScrollPane1.setViewportView(eventTable);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("触发条件"));
        jPanel5.setName("jPanel5"); // NOI18N

        buttonGroup2.add(automaticRadioButton);
        automaticRadioButton.setSelected(true);
        automaticRadioButton.setText("自动");
        automaticRadioButton.setName("automaticRadioButton"); // NOI18N
        automaticRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automaticRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(contactRadioButton);
        contactRadioButton.setText("接触");
        contactRadioButton.setName("contactRadioButton"); // NOI18N
        contactRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(buttonRadioButton);
        buttonRadioButton.setText("按键");
        buttonRadioButton.setName("buttonRadioButton"); // NOI18N
        buttonRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(automaticRadioButton)
                .addGap(18, 18, 18)
                .addComponent(contactRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(buttonRadioButton)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(automaticRadioButton)
                    .addComponent(buttonRadioButton)
                    .addComponent(contactRadioButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("选项"));
        jPanel6.setName("jPanel6"); // NOI18N

        crossCheckBox.setText("允许穿透");
        crossCheckBox.setName("crossCheckBox"); // NOI18N
        crossCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crossCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crossCheckBox)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(crossCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("执行策略"));
        jPanel4.setName("jPanel4"); // NOI18N

        buttonGroup3.add(parallelRadioButton);
        parallelRadioButton.setText("并行");
        parallelRadioButton.setName("parallelRadioButton"); // NOI18N

        buttonGroup3.add(serialRadioButton);
        serialRadioButton.setSelected(true);
        serialRadioButton.setText("串行");
        serialRadioButton.setName("serialRadioButton"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parallelRadioButton)
                .addGap(18, 18, 18)
                .addComponent(serialRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parallelRadioButton)
                    .addComponent(serialRadioButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        addScriptButton.setText("添加脚本");
        addScriptButton.setFocusable(false);
        addScriptButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addScriptButton.setName("addScriptButton"); // NOI18N
        addScriptButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addScriptButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(addScriptButton);

        insertScriptButton.setText("插入脚本");
        insertScriptButton.setFocusable(false);
        insertScriptButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        insertScriptButton.setName("insertScriptButton"); // NOI18N
        insertScriptButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        insertScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertScriptButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(insertScriptButton);

        removeScriptButton.setText("删除脚本");
        removeScriptButton.setFocusable(false);
        removeScriptButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeScriptButton.setName("removeScriptButton"); // NOI18N
        removeScriptButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeScriptButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(removeScriptButton);

        editButton.setText("手动编辑");
        editButton.setFocusable(false);
        editButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editButton.setName("editButton"); // NOI18N
        editButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(editButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(playerImgPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerImgPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void switchCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchCheckBoxActionPerformed
        // TODO add your handling code here:
        if (switchCheckBox.isSelected()) {
            switchComboBox.setEnabled(true);
            onComboBox.setEnabled(true);
        } else {
            switchComboBox.setEnabled(false);
            onComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_switchCheckBoxActionPerformed

    private void varCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varCheckBoxActionPerformed
        // TODO add your handling code here:
        if (varCheckBox.isSelected()) {
            varComboBox.setEnabled(true);
            upVarTextField.setEnabled(true);
            varOperationTypeComboBox.setEnabled(true);
        } else {
            varComboBox.setEnabled(false);
            upVarTextField.setEnabled(false);
            varOperationTypeComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_varCheckBoxActionPerformed

    private void playerImgPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerImgPaneMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 2) {
            NpcMoveImageDialog cid = new NpcMoveImageDialog(this, true);
            cid.setVisible(true);
        }
    }//GEN-LAST:event_playerImgPaneMouseClicked

    private void upRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upRadioButtonActionPerformed
        // TODO add your handling code here:
        npcState.setFace(NpcState.UP);
}//GEN-LAST:event_upRadioButtonActionPerformed

    private void downRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downRadioButtonActionPerformed
        // TODO add your handling code here:
        npcState.setFace(NpcState.DOWN);
}//GEN-LAST:event_downRadioButtonActionPerformed

    private void leftRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftRadioButtonActionPerformed
        // TODO add your handling code here:
        npcState.setFace(NpcState.LEFT);
}//GEN-LAST:event_leftRadioButtonActionPerformed

    private void rightRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightRadioButtonActionPerformed
        // TODO add your handling code here:
        npcState.setFace(NpcState.RIGHT);
}//GEN-LAST:event_rightRadioButtonActionPerformed
    private ScriptDialog sd;
    private void eventTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 2) {
            if (sd == null) {
                sd = new ScriptDialog(this, true);
            }
            sd.setVisible(true);
        }
}//GEN-LAST:event_eventTableMouseClicked

    private void automaticRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automaticRadioButtonActionPerformed
        // TODO add your handling code here:
        npcState.setStartType(NpcState.AUTOMATIC);
}//GEN-LAST:event_automaticRadioButtonActionPerformed

    private void contactRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactRadioButtonActionPerformed
        // TODO add your handling code here:

        npcState.setStartType(NpcState.CONTACT);
}//GEN-LAST:event_contactRadioButtonActionPerformed

    private void buttonRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRadioButtonActionPerformed
        // TODO add your handling code here:
        npcState.setStartType(NpcState.BUTTON);
}//GEN-LAST:event_buttonRadioButtonActionPerformed

    private void crossCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crossCheckBoxActionPerformed
        // TODO add your handling code here:
        npcState.setCross(crossCheckBox.isSelected());
}//GEN-LAST:event_crossCheckBoxActionPerformed

    private void speedComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_speedComboBoxItemStateChanged
        // TODO add your handling code here:
        npcState.setSpeed(Byte.parseByte("" + speedComboBox.getSelectedIndex()));
    }//GEN-LAST:event_speedComboBoxItemStateChanged

    private void typeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeComboBoxItemStateChanged
        // TODO add your handling code here:
        npcState.setMove(Byte.parseByte("" + typeComboBox.getSelectedIndex()));
        if (typeComboBox.getSelectedIndex() == 3) {
            setMoveButton.setEnabled(true);
        } else {
            setMoveButton.setEnabled(false);
        }
    }//GEN-LAST:event_typeComboBoxItemStateChanged

    private void setMoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMoveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setMoveButtonActionPerformed

    private void insertMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertMenuItemActionPerformed
        // TODO add your handling code here:
        if (sd == null) {
            sd = new ScriptDialog(this, true);
        }
        sd.setVisible(true);
    }//GEN-LAST:event_insertMenuItemActionPerformed

    private void removeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMenuItemActionPerformed
        // TODO add your handling code here:
        removeScript();
    }//GEN-LAST:event_removeMenuItemActionPerformed

    private void insertScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertScriptButtonActionPerformed
        // TODO add your handling code here:
        if (sd == null) {
            sd = new ScriptDialog(this, true);
        }
        sd.setVisible(true);
    }//GEN-LAST:event_insertScriptButtonActionPerformed

    private void removeScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeScriptButtonActionPerformed
        // TODO add your handling code here:
        removeScript();
    }//GEN-LAST:event_removeScriptButtonActionPerformed
    private void removeScript() {
        if (eventTable.getSelectedRow() == -1) {
            return;
        }
        eventTM.removeRow(eventTable.getSelectedRow());
        if (eventTM.getRowCount() == 0) {
            addScript();
        }
        eventTable.getSelectionModel().clearSelection();
    }
    private void addScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addScriptButtonActionPerformed
        // TODO add your handling code here:
        addScript();
    }//GEN-LAST:event_addScriptButtonActionPerformed
    private void addScript() {
        String[] s = {""};
        eventTM.addRow(s);
        eventTable.getSelectionModel().setSelectionInterval(eventTM.getRowCount() - 1, eventTM.getRowCount() - 1);
    }
    private void addMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMenuItemActionPerformed
        // TODO add your handling code here:
        addScript();
    }//GEN-LAST:event_addMenuItemActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        ScriptManagerDialog smd = new ScriptManagerDialog(this, true);
        smd.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addMenuItem;
    private javax.swing.JButton addScriptButton;
    private javax.swing.JRadioButton automaticRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton buttonRadioButton;
    private javax.swing.JRadioButton contactRadioButton;
    private javax.swing.JCheckBox crossCheckBox;
    private javax.swing.JRadioButton downRadioButton;
    private javax.swing.JButton editButton;
    private javax.swing.JPopupMenu eventPopupMenu;
    public javax.swing.JTable eventTable;
    private javax.swing.JMenuItem insertMenuItem;
    private javax.swing.JButton insertScriptButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButton leftRadioButton;
    private javax.swing.JComboBox onComboBox;
    private javax.swing.JRadioButton parallelRadioButton;
    public javax.swing.JPanel playerImgPane;
    private javax.swing.JMenuItem removeMenuItem;
    private javax.swing.JButton removeScriptButton;
    private javax.swing.JRadioButton rightRadioButton;
    private javax.swing.JRadioButton serialRadioButton;
    private javax.swing.JButton setMoveButton;
    private javax.swing.JComboBox speedComboBox;
    private javax.swing.JCheckBox switchCheckBox;
    private javax.swing.JComboBox switchComboBox;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JRadioButton upRadioButton;
    private javax.swing.JTextField upVarTextField;
    private javax.swing.JCheckBox varCheckBox;
    private javax.swing.JComboBox varComboBox;
    private javax.swing.JComboBox varOperationTypeComboBox;
    // End of variables declaration//GEN-END:variables

    public void tableChanged(TableModelEvent e) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < eventTM.getRowCount(); i++) {
            sb.append(eventTM.getValueAt(i, 0)).append("\n");
        }
        npcState.getScript().setFunc(sb.toString());
    }
}
