/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditMapDialog.java
 *
 * Created on 2011-3-27, 15:05:35
 */
package com.soyomaker.dialog;

import com.soyomaker.AppData;
import com.soyomaker.project.Project;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class EditMapDialog extends javax.swing.JDialog {

    /** Creates new form EditMapDialog
     * @param parent
     * @param modal  
     */
    public EditMapDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initialize();
    }

    private void initialize() {
        setLocationRelativeTo(null);
        init();
    }
    private AppData data = AppData.getInstance();

    private void init() {
        File musicDir = new File(AppData.getInstance().getCurProject().getPath() + File.separatorChar + "audio" + File.separatorChar + "music");
        if (!musicDir.exists()) {
            musicDir.mkdirs();
        }
        File[] files = musicDir.listFiles();
        musicComboBox.addItem("");
        for (int i = 0, n = files.length; i < n; i++) {
            musicComboBox.addItem(files[i].getName());
        }
        battleMusicComboBox.addItem("");
        for (int i = 0, n = files.length; i < n; i++) {
            battleMusicComboBox.addItem(files[i].getName());
        }
        File bgDir = new File(AppData.getInstance().getCurProject().getPath() + File.separatorChar + "image" + File.separatorChar + "battle");
        if (!bgDir.exists()) {
            bgDir.mkdirs();
        }
        files = bgDir.listFiles();
        battleBackgroundComboBox.addItem("");
        for (int i = 0, n = files.length; i < n; i++) {
            battleBackgroundComboBox.addItem(files[i].getName());
        }
        musicComboBox.setSelectedItem(data.getCurrentMap().getMusicName());
        battleMusicComboBox.setSelectedItem(data.getCurrentMap().getBattleMusicName());
        battleBackgroundComboBox.setSelectedItem(data.getCurrentMap().getBattleBackground());
        mapNameTextField.setText(data.getCurrentMap().getName());
        mapWidthTextField.setText("" + data.getCurrentMap().getWidth());
        mapHeightTextField.setText("" + data.getCurrentMap().getHeight());
        tileWidthTextField.setText("" + data.getCurrentMap().getTileWidth());
        tileHeightTextField.setText("" + data.getCurrentMap().getTileHeight());
        mapSizeLabel.setText("" + data.getCurrentMap().getWidth() * data.getCurrentMap().getTileWidth() + "x" + data.getCurrentMap().getHeight() * data.getCurrentMap().getTileHeight());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mapNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mapWidthTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mapHeightTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        musicComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tileWidthTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tileHeightTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mapSizeLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        battleMusicComboBox = new javax.swing.JComboBox();
        battleBackgroundComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(EditMapDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setResizable(false);

        jPanel1.setName("jPanel1"); // NOI18N

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancleButton.setText("取消");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("名称");
        jLabel1.setName("jLabel1"); // NOI18N

        mapNameTextField.setName("mapNameTextField"); // NOI18N

        jLabel2.setText("Map宽");
        jLabel2.setName("jLabel2"); // NOI18N

        mapWidthTextField.setName("mapWidthTextField"); // NOI18N

        jLabel3.setText("Map高");
        jLabel3.setName("jLabel3"); // NOI18N

        mapHeightTextField.setName("mapHeightTextField"); // NOI18N

        jLabel4.setText("背景音乐");
        jLabel4.setName("jLabel4"); // NOI18N

        musicComboBox.setName("musicComboBox"); // NOI18N

        jLabel5.setText("Tile宽");
        jLabel5.setName("jLabel5"); // NOI18N

        tileWidthTextField.setEnabled(false);
        tileWidthTextField.setName("tileWidthTextField"); // NOI18N

        jLabel6.setText("Tile高");
        jLabel6.setName("jLabel6"); // NOI18N

        tileHeightTextField.setEnabled(false);
        tileHeightTextField.setName("tileHeightTextField"); // NOI18N

        jLabel7.setText("地图像素大小：");
        jLabel7.setName("jLabel7"); // NOI18N

        mapSizeLabel.setText("无");
        mapSizeLabel.setName("mapSizeLabel"); // NOI18N

        jLabel8.setText("战斗音乐");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText("战斗背景");
        jLabel9.setName("jLabel9"); // NOI18N

        battleMusicComboBox.setName("battleMusicComboBox"); // NOI18N

        battleBackgroundComboBox.setName("battleBackgroundComboBox"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancleButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mapWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(mapHeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mapNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(musicComboBox, 0, 243, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tileWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(tileHeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(mapSizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(battleMusicComboBox, 0, 240, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(battleBackgroundComboBox, 0, 240, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mapNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mapWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mapHeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(musicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tileWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tileHeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(battleMusicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(battleBackgroundComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(mapSizeLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancleButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        if (mapNameTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "地图名不能为空！");
            return;
        }
        String mapName = mapNameTextField.getText();
        if (mapWidthTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "地图宽度不能为空！");
            return;
        }
        int mapW = Integer.parseInt(mapWidthTextField.getText());

        if (mapHeightTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this,
                    "地图高度不能为空！");
            return;
        }
        int mapH = Integer.parseInt(mapHeightTextField.getText());

        String musicName = (String) musicComboBox.getSelectedItem() == null ? "" : (String) musicComboBox.getSelectedItem();
        String battleMusicName = (String) battleMusicComboBox.getSelectedItem() == null ? "" : (String) battleMusicComboBox.getSelectedItem();
        String battleBackgroundName = (String) battleBackgroundComboBox.getSelectedItem() == null ? "" : (String) battleBackgroundComboBox.getSelectedItem();
        data.getCurrentMap().setName(mapName);
        data.getCurrentMap().setBattleMusicName(battleMusicName);
        data.getCurrentMap().setBattleBackground(battleBackgroundName);
        data.getCurrentMap().resize(mapW, mapH, 0, 0);
        data.getCurrentMap().setMusicName(musicName);
        data.getMainFrame().mapScrollPane.setViewportView(data.getCurrentMap().getMapRender());
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancleButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox battleBackgroundComboBox;
    private javax.swing.JComboBox battleMusicComboBox;
    private javax.swing.JButton cancleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mapHeightTextField;
    private javax.swing.JTextField mapNameTextField;
    private javax.swing.JLabel mapSizeLabel;
    private javax.swing.JTextField mapWidthTextField;
    private javax.swing.JComboBox musicComboBox;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField tileHeightTextField;
    private javax.swing.JTextField tileWidthTextField;
    // End of variables declaration//GEN-END:variables
}
