/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScriptDialog.java
 *
 * Created on 2011-3-27, 13:57:50
 */
package com.soyomaker.dialog;

import com.soyomaker.dialog.event.dataprocess.ChangeEnemyModelDialog;
import com.soyomaker.dialog.event.dataprocess.ChangeEnemyPowerDialog;
import com.soyomaker.dialog.event.dataprocess.ChangeEquipDialog;
import com.soyomaker.dialog.event.dataprocess.ChangePlayerModelDialog;
import com.soyomaker.dialog.event.dataprocess.ChangePlayerNameDialog;
import com.soyomaker.dialog.event.gameperformance.BattleDialog;
import com.soyomaker.dialog.event.dataprocess.EquipDialog;
import com.soyomaker.dialog.event.gameperformance.FaceDialog;
import com.soyomaker.dialog.event.dataprocess.ItemDialog;
import com.soyomaker.dialog.event.gameperformance.OpenShopDialog;
import com.soyomaker.dialog.event.gameperformance.MapDialog;
import com.soyomaker.dialog.event.gameperformance.ShowMessageDialog;
import com.soyomaker.dialog.event.dataprocess.MoneyDialog;
import com.soyomaker.dialog.event.gameperformance.MoveDialog;
import com.soyomaker.dialog.event.gameperformance.PlayMusicDialog;
import com.soyomaker.dialog.event.dataprocess.PowerDialog;
import com.soyomaker.dialog.event.dataprocess.SkillDialog;
import com.soyomaker.dialog.event.dataprocess.SwitchDialog;
import com.soyomaker.dialog.event.dataprocess.VarDialog;
import com.soyomaker.dialog.event.gameperformance.ChangeImageARGBDialog;
import com.soyomaker.dialog.event.gameperformance.ChangeScreenARGBDialog;
import com.soyomaker.dialog.event.gameperformance.ChangeSkinDialog;
import com.soyomaker.dialog.event.gameperformance.MoveImageDialog;
import com.soyomaker.dialog.event.gameperformance.RemoveImageDialog;
import com.soyomaker.dialog.event.gameperformance.RotateImageDialog;
import com.soyomaker.dialog.event.gameperformance.ScreenShockDialog;
import com.soyomaker.dialog.event.gameperformance.ShowAnimationDialog;
import com.soyomaker.dialog.event.gameperformance.ShowChooseDialog;
import com.soyomaker.dialog.event.gameperformance.ShowCountDownDialog;
import com.soyomaker.dialog.event.gameperformance.ShowImageDialog;
import com.soyomaker.dialog.event.gameperformance.ShowInputDialog;
import com.soyomaker.dialog.event.gameperformance.StopMusicDialog;
import com.soyomaker.dialog.event.processcontrol.IfDialog;
import com.soyomaker.dialog.event.processcontrol.PublicEventDialog;
import com.soyomaker.dialog.event.processcontrol.WaitDialog;
import com.soyomaker.model.map.Command;
import com.soyomaker.model.map.Script;
import com.soyomaker.widget.NpcStatePane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author Administrator
 */
public class ScriptDialog extends javax.swing.JDialog {

    /** Creates new form ScriptDialog
     * @param parent 
     * @param modal 
     */
    public ScriptDialog(NpcStatePane parent, boolean modal) {
        setModal(modal);
        initComponents();
        initialize();
        npcStatePane = parent;
    }
    private NpcStatePane npcStatePane = null;
    private Script mScript = null;

    /**
     *
     * @param script
     */
    public void setScript(Script script) {
        mScript = script;
    }

    private void initialize() {
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scriptTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        showChooseButton = new javax.swing.JButton();
        showInputButton = new javax.swing.JButton();
        showMessageButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        switchButton = new javax.swing.JButton();
        varButton = new javax.swing.JButton();
        showCountDownButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        itemButton = new javax.swing.JButton();
        moneyButton = new javax.swing.JButton();
        equipButton = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        changeEquipButton = new javax.swing.JButton();
        changeModalButton = new javax.swing.JButton();
        changeNameButton = new javax.swing.JButton();
        powButton = new javax.swing.JButton();
        skillButton = new javax.swing.JButton();
        faceButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        mapButton = new javax.swing.JButton();
        moveButton = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        showAniButton = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        shakeScreenButton = new javax.swing.JButton();
        changeScreenColorButton = new javax.swing.JButton();
        changeSkinButton = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        changeImageARGBButton = new javax.swing.JButton();
        showImageButton = new javax.swing.JButton();
        removeImageButton = new javax.swing.JButton();
        rotateImageButton = new javax.swing.JButton();
        moveImageButton = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        stopMusicButton = new javax.swing.JButton();
        playMusicButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        battleButton = new javax.swing.JButton();
        openShopButton = new javax.swing.JButton();
        endBattleButton = new javax.swing.JButton();
        gameSaveButton = new javax.swing.JButton();
        systemMenuButton = new javax.swing.JButton();
        mainMenuButton = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        enemyTransButton = new javax.swing.JButton();
        changeEnemyPowerButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        ifButton = new javax.swing.JButton();
        whileButton = new javax.swing.JButton();
        breakButton = new javax.swing.JButton();
        exitScriptButton = new javax.swing.JButton();
        publicEventButton = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        waitButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ScriptDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setResizable(false);

        jPanel1.setName("jPanel1"); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("消息"));
        jPanel7.setName("jPanel7"); // NOI18N

        showChooseButton.setText("显示选项框");
        showChooseButton.setName("showChooseButton"); // NOI18N
        showChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showChooseButtonActionPerformed(evt);
            }
        });

        showInputButton.setText("显示输入框");
        showInputButton.setName("showInputButton"); // NOI18N
        showInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInputButtonActionPerformed(evt);
            }
        });

        showMessageButton.setText("显示对话框");
        showMessageButton.setName("showMessageButton"); // NOI18N
        showMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMessageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showChooseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(showInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(showMessageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {showChooseButton, showInputButton, showMessageButton});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showChooseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showInputButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showMessageButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {showChooseButton, showInputButton, showMessageButton});

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("游戏进程"));
        jPanel8.setName("jPanel8"); // NOI18N

        switchButton.setText("开关操作");
        switchButton.setName("switchButton"); // NOI18N
        switchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchButtonActionPerformed(evt);
            }
        });

        varButton.setText("变量操作");
        varButton.setName("varButton"); // NOI18N
        varButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varButtonActionPerformed(evt);
            }
        });

        showCountDownButton.setText("计时器操作");
        showCountDownButton.setName("showCountDownButton"); // NOI18N
        showCountDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCountDownButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(switchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showCountDownButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {switchButton, varButton});

        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(switchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(varButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showCountDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {switchButton, varButton});

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("队伍"));
        jPanel10.setName("jPanel10"); // NOI18N

        itemButton.setText("增减物品");
        itemButton.setName("itemButton"); // NOI18N
        itemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemButtonActionPerformed(evt);
            }
        });

        moneyButton.setText("增减金钱");
        moneyButton.setName("moneyButton"); // NOI18N
        moneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyButtonActionPerformed(evt);
            }
        });

        equipButton.setText("增减装备");
        equipButton.setName("equipButton"); // NOI18N
        equipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moneyButton)
                    .addComponent(equipButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(itemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {equipButton, itemButton, moneyButton});

        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moneyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(equipButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {equipButton, itemButton, moneyButton});

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("角色"));
        jPanel11.setName("jPanel11"); // NOI18N

        changeEquipButton.setText("切换装备");
        changeEquipButton.setName("changeEquipButton"); // NOI18N
        changeEquipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeEquipButtonActionPerformed(evt);
            }
        });

        changeModalButton.setText("角色变身");
        changeModalButton.setName("changeModalButton"); // NOI18N
        changeModalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeModalButtonActionPerformed(evt);
            }
        });

        changeNameButton.setText("修改角色名称");
        changeNameButton.setName("changeNameButton"); // NOI18N
        changeNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNameButtonActionPerformed(evt);
            }
        });

        powButton.setText("增减属性");
        powButton.setName("powButton"); // NOI18N
        powButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powButtonActionPerformed(evt);
            }
        });

        skillButton.setText("增减技能");
        skillButton.setName("skillButton"); // NOI18N
        skillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skillButtonActionPerformed(evt);
            }
        });

        faceButton.setText("改变面向");
        faceButton.setName("faceButton"); // NOI18N
        faceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(skillButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(changeNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(changeEquipButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(changeModalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(faceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(powButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel11Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {changeEquipButton, changeModalButton, changeNameButton, faceButton, powButton, skillButton});

        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(powButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(skillButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeNameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeEquipButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeModalButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(faceButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {changeEquipButton, changeModalButton, changeNameButton, powButton, skillButton});

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel10, jPanel11, jPanel7, jPanel8});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        scriptTabbedPane.addTab("  1  ", jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N

        jPanel5.setName("jPanel5"); // NOI18N

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("移动"));
        jPanel12.setName("jPanel12"); // NOI18N

        mapButton.setText("切换地图");
        mapButton.setName("mapButton"); // NOI18N
        mapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapButtonActionPerformed(evt);
            }
        });

        moveButton.setText("设置移动");
        moveButton.setName("moveButton"); // NOI18N
        moveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mapButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(moveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel12Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {mapButton, moveButton});

        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mapButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moveButton)
                .addContainerGap())
        );

        jPanel12Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {mapButton, moveButton});

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("动画"));
        jPanel13.setName("jPanel13"); // NOI18N

        showAniButton.setText("显示动画");
        showAniButton.setName("showAniButton"); // NOI18N
        showAniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAniButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showAniButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showAniButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("画面"));
        jPanel14.setName("jPanel14"); // NOI18N

        shakeScreenButton.setText("画面震动");
        shakeScreenButton.setName("shakeScreenButton"); // NOI18N
        shakeScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shakeScreenButtonActionPerformed(evt);
            }
        });

        changeScreenColorButton.setText("更改画面色调");
        changeScreenColorButton.setName("changeScreenColorButton"); // NOI18N
        changeScreenColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeScreenColorButtonActionPerformed(evt);
            }
        });

        changeSkinButton.setText("更换皮肤");
        changeSkinButton.setName("changeSkinButton"); // NOI18N
        changeSkinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSkinButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeScreenColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(shakeScreenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(changeSkinButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel14Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {changeScreenColorButton, changeSkinButton, shakeScreenButton});

        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changeScreenColorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shakeScreenButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeSkinButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {changeScreenColorButton, changeSkinButton, shakeScreenButton});

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("图片"));
        jPanel16.setName("jPanel16"); // NOI18N

        changeImageARGBButton.setText("更改图片色调");
        changeImageARGBButton.setName("changeImageARGBButton"); // NOI18N
        changeImageARGBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeImageARGBButtonActionPerformed(evt);
            }
        });

        showImageButton.setText("显示图片");
        showImageButton.setName("showImageButton"); // NOI18N
        showImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showImageButtonActionPerformed(evt);
            }
        });

        removeImageButton.setText("移除图片");
        removeImageButton.setName("removeImageButton"); // NOI18N
        removeImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeImageButtonActionPerformed(evt);
            }
        });

        rotateImageButton.setText("旋转图片");
        rotateImageButton.setName("rotateImageButton"); // NOI18N
        rotateImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateImageButtonActionPerformed(evt);
            }
        });

        moveImageButton.setText("移动图片");
        moveImageButton.setName("moveImageButton"); // NOI18N
        moveImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveImageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(rotateImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(removeImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(changeImageARGBButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(moveImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel16Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {changeImageARGBButton, moveImageButton, removeImageButton, rotateImageButton, showImageButton});

        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showImageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rotateImageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeImageARGBButton)
                .addGap(10, 10, 10)
                .addComponent(removeImageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moveImageButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {changeImageARGBButton, moveImageButton, removeImageButton, rotateImageButton, showImageButton});

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("音乐"));
        jPanel17.setName("jPanel17"); // NOI18N

        stopMusicButton.setText("停止音乐");
        stopMusicButton.setName("stopMusicButton"); // NOI18N
        stopMusicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopMusicButtonActionPerformed(evt);
            }
        });

        playMusicButton.setText("播放音乐");
        playMusicButton.setName("playMusicButton"); // NOI18N
        playMusicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playMusicButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playMusicButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(stopMusicButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel17Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {playMusicButton, stopMusicButton});

        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playMusicButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stopMusicButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel17Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {playMusicButton, stopMusicButton});

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel12, jPanel13, jPanel14, jPanel16, jPanel17});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );

        scriptTabbedPane.addTab("  2  ", jPanel2);

        jPanel3.setName("jPanel3"); // NOI18N

        jPanel6.setName("jPanel6"); // NOI18N

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("场景控制"));
        jPanel18.setName("jPanel18"); // NOI18N

        battleButton.setText("开启战斗");
        battleButton.setName("battleButton"); // NOI18N
        battleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battleButtonActionPerformed(evt);
            }
        });

        openShopButton.setText("开启商店");
        openShopButton.setName("openShopButton"); // NOI18N
        openShopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openShopButtonActionPerformed(evt);
            }
        });

        endBattleButton.setText("结束战斗");
        endBattleButton.setName("endBattleButton"); // NOI18N
        endBattleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endBattleButtonActionPerformed(evt);
            }
        });

        gameSaveButton.setText("打开存档菜单");
        gameSaveButton.setName("gameSaveButton"); // NOI18N
        gameSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameSaveButtonActionPerformed(evt);
            }
        });

        systemMenuButton.setText("打开系统菜单");
        systemMenuButton.setName("systemMenuButton"); // NOI18N
        systemMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemMenuButtonActionPerformed(evt);
            }
        });

        mainMenuButton.setText("回主菜单");
        mainMenuButton.setName("mainMenuButton"); // NOI18N
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(battleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(openShopButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(endBattleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(systemMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel18Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {battleButton, endBattleButton, gameSaveButton, mainMenuButton, openShopButton, systemMenuButton});

        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(battleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(openShopButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(endBattleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gameSaveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(systemMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainMenuButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {battleButton, endBattleButton, gameSaveButton, mainMenuButton, openShopButton, systemMenuButton});

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("战斗"));
        jPanel19.setName("jPanel19"); // NOI18N

        enemyTransButton.setText("敌人变身");
        enemyTransButton.setName("enemyTransButton"); // NOI18N
        enemyTransButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enemyTransButtonActionPerformed(evt);
            }
        });

        changeEnemyPowerButton.setText("增减敌人属性");
        changeEnemyPowerButton.setName("changeEnemyPowerButton"); // NOI18N
        changeEnemyPowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeEnemyPowerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enemyTransButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(changeEnemyPowerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel19Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {changeEnemyPowerButton, enemyTransButton});

        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enemyTransButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeEnemyPowerButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {changeEnemyPowerButton, enemyTransButton});

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("流程控制"));
        jPanel9.setName("jPanel9"); // NOI18N

        ifButton.setText("条件分支");
        ifButton.setName("ifButton"); // NOI18N
        ifButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifButtonActionPerformed(evt);
            }
        });

        whileButton.setText("循环");
        whileButton.setName("whileButton"); // NOI18N
        whileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whileButtonActionPerformed(evt);
            }
        });

        breakButton.setText("中断循环");
        breakButton.setName("breakButton"); // NOI18N
        breakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakButtonActionPerformed(evt);
            }
        });

        exitScriptButton.setText("中断事件处理");
        exitScriptButton.setName("exitScriptButton"); // NOI18N
        exitScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitScriptButtonActionPerformed(evt);
            }
        });

        publicEventButton.setText("公共事件");
        publicEventButton.setName("publicEventButton"); // NOI18N
        publicEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicEventButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ifButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(breakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitScriptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(publicEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {breakButton, exitScriptButton, ifButton, publicEventButton, whileButton});

        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ifButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(whileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(breakButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitScriptButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(publicEventButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {breakButton, exitScriptButton, ifButton, publicEventButton, whileButton});

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("等待"));
        jPanel15.setName("jPanel15"); // NOI18N

        waitButton.setText("强制等待");
        waitButton.setName("waitButton"); // NOI18N
        waitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );

        scriptTabbedPane.addTab("  3  ", jPanel3);

        cancleButton.setText("关闭");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scriptTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(cancleButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scriptTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancleButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancleButtonActionPerformed

    private void ifButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifButtonActionPerformed
        // TODO add your handling code here:
        IfDialog md = new IfDialog(this, true, Command.IF);
        md.setVisible(true);

        addCommand(md.getCommand());
    }//GEN-LAST:event_ifButtonActionPerformed

    private void whileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whileButtonActionPerformed
        // TODO add your handling code here:
        Command c3 = new Command();
        c3.setScriptId(Command.WHILE);

        addCommand(c3);
    }//GEN-LAST:event_whileButtonActionPerformed

    private void exitScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitScriptButtonActionPerformed
        // TODO add your handling code here:
        Command c1 = new Command();
        c1.setScriptId(Command.EXIT_SCRIPT);

        addCommand(c1);
    }//GEN-LAST:event_exitScriptButtonActionPerformed

    private void breakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakButtonActionPerformed
        // TODO add your handling code here:
        Command c1 = new Command();
        c1.setScriptId(Command.BREAK);

        addCommand(c1);
    }//GEN-LAST:event_breakButtonActionPerformed

    private void addCommand(Command c) {
        if (c == null) {
            return;
        }
        DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(c);
        Command c2 = new Command();
        c2.setScriptId(Command.INVALID);
        DefaultMutableTreeNode newNode2 = new DefaultMutableTreeNode(c2);
        if (c.getScriptId() == Command.IF || c.getScriptId() == Command.WHILE) {
            c.addCommand(c2);
            newNode.add(newNode2);
        }
        DefaultMutableTreeNode selectedNode = npcStatePane.commandTree.getSelectNode();
        if (selectedNode == null) {
            ((DefaultMutableTreeNode) npcStatePane.commandTree.getModel().getRoot()).add(newNode);
            ((DefaultTreeModel) npcStatePane.commandTree.getModel()).reload((DefaultMutableTreeNode) npcStatePane.commandTree.getModel().getRoot());
            mScript.addCommand(c);
        } else {
            DefaultMutableTreeNode parentNode = (DefaultMutableTreeNode) selectedNode.getParent();
            if (parentNode == null) {
                ((DefaultMutableTreeNode) npcStatePane.commandTree.getModel().getRoot()).add(newNode);
                ((DefaultTreeModel) npcStatePane.commandTree.getModel()).reload((DefaultMutableTreeNode) npcStatePane.commandTree.getModel().getRoot());
                mScript.addCommand(c);
            } else if (parentNode.getUserObject() instanceof Command
                    && (((Command) parentNode.getUserObject()).getScriptId() == Command.IF || ((Command) parentNode.getUserObject()).getScriptId() == Command.WHILE)) {
                int index = parentNode.getIndex(selectedNode);
                parentNode.insert(newNode, index + 1);
                ((DefaultTreeModel) npcStatePane.commandTree.getModel()).reload(npcStatePane.commandTree.getSelectNode());
                ((Command) parentNode.getUserObject()).addCommand(index + 1, c);
            } else {
                int index = parentNode.getIndex(selectedNode);
                ((DefaultMutableTreeNode) npcStatePane.commandTree.getModel().getRoot()).insert(newNode, index + 1);
                ((DefaultTreeModel) npcStatePane.commandTree.getModel()).reload((DefaultMutableTreeNode) npcStatePane.commandTree.getModel().getRoot());
                mScript.addCommand(index + 1, c);
            }
        }
        npcStatePane.commandTree.expandPath(npcStatePane.commandTree.getSelectionPath());
        if (c.getScriptId() == Command.IF || c.getScriptId() == Command.WHILE) {
            npcStatePane.commandTree.setSelectionPath(new TreePath(((DefaultTreeModel) npcStatePane.commandTree.getModel()).getPathToRoot(newNode2)));
        } else {
            npcStatePane.commandTree.setSelectionPath(new TreePath(((DefaultTreeModel) npcStatePane.commandTree.getModel()).getPathToRoot(newNode)));
        }
        //设置维持当前的选择路径
        npcStatePane.commandTree.setExpandsSelectedPaths(true);
        dispose();
    }
    private void mapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapButtonActionPerformed
        // TODO add your handling code here:
        MapDialog md = new MapDialog(this, true, Command.CHANGE_MAP);
        md.setVisible(true);
        addCommand(md.getCommand());
    }//GEN-LAST:event_mapButtonActionPerformed

    private void moveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveButtonActionPerformed
        // TODO add your handling code here:
        MoveDialog md = new MoveDialog(this, true, Command.MOVE);
        md.setVisible(true);
        addCommand(md.getCommand());
    }//GEN-LAST:event_moveButtonActionPerformed

    private void showMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMessageButtonActionPerformed
        // TODO add your handling code here:
        ShowMessageDialog md = new ShowMessageDialog(this, true, Command.SHOW_MESSAGE);
        md.setVisible(true);
        addCommand(md.getCommand());
    }//GEN-LAST:event_showMessageButtonActionPerformed

    private void playMusicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playMusicButtonActionPerformed
        // TODO add your handling code here:
        PlayMusicDialog dialog = new PlayMusicDialog(this, true, Command.PLAY_MUSIC);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_playMusicButtonActionPerformed

    private void openShopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openShopButtonActionPerformed
        // TODO add your handling code here:
        OpenShopDialog dialog = new OpenShopDialog(this, true, Command.OPEN_SHOP);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_openShopButtonActionPerformed

    private void battleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battleButtonActionPerformed
        // TODO add your handling code here:
        BattleDialog dialog = new BattleDialog(this, true, Command.START_BATTLE);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_battleButtonActionPerformed

    private void varButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varButtonActionPerformed
        // TODO add your handling code here:
        VarDialog dialog = new VarDialog(this, true, Command.OPERATE_VAR);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_varButtonActionPerformed

    private void switchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchButtonActionPerformed
        // TODO add your handling code here:
        SwitchDialog dialog = new SwitchDialog(this, true, Command.OPERATE_SWITCH);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_switchButtonActionPerformed

    private void faceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faceButtonActionPerformed
        // TODO add your handling code here:
        FaceDialog fd = new FaceDialog(this, true, Command.CHANGE_FACE);
        fd.setVisible(true);
        addCommand(fd.getCommand());
    }//GEN-LAST:event_faceButtonActionPerformed

    private void waitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitButtonActionPerformed
        // TODO add your handling code here:
        WaitDialog hd = new WaitDialog(this, true, Command.WAIT);
        hd.setVisible(true);
        addCommand(hd.getCommand());
    }//GEN-LAST:event_waitButtonActionPerformed

    private void moneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyButtonActionPerformed
        // TODO add your handling code here:
        MoneyDialog md = new MoneyDialog(this, true, Command.OPERATE_MONEY);
        md.setVisible(true);
        addCommand(md.getCommand());
    }//GEN-LAST:event_moneyButtonActionPerformed

    private void powButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powButtonActionPerformed
        // TODO add your handling code here:
        PowerDialog dialog = new PowerDialog(this, true, Command.OPERATE_POWER);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_powButtonActionPerformed

    private void skillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skillButtonActionPerformed
        // TODO add your handling code here:
        SkillDialog dialog = new SkillDialog(this, true, Command.OPERATE_SKILL);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_skillButtonActionPerformed

    private void itemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemButtonActionPerformed
        // TODO add your handling code here:
        ItemDialog dialog = new ItemDialog(this, true, Command.OPERATE_ITEM_LIST);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_itemButtonActionPerformed

    private void equipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipButtonActionPerformed
        // TODO add your handling code here:
        EquipDialog dialog = new EquipDialog(this, true, Command.OPERATE_EQUIP_LIST);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_equipButtonActionPerformed

    private void publicEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicEventButtonActionPerformed
        // TODO add your handling code here:
        PublicEventDialog ped = new PublicEventDialog(this, true, Command.PUBLIC_EVENT);
        ped.setVisible(true);
        addCommand(ped.getCommand());
    }//GEN-LAST:event_publicEventButtonActionPerformed

    private void showCountDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCountDownButtonActionPerformed
        // TODO add your handling code here:
        ShowCountDownDialog scdd = new ShowCountDownDialog(this, true, Command.SHOW_COUNT_DOWN);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_showCountDownButtonActionPerformed

    private void showChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showChooseButtonActionPerformed
        // TODO add your handling code here:
        ShowChooseDialog scdd = new ShowChooseDialog(this, true, Command.SHOW_CHOOSE);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_showChooseButtonActionPerformed

    private void showInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInputButtonActionPerformed
        // TODO add your handling code here:
        ShowInputDialog scdd = new ShowInputDialog(this, true, Command.SHOW_INPUT);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_showInputButtonActionPerformed

    private void moveImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveImageButtonActionPerformed
        // TODO add your handling code here:
        MoveImageDialog scdd = new MoveImageDialog(this, true, Command.MOVE_IMAGE);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_moveImageButtonActionPerformed

    private void showAniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAniButtonActionPerformed
        // TODO add your handling code here:
        ShowAnimationDialog scdd = new ShowAnimationDialog(this, true);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_showAniButtonActionPerformed

    private void removeImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeImageButtonActionPerformed
        // TODO add your handling code here:
        RemoveImageDialog scdd = new RemoveImageDialog(this, true, Command.REMOVE_IMAGE);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_removeImageButtonActionPerformed

    private void rotateImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateImageButtonActionPerformed
        // TODO add your handling code here:
        RotateImageDialog scdd = new RotateImageDialog(this, true, Command.ROTATE_IMAGE);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_rotateImageButtonActionPerformed

    private void stopMusicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopMusicButtonActionPerformed
        // TODO add your handling code here:
        StopMusicDialog scdd = new StopMusicDialog(this, true, Command.STOP_MUSIC);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_stopMusicButtonActionPerformed

    private void endBattleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endBattleButtonActionPerformed
        // TODO add your handling code here:
        Command command = new Command();
        command.setScriptId(Command.STOP_BATTLE);
        System.out.println(command);
        addCommand(command);
//        insertScriptData(npcPane.eventTable.getSelectedRow(), "globalData.proxy:exitFight()");
    }//GEN-LAST:event_endBattleButtonActionPerformed

    private void showImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showImageButtonActionPerformed
        // TODO add your handling code here:
        ShowImageDialog scdd = new ShowImageDialog(this, true, Command.SHOW_IMAGE);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_showImageButtonActionPerformed

    private void changeImageARGBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeImageARGBButtonActionPerformed
        // TODO add your handling code here:
        ChangeImageARGBDialog scdd = new ChangeImageARGBDialog(this, true, Command.CHANGE_IMAGE_COLOR);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_changeImageARGBButtonActionPerformed

    private void changeSkinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSkinButtonActionPerformed
        // TODO add your handling code here:
        ChangeSkinDialog scdd = new ChangeSkinDialog(this, true, Command.CHANGE_SKIN);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_changeSkinButtonActionPerformed

    private void changeScreenColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeScreenColorButtonActionPerformed
        // TODO add your handling code here:
        ChangeScreenARGBDialog scdd = new ChangeScreenARGBDialog(this, true, Command.CHANGE_SCREEN_COLOR);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_changeScreenColorButtonActionPerformed

    private void systemMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemMenuButtonActionPerformed
        // TODO add your handling code here:
        Command command = new Command();
        command.setScriptId(Command.OPEN_SYSTEM_MENU);
        System.out.println(command);
        addCommand(command);
//        insertScriptData(npcPane.eventTable.getSelectedRow(), "globalData.proxy:openSystemMenu()");
    }//GEN-LAST:event_systemMenuButtonActionPerformed

    private void shakeScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shakeScreenButtonActionPerformed
        // TODO add your handling code here:
        ScreenShockDialog scdd = new ScreenShockDialog(this, true, Command.SCREEN_SHOCK);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_shakeScreenButtonActionPerformed

    private void gameSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameSaveButtonActionPerformed
        // TODO add your handling code here:
        Command command = new Command();
        command.setScriptId(Command.OPEN_RECORD_MENU);
        System.out.println(command);
        addCommand(command);
//        insertScriptData(npcPane.eventTable.getSelectedRow(), "globalData.proxy:openRecordMenu()");
    }//GEN-LAST:event_gameSaveButtonActionPerformed

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // TODO add your handling code here:
        Command command = new Command();
        command.setScriptId(Command.OPEN_MAIN_MENU);
        System.out.println(command);
        addCommand(command);
//        insertScriptData(npcPane.eventTable.getSelectedRow(), "globalData.proxy:returnToMainMenu()");
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void changeNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNameButtonActionPerformed
        // TODO add your handling code here:
        ChangePlayerNameDialog scdd = new ChangePlayerNameDialog(this, true, Command.CHANGE_PLAYER_NAME);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_changeNameButtonActionPerformed

    private void changeModalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeModalButtonActionPerformed
        // TODO add your handling code here:
        ChangePlayerModelDialog scdd = new ChangePlayerModelDialog(this, true, Command.CHNAGE_PLAYER_MODEL);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_changeModalButtonActionPerformed

    private void changeEquipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeEquipButtonActionPerformed
        // TODO add your handling code here:
        ChangeEquipDialog scdd = new ChangeEquipDialog(this, true, Command.OPERATE_EQUIP);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_changeEquipButtonActionPerformed

    private void changeEnemyPowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeEnemyPowerButtonActionPerformed
        // TODO add your handling code here:
        ChangeEnemyPowerDialog scdd = new ChangeEnemyPowerDialog(this, true, Command.OPERATE_ENEMY_POWER);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_changeEnemyPowerButtonActionPerformed

    private void enemyTransButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enemyTransButtonActionPerformed
        // TODO add your handling code here:
        ChangeEnemyModelDialog scdd = new ChangeEnemyModelDialog(this, true, Command.CHANGE_ENEMY_MODEL);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_enemyTransButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton battleButton;
    private javax.swing.JButton breakButton;
    private javax.swing.JButton cancleButton;
    private javax.swing.JButton changeEnemyPowerButton;
    private javax.swing.JButton changeEquipButton;
    private javax.swing.JButton changeImageARGBButton;
    private javax.swing.JButton changeModalButton;
    private javax.swing.JButton changeNameButton;
    private javax.swing.JButton changeScreenColorButton;
    private javax.swing.JButton changeSkinButton;
    private javax.swing.JButton endBattleButton;
    private javax.swing.JButton enemyTransButton;
    private javax.swing.JButton equipButton;
    private javax.swing.JButton exitScriptButton;
    private javax.swing.JButton faceButton;
    private javax.swing.JButton gameSaveButton;
    private javax.swing.JButton ifButton;
    private javax.swing.JButton itemButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton mapButton;
    private javax.swing.JButton moneyButton;
    private javax.swing.JButton moveButton;
    private javax.swing.JButton moveImageButton;
    private javax.swing.JButton openShopButton;
    private javax.swing.JButton playMusicButton;
    private javax.swing.JButton powButton;
    private javax.swing.JButton publicEventButton;
    private javax.swing.JButton removeImageButton;
    private javax.swing.JButton rotateImageButton;
    private javax.swing.JTabbedPane scriptTabbedPane;
    private javax.swing.JButton shakeScreenButton;
    private javax.swing.JButton showAniButton;
    private javax.swing.JButton showChooseButton;
    private javax.swing.JButton showCountDownButton;
    private javax.swing.JButton showImageButton;
    private javax.swing.JButton showInputButton;
    private javax.swing.JButton showMessageButton;
    private javax.swing.JButton skillButton;
    private javax.swing.JButton stopMusicButton;
    private javax.swing.JButton switchButton;
    private javax.swing.JButton systemMenuButton;
    private javax.swing.JButton varButton;
    private javax.swing.JButton waitButton;
    private javax.swing.JButton whileButton;
    // End of variables declaration//GEN-END:variables
}
