/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScriptDialog.java
 *
 * Created on 2011-3-27, 13:57:50
 */
package com.soyomaker.dialog;

import com.soyomaker.dialog.event.dataprocess.ChangeEnemyModelDialog;
import com.soyomaker.dialog.event.dataprocess.ChangeEnemyPowerDialog;
import com.soyomaker.dialog.event.dataprocess.ChangeEquipDialog;
import com.soyomaker.dialog.event.dataprocess.ChangePlayerModelDialog;
import com.soyomaker.dialog.event.dataprocess.ChangePlayerNameDialog;
import com.soyomaker.dialog.event.gameperformance.BattleDialog;
import com.soyomaker.dialog.event.dataprocess.EquipDialog;
import com.soyomaker.dialog.event.gameperformance.FaceDialog;
import com.soyomaker.dialog.event.dataprocess.ItemDialog;
import com.soyomaker.dialog.event.gameperformance.OpenShopDialog;
import com.soyomaker.dialog.event.gameperformance.MapDialog;
import com.soyomaker.dialog.event.gameperformance.ShowMessageDialog;
import com.soyomaker.dialog.event.dataprocess.MoneyDialog;
import com.soyomaker.dialog.event.gameperformance.MoveDialog;
import com.soyomaker.dialog.event.gameperformance.PlayMusicDialog;
import com.soyomaker.dialog.event.dataprocess.PowerDialog;
import com.soyomaker.dialog.event.dataprocess.SkillDialog;
import com.soyomaker.dialog.event.dataprocess.SwitchDialog;
import com.soyomaker.dialog.event.dataprocess.VarDialog;
import com.soyomaker.dialog.event.gameperformance.ChangeImageARGBDialog;
import com.soyomaker.dialog.event.gameperformance.ChangeScreenARGBDialog;
import com.soyomaker.dialog.event.gameperformance.ChangeSkinDialog;
import com.soyomaker.dialog.event.gameperformance.MoveImageDialog;
import com.soyomaker.dialog.event.gameperformance.RemoveImageDialog;
import com.soyomaker.dialog.event.gameperformance.RotateImageDialog;
import com.soyomaker.dialog.event.gameperformance.ScreenShockDialog;
import com.soyomaker.dialog.event.gameperformance.ShowAnimationDialog;
import com.soyomaker.dialog.event.gameperformance.ShowChooseDialog;
import com.soyomaker.dialog.event.gameperformance.ShowCountDownDialog;
import com.soyomaker.dialog.event.gameperformance.ShowImageDialog;
import com.soyomaker.dialog.event.gameperformance.ShowInputDialog;
import com.soyomaker.dialog.event.gameperformance.StopMusicDialog;
import com.soyomaker.dialog.event.processcontrol.IfDialog;
import com.soyomaker.dialog.event.processcontrol.PublicEventDialog;
import com.soyomaker.dialog.event.processcontrol.WaitDialog;
import com.soyomaker.model.map.Command;
import com.soyomaker.model.map.Script;
import com.soyomaker.widget.NpcStatePane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author Administrator
 */
public class ScriptDialog extends javax.swing.JDialog {

    /** Creates new form ScriptDialog
     * @param parent 
     * @param modal 
     */
    public ScriptDialog(NpcStatePane parent, boolean modal) {
        setModal(modal);
        initComponents();
        initialize();
        npcStatePane = parent;
    }
    private NpcStatePane npcStatePane = null;
    private Script mScript = null;

    /**
     *
     * @param script
     */
    public void setScript(Script script) {
        mScript = script;
    }

    private void initialize() {
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scriptTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        breakButton = new javax.swing.JButton();
        ifButton = new javax.swing.JButton();
        whileButton = new javax.swing.JButton();
        exitScriptButton = new javax.swing.JButton();
        publicEventButton = new javax.swing.JButton();
        waitButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        mapButton = new javax.swing.JButton();
        moveButton = new javax.swing.JButton();
        showMessageButton = new javax.swing.JButton();
        playMusicButton = new javax.swing.JButton();
        openShopButton = new javax.swing.JButton();
        battleButton = new javax.swing.JButton();
        faceButton = new javax.swing.JButton();
        showChooseButton = new javax.swing.JButton();
        showInputButton = new javax.swing.JButton();
        showImageButton = new javax.swing.JButton();
        showCountDownButton = new javax.swing.JButton();
        showAniButton = new javax.swing.JButton();
        stopMusicButton = new javax.swing.JButton();
        moveImageButton = new javax.swing.JButton();
        rotateImageButton = new javax.swing.JButton();
        changeImageARGBButton = new javax.swing.JButton();
        changeSkinButton = new javax.swing.JButton();
        removeImageButton = new javax.swing.JButton();
        shakeScreenButton = new javax.swing.JButton();
        changeScreenColorButton = new javax.swing.JButton();
        systemMenuButton = new javax.swing.JButton();
        gameSaveButton = new javax.swing.JButton();
        mainMenuButton = new javax.swing.JButton();
        endBattleButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        powButton = new javax.swing.JButton();
        skillButton = new javax.swing.JButton();
        equipButton = new javax.swing.JButton();
        itemButton = new javax.swing.JButton();
        moneyButton = new javax.swing.JButton();
        varButton = new javax.swing.JButton();
        switchButton = new javax.swing.JButton();
        changeEquipButton = new javax.swing.JButton();
        changeModalButton = new javax.swing.JButton();
        changeNameButton = new javax.swing.JButton();
        changeEnemyPowerButton = new javax.swing.JButton();
        enemyTransButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ScriptDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setResizable(false);

        jPanel1.setName("jPanel1"); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N

        breakButton.setText("跳出循环");
        breakButton.setName("breakButton"); // NOI18N
        breakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakButtonActionPerformed(evt);
            }
        });

        ifButton.setText("条件分支");
        ifButton.setName("ifButton"); // NOI18N
        ifButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifButtonActionPerformed(evt);
            }
        });

        whileButton.setText("循环结构");
        whileButton.setName("whileButton"); // NOI18N
        whileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whileButtonActionPerformed(evt);
            }
        });

        exitScriptButton.setText("结束脚本");
        exitScriptButton.setName("exitScriptButton"); // NOI18N
        exitScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitScriptButtonActionPerformed(evt);
            }
        });

        publicEventButton.setText("公共事件");
        publicEventButton.setName("publicEventButton"); // NOI18N
        publicEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicEventButtonActionPerformed(evt);
            }
        });

        waitButton.setText("强制等待");
        waitButton.setName("waitButton"); // NOI18N
        waitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(breakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ifButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(whileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publicEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitScriptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {breakButton, exitScriptButton, ifButton, publicEventButton, waitButton, whileButton});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(waitButton)
                        .addGap(18, 18, 18)
                        .addComponent(exitScriptButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(ifButton)
                            .addComponent(whileButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(breakButton)
                            .addComponent(publicEventButton))))
                .addGap(344, 344, 344))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {breakButton, exitScriptButton, ifButton, publicEventButton, waitButton, whileButton});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        scriptTabbedPane.addTab("流程控制", jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N

        jPanel5.setName("jPanel5"); // NOI18N

        mapButton.setText("切换地图");
        mapButton.setName("mapButton"); // NOI18N
        mapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapButtonActionPerformed(evt);
            }
        });

        moveButton.setText("设置移动");
        moveButton.setName("moveButton"); // NOI18N
        moveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveButtonActionPerformed(evt);
            }
        });

        showMessageButton.setText("显示对话框");
        showMessageButton.setName("showMessageButton"); // NOI18N
        showMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMessageButtonActionPerformed(evt);
            }
        });

        playMusicButton.setText("播放音乐");
        playMusicButton.setName("playMusicButton"); // NOI18N
        playMusicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playMusicButtonActionPerformed(evt);
            }
        });

        openShopButton.setText("开启商店");
        openShopButton.setName("openShopButton"); // NOI18N
        openShopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openShopButtonActionPerformed(evt);
            }
        });

        battleButton.setText("开启战斗");
        battleButton.setName("battleButton"); // NOI18N
        battleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battleButtonActionPerformed(evt);
            }
        });

        faceButton.setText("改变面向");
        faceButton.setName("faceButton"); // NOI18N
        faceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faceButtonActionPerformed(evt);
            }
        });

        showChooseButton.setText("显示选项框");
        showChooseButton.setName("showChooseButton"); // NOI18N
        showChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showChooseButtonActionPerformed(evt);
            }
        });

        showInputButton.setText("显示输入框");
        showInputButton.setName("showInputButton"); // NOI18N
        showInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInputButtonActionPerformed(evt);
            }
        });

        showImageButton.setText("显示图片");
        showImageButton.setName("showImageButton"); // NOI18N
        showImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showImageButtonActionPerformed(evt);
            }
        });

        showCountDownButton.setText("显示倒计时");
        showCountDownButton.setName("showCountDownButton"); // NOI18N
        showCountDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCountDownButtonActionPerformed(evt);
            }
        });

        showAniButton.setText("显示动画");
        showAniButton.setName("showAniButton"); // NOI18N
        showAniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAniButtonActionPerformed(evt);
            }
        });

        stopMusicButton.setText("停止音乐");
        stopMusicButton.setName("stopMusicButton"); // NOI18N
        stopMusicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopMusicButtonActionPerformed(evt);
            }
        });

        moveImageButton.setText("移动图片");
        moveImageButton.setName("moveImageButton"); // NOI18N
        moveImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveImageButtonActionPerformed(evt);
            }
        });

        rotateImageButton.setText("旋转图片");
        rotateImageButton.setName("rotateImageButton"); // NOI18N
        rotateImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateImageButtonActionPerformed(evt);
            }
        });

        changeImageARGBButton.setText("更改图片色调");
        changeImageARGBButton.setName("changeImageARGBButton"); // NOI18N
        changeImageARGBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeImageARGBButtonActionPerformed(evt);
            }
        });

        changeSkinButton.setText("更换皮肤");
        changeSkinButton.setName("changeSkinButton"); // NOI18N
        changeSkinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSkinButtonActionPerformed(evt);
            }
        });

        removeImageButton.setText("移除图片");
        removeImageButton.setName("removeImageButton"); // NOI18N
        removeImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeImageButtonActionPerformed(evt);
            }
        });

        shakeScreenButton.setText("画面震动");
        shakeScreenButton.setName("shakeScreenButton"); // NOI18N
        shakeScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shakeScreenButtonActionPerformed(evt);
            }
        });

        changeScreenColorButton.setText("更改画面色调");
        changeScreenColorButton.setName("changeScreenColorButton"); // NOI18N
        changeScreenColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeScreenColorButtonActionPerformed(evt);
            }
        });

        systemMenuButton.setText("打开系统菜单");
        systemMenuButton.setName("systemMenuButton"); // NOI18N
        systemMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemMenuButtonActionPerformed(evt);
            }
        });

        gameSaveButton.setText("打开存档菜单");
        gameSaveButton.setName("gameSaveButton"); // NOI18N
        gameSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameSaveButtonActionPerformed(evt);
            }
        });

        mainMenuButton.setText("回主菜单");
        mainMenuButton.setName("mainMenuButton"); // NOI18N
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        endBattleButton.setText("结束战斗");
        endBattleButton.setName("endBattleButton"); // NOI18N
        endBattleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endBattleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(changeImageARGBButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(battleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(faceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playMusicButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mapButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(changeScreenColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(gameSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(openShopButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(moveImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(rotateImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(changeSkinButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(systemMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(endBattleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopMusicButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showChooseButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(showInputButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(showAniButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(showMessageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(showImageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(showCountDownButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(shakeScreenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(mainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {battleButton, changeImageARGBButton, changeScreenColorButton, changeSkinButton, endBattleButton, faceButton, gameSaveButton, mainMenuButton, mapButton, moveButton, moveImageButton, openShopButton, playMusicButton, removeImageButton, rotateImageButton, shakeScreenButton, showAniButton, showChooseButton, showCountDownButton, showImageButton, showInputButton, showMessageButton, stopMusicButton, systemMenuButton});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(endBattleButton)
                                .addComponent(changeScreenColorButton))
                            .addGap(123, 123, 123))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(showCountDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                            .addComponent(showChooseButton)
                            .addGap(18, 18, 18)
                            .addComponent(showInputButton)
                            .addGap(18, 18, 18)
                            .addComponent(showAniButton)
                            .addGap(18, 18, 18)
                            .addComponent(showMessageButton)
                            .addGap(18, 18, 18)
                            .addComponent(showImageButton)
                            .addGap(82, 82, 82))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(moveButton)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(openShopButton)
                                .addComponent(shakeScreenButton))
                            .addGap(59, 59, 59)
                            .addComponent(moveImageButton)
                            .addGap(18, 18, 18)
                            .addComponent(rotateImageButton)
                            .addGap(59, 59, 59)
                            .addComponent(changeSkinButton)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(systemMenuButton)
                                .addComponent(gameSaveButton)
                                .addComponent(mainMenuButton))
                            .addGap(41, 41, 41)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(mapButton)
                        .addGap(18, 18, 18)
                        .addComponent(playMusicButton)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(faceButton)
                            .addComponent(stopMusicButton))
                        .addGap(18, 18, 18)
                        .addComponent(battleButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeImageButton)
                        .addGap(59, 59, 59)
                        .addComponent(changeImageARGBButton)
                        .addGap(82, 82, 82)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {battleButton, changeImageARGBButton, changeScreenColorButton, changeSkinButton, endBattleButton, faceButton, gameSaveButton, mainMenuButton, mapButton, moveButton, moveImageButton, openShopButton, playMusicButton, removeImageButton, rotateImageButton, shakeScreenButton, showAniButton, showChooseButton, showCountDownButton, showImageButton, showInputButton, showMessageButton, stopMusicButton, systemMenuButton});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        scriptTabbedPane.addTab("游戏表现", jPanel2);

        jPanel3.setName("jPanel3"); // NOI18N

        jPanel6.setName("jPanel6"); // NOI18N

        powButton.setText("增减属性");
        powButton.setName("powButton"); // NOI18N
        powButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powButtonActionPerformed(evt);
            }
        });

        skillButton.setText("增减技能");
        skillButton.setName("skillButton"); // NOI18N
        skillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skillButtonActionPerformed(evt);
            }
        });

        equipButton.setText("增减装备");
        equipButton.setName("equipButton"); // NOI18N
        equipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipButtonActionPerformed(evt);
            }
        });

        itemButton.setText("增减物品");
        itemButton.setName("itemButton"); // NOI18N
        itemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemButtonActionPerformed(evt);
            }
        });

        moneyButton.setText("增减金钱");
        moneyButton.setName("moneyButton"); // NOI18N
        moneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyButtonActionPerformed(evt);
            }
        });

        varButton.setText("变量操作");
        varButton.setName("varButton"); // NOI18N
        varButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varButtonActionPerformed(evt);
            }
        });

        switchButton.setText("开关操作");
        switchButton.setName("switchButton"); // NOI18N
        switchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchButtonActionPerformed(evt);
            }
        });

        changeEquipButton.setText("切换装备");
        changeEquipButton.setName("changeEquipButton"); // NOI18N
        changeEquipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeEquipButtonActionPerformed(evt);
            }
        });

        changeModalButton.setText("角色变身");
        changeModalButton.setName("changeModalButton"); // NOI18N
        changeModalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeModalButtonActionPerformed(evt);
            }
        });

        changeNameButton.setText("修改角色名称");
        changeNameButton.setName("changeNameButton"); // NOI18N
        changeNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNameButtonActionPerformed(evt);
            }
        });

        changeEnemyPowerButton.setText("增减敌人属性");
        changeEnemyPowerButton.setName("changeEnemyPowerButton"); // NOI18N
        changeEnemyPowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeEnemyPowerButtonActionPerformed(evt);
            }
        });

        enemyTransButton.setText("敌人变身");
        enemyTransButton.setName("enemyTransButton"); // NOI18N
        enemyTransButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enemyTransButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(powButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(skillButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moneyButton)
                            .addComponent(itemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(varButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(switchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(changeEnemyPowerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(changeNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(equipButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(changeEquipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(changeModalButton)
                        .addGap(18, 18, 18)
                        .addComponent(enemyTransButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {changeEnemyPowerButton, changeEquipButton, changeModalButton, changeNameButton, enemyTransButton, equipButton, itemButton, moneyButton, powButton, skillButton, switchButton, varButton});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(powButton)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(skillButton))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(switchButton)
                            .addComponent(itemButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moneyButton)
                            .addComponent(varButton))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(equipButton)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(changeEnemyPowerButton)
                        .addComponent(changeNameButton)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeEquipButton)
                    .addComponent(changeModalButton)
                    .addComponent(enemyTransButton))
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {changeEnemyPowerButton, changeEquipButton, changeModalButton, changeNameButton, enemyTransButton, equipButton, itemButton, moneyButton, powButton, skillButton, switchButton, varButton});

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        scriptTabbedPane.addTab("数据处理", jPanel3);

        cancleButton.setText("关闭");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scriptTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(cancleButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(scriptTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancleButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancleButtonActionPerformed

    private void ifButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifButtonActionPerformed
        // TODO add your handling code here:
        IfDialog md = new IfDialog(this, true, Command.IF);
        md.setVisible(true);

        addCommand(md.getCommand());
    }//GEN-LAST:event_ifButtonActionPerformed

    private void whileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whileButtonActionPerformed
        // TODO add your handling code here:
        Command c3 = new Command();
        c3.setScriptId(Command.WHILE);

        addCommand(c3);
    }//GEN-LAST:event_whileButtonActionPerformed

    private void exitScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitScriptButtonActionPerformed
        // TODO add your handling code here:
        Command c1 = new Command();
        c1.setScriptId(Command.EXIT_SCRIPT);

        addCommand(c1);
    }//GEN-LAST:event_exitScriptButtonActionPerformed

    private void breakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakButtonActionPerformed
        // TODO add your handling code here:
        Command c1 = new Command();
        c1.setScriptId(Command.BREAK);

        addCommand(c1);
    }//GEN-LAST:event_breakButtonActionPerformed

    private void addCommand(Command c) {
        if (c == null) {
            return;
        }
        DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(c);
        Command c2 = new Command();
        c2.setScriptId(Command.INVALID);
        DefaultMutableTreeNode newNode2 = new DefaultMutableTreeNode(c2);
        if (c.getScriptId() == Command.IF || c.getScriptId() == Command.WHILE) {
            c.addCommand(c2);
            newNode.add(newNode2);
        }
        DefaultMutableTreeNode selectedNode = npcStatePane.commandTree.getSelectNode();
        if (selectedNode == null) {
            ((DefaultMutableTreeNode) npcStatePane.commandTree.getModel().getRoot()).add(newNode);
            ((DefaultTreeModel) npcStatePane.commandTree.getModel()).reload((DefaultMutableTreeNode) npcStatePane.commandTree.getModel().getRoot());
            mScript.addCommand(c);
        } else {
            DefaultMutableTreeNode parentNode = (DefaultMutableTreeNode) selectedNode.getParent();
            if (parentNode == null) {
                ((DefaultMutableTreeNode) npcStatePane.commandTree.getModel().getRoot()).add(newNode);
                ((DefaultTreeModel) npcStatePane.commandTree.getModel()).reload((DefaultMutableTreeNode) npcStatePane.commandTree.getModel().getRoot());
                mScript.addCommand(c);
            } else if (parentNode.getUserObject() instanceof Command
                    && (((Command) parentNode.getUserObject()).getScriptId() == Command.IF || ((Command) parentNode.getUserObject()).getScriptId() == Command.WHILE)) {
                int index = parentNode.getIndex(selectedNode);
                parentNode.insert(newNode, index + 1);
                ((DefaultTreeModel) npcStatePane.commandTree.getModel()).reload(npcStatePane.commandTree.getSelectNode());
                ((Command) parentNode.getUserObject()).addCommand(index + 1, c);
            } else {
                int index = parentNode.getIndex(selectedNode);
                ((DefaultMutableTreeNode) npcStatePane.commandTree.getModel().getRoot()).insert(newNode, index + 1);
                ((DefaultTreeModel) npcStatePane.commandTree.getModel()).reload((DefaultMutableTreeNode) npcStatePane.commandTree.getModel().getRoot());
                mScript.addCommand(index + 1, c);
            }
        }
        npcStatePane.commandTree.expandPath(npcStatePane.commandTree.getSelectionPath());
        if (c.getScriptId() == Command.IF || c.getScriptId() == Command.WHILE) {
            npcStatePane.commandTree.setSelectionPath(new TreePath(((DefaultTreeModel) npcStatePane.commandTree.getModel()).getPathToRoot(newNode2)));
        } else {
            npcStatePane.commandTree.setSelectionPath(new TreePath(((DefaultTreeModel) npcStatePane.commandTree.getModel()).getPathToRoot(newNode)));
        }
        //设置维持当前的选择路径
        npcStatePane.commandTree.setExpandsSelectedPaths(true);
        dispose();
    }
    private void mapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapButtonActionPerformed
        // TODO add your handling code here:
        MapDialog md = new MapDialog(this, true, Command.CHANGE_MAP);
        md.setVisible(true);
        addCommand(md.getCommand());
    }//GEN-LAST:event_mapButtonActionPerformed

    private void moveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveButtonActionPerformed
        // TODO add your handling code here:
        MoveDialog md = new MoveDialog(this, true, Command.MOVE);
        md.setVisible(true);
        addCommand(md.getCommand());
    }//GEN-LAST:event_moveButtonActionPerformed

    private void showMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMessageButtonActionPerformed
        // TODO add your handling code here:
        ShowMessageDialog md = new ShowMessageDialog(this, true, Command.SHOW_MESSAGE);
        md.setVisible(true);
        addCommand(md.getCommand());
    }//GEN-LAST:event_showMessageButtonActionPerformed

    private void playMusicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playMusicButtonActionPerformed
        // TODO add your handling code here:
        PlayMusicDialog dialog = new PlayMusicDialog(this, true, Command.PLAY_MUSIC);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_playMusicButtonActionPerformed

    private void openShopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openShopButtonActionPerformed
        // TODO add your handling code here:
        OpenShopDialog dialog = new OpenShopDialog(this, true, Command.OPEN_SHOP);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_openShopButtonActionPerformed

    private void battleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battleButtonActionPerformed
        // TODO add your handling code here:
        BattleDialog dialog = new BattleDialog(this, true, Command.START_BATTLE);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_battleButtonActionPerformed

    private void varButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varButtonActionPerformed
        // TODO add your handling code here:
        VarDialog dialog = new VarDialog(this, true, Command.OPERATE_VAR);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_varButtonActionPerformed

    private void switchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchButtonActionPerformed
        // TODO add your handling code here:
        SwitchDialog dialog = new SwitchDialog(this, true, Command.OPERATE_SWITCH);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_switchButtonActionPerformed

    private void faceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faceButtonActionPerformed
        // TODO add your handling code here:
        FaceDialog fd = new FaceDialog(this, true, Command.CHANGE_FACE);
        fd.setVisible(true);
        addCommand(fd.getCommand());
    }//GEN-LAST:event_faceButtonActionPerformed

    private void waitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitButtonActionPerformed
        // TODO add your handling code here:
        WaitDialog hd = new WaitDialog(this, true, Command.WAIT);
        hd.setVisible(true);
        addCommand(hd.getCommand());
    }//GEN-LAST:event_waitButtonActionPerformed

    private void moneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyButtonActionPerformed
        // TODO add your handling code here:
        MoneyDialog md = new MoneyDialog(this, true, Command.OPERATE_MONEY);
        md.setVisible(true);
        addCommand(md.getCommand());
    }//GEN-LAST:event_moneyButtonActionPerformed

    private void powButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powButtonActionPerformed
        // TODO add your handling code here:
        PowerDialog dialog = new PowerDialog(this, true, Command.OPERATE_POWER);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_powButtonActionPerformed

    private void skillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skillButtonActionPerformed
        // TODO add your handling code here:
        SkillDialog dialog = new SkillDialog(this, true, Command.OPERATE_SKILL);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_skillButtonActionPerformed

    private void itemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemButtonActionPerformed
        // TODO add your handling code here:
        ItemDialog dialog = new ItemDialog(this, true, Command.OPERATE_ITEM_LIST);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_itemButtonActionPerformed

    private void equipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipButtonActionPerformed
        // TODO add your handling code here:
        EquipDialog dialog = new EquipDialog(this, true, Command.OPERATE_EQUIP_LIST);
        dialog.setVisible(true);
        addCommand(dialog.getCommand());
    }//GEN-LAST:event_equipButtonActionPerformed

    private void publicEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicEventButtonActionPerformed
        // TODO add your handling code here:
        PublicEventDialog ped = new PublicEventDialog(this, true, Command.PUBLIC_EVENT);
        ped.setVisible(true);
        addCommand(ped.getCommand());
    }//GEN-LAST:event_publicEventButtonActionPerformed

    private void showCountDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCountDownButtonActionPerformed
        // TODO add your handling code here:
        ShowCountDownDialog scdd = new ShowCountDownDialog(this, true, Command.SHOW_COUNT_DOWN);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_showCountDownButtonActionPerformed

    private void showChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showChooseButtonActionPerformed
        // TODO add your handling code here:
        ShowChooseDialog scdd = new ShowChooseDialog(this, true, Command.SHOW_CHOOSE);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_showChooseButtonActionPerformed

    private void showInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInputButtonActionPerformed
        // TODO add your handling code here:
        ShowInputDialog scdd = new ShowInputDialog(this, true, Command.SHOW_INPUT);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_showInputButtonActionPerformed

    private void moveImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveImageButtonActionPerformed
        // TODO add your handling code here:
        MoveImageDialog scdd = new MoveImageDialog(this, true, Command.MOVE_IMAGE);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_moveImageButtonActionPerformed

    private void showAniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAniButtonActionPerformed
        // TODO add your handling code here:
        ShowAnimationDialog scdd = new ShowAnimationDialog(this, true);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_showAniButtonActionPerformed

    private void removeImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeImageButtonActionPerformed
        // TODO add your handling code here:
        RemoveImageDialog scdd = new RemoveImageDialog(this, true, Command.REMOVE_IMAGE);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_removeImageButtonActionPerformed

    private void rotateImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateImageButtonActionPerformed
        // TODO add your handling code here:
        RotateImageDialog scdd = new RotateImageDialog(this, true, Command.ROTATE_IMAGE);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_rotateImageButtonActionPerformed

    private void stopMusicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopMusicButtonActionPerformed
        // TODO add your handling code here:
        StopMusicDialog scdd = new StopMusicDialog(this, true, Command.STOP_MUSIC);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_stopMusicButtonActionPerformed

    private void endBattleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endBattleButtonActionPerformed
        // TODO add your handling code here:
        Command command = new Command();
        command.setScriptId(Command.STOP_BATTLE);
        System.out.println(command);
        addCommand(command);
//        insertScriptData(npcPane.eventTable.getSelectedRow(), "globalData.proxy:exitFight()");
    }//GEN-LAST:event_endBattleButtonActionPerformed

    private void showImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showImageButtonActionPerformed
        // TODO add your handling code here:
        ShowImageDialog scdd = new ShowImageDialog(this, true, Command.SHOW_IMAGE);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_showImageButtonActionPerformed

    private void changeImageARGBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeImageARGBButtonActionPerformed
        // TODO add your handling code here:
        ChangeImageARGBDialog scdd = new ChangeImageARGBDialog(this, true, Command.CHANGE_IMAGE_COLOR);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_changeImageARGBButtonActionPerformed

    private void changeSkinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSkinButtonActionPerformed
        // TODO add your handling code here:
        ChangeSkinDialog scdd = new ChangeSkinDialog(this, true, Command.CHANGE_SKIN);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_changeSkinButtonActionPerformed

    private void changeScreenColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeScreenColorButtonActionPerformed
        // TODO add your handling code here:
        ChangeScreenARGBDialog scdd = new ChangeScreenARGBDialog(this, true, Command.CHANGE_SCREEN_COLOR);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_changeScreenColorButtonActionPerformed

    private void systemMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemMenuButtonActionPerformed
        // TODO add your handling code here:
        Command command = new Command();
        command.setScriptId(Command.OPEN_SYSTEM_MENU);
        System.out.println(command);
        addCommand(command);
//        insertScriptData(npcPane.eventTable.getSelectedRow(), "globalData.proxy:openSystemMenu()");
    }//GEN-LAST:event_systemMenuButtonActionPerformed

    private void shakeScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shakeScreenButtonActionPerformed
        // TODO add your handling code here:
        ScreenShockDialog scdd = new ScreenShockDialog(this, true, Command.SCREEN_SHOCK);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_shakeScreenButtonActionPerformed

    private void gameSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameSaveButtonActionPerformed
        // TODO add your handling code here:
        Command command = new Command();
        command.setScriptId(Command.OPEN_RECORD_MENU);
        System.out.println(command);
        addCommand(command);
//        insertScriptData(npcPane.eventTable.getSelectedRow(), "globalData.proxy:openRecordMenu()");
    }//GEN-LAST:event_gameSaveButtonActionPerformed

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // TODO add your handling code here:
        Command command = new Command();
        command.setScriptId(Command.OPEN_MAIN_MENU);
        System.out.println(command);
        addCommand(command);
//        insertScriptData(npcPane.eventTable.getSelectedRow(), "globalData.proxy:returnToMainMenu()");
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void changeNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNameButtonActionPerformed
        // TODO add your handling code here:
        ChangePlayerNameDialog scdd = new ChangePlayerNameDialog(this, true, Command.CHANGE_PLAYER_NAME);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_changeNameButtonActionPerformed

    private void changeModalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeModalButtonActionPerformed
        // TODO add your handling code here:
        ChangePlayerModelDialog scdd = new ChangePlayerModelDialog(this, true, Command.CHNAGE_PLAYER_MODEL);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_changeModalButtonActionPerformed

    private void changeEquipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeEquipButtonActionPerformed
        // TODO add your handling code here:
        ChangeEquipDialog scdd = new ChangeEquipDialog(this, true, Command.OPERATE_EQUIP);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_changeEquipButtonActionPerformed

    private void changeEnemyPowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeEnemyPowerButtonActionPerformed
        // TODO add your handling code here:
        ChangeEnemyPowerDialog scdd = new ChangeEnemyPowerDialog(this, true, Command.OPERATE_ENEMY_POWER);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_changeEnemyPowerButtonActionPerformed

    private void enemyTransButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enemyTransButtonActionPerformed
        // TODO add your handling code here:
        ChangeEnemyModelDialog scdd = new ChangeEnemyModelDialog(this, true, Command.CHANGE_ENEMY_MODEL);
        scdd.setVisible(true);
        addCommand(scdd.getCommand());
    }//GEN-LAST:event_enemyTransButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton battleButton;
    private javax.swing.JButton breakButton;
    private javax.swing.JButton cancleButton;
    private javax.swing.JButton changeEnemyPowerButton;
    private javax.swing.JButton changeEquipButton;
    private javax.swing.JButton changeImageARGBButton;
    private javax.swing.JButton changeModalButton;
    private javax.swing.JButton changeNameButton;
    private javax.swing.JButton changeScreenColorButton;
    private javax.swing.JButton changeSkinButton;
    private javax.swing.JButton endBattleButton;
    private javax.swing.JButton enemyTransButton;
    private javax.swing.JButton equipButton;
    private javax.swing.JButton exitScriptButton;
    private javax.swing.JButton faceButton;
    private javax.swing.JButton gameSaveButton;
    private javax.swing.JButton ifButton;
    private javax.swing.JButton itemButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton mapButton;
    private javax.swing.JButton moneyButton;
    private javax.swing.JButton moveButton;
    private javax.swing.JButton moveImageButton;
    private javax.swing.JButton openShopButton;
    private javax.swing.JButton playMusicButton;
    private javax.swing.JButton powButton;
    private javax.swing.JButton publicEventButton;
    private javax.swing.JButton removeImageButton;
    private javax.swing.JButton rotateImageButton;
    private javax.swing.JTabbedPane scriptTabbedPane;
    private javax.swing.JButton shakeScreenButton;
    private javax.swing.JButton showAniButton;
    private javax.swing.JButton showChooseButton;
    private javax.swing.JButton showCountDownButton;
    private javax.swing.JButton showImageButton;
    private javax.swing.JButton showInputButton;
    private javax.swing.JButton showMessageButton;
    private javax.swing.JButton skillButton;
    private javax.swing.JButton stopMusicButton;
    private javax.swing.JButton switchButton;
    private javax.swing.JButton systemMenuButton;
    private javax.swing.JButton varButton;
    private javax.swing.JButton waitButton;
    private javax.swing.JButton whileButton;
    // End of variables declaration//GEN-END:variables
}
