/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditEnemyTroopDialog.java
 *
 * Created on 2011-9-30, 22:15:43
 */
package com.soyomaker.data.ui;

import com.soyomaker.AppData;
import com.soyomaker.data.model.Enemy;
import com.soyomaker.data.model.EnemyTroop;
import com.soyomaker.data.model.Model;
import javax.swing.DefaultListModel;

/**
 *
 * @author Administrator
 */
public class EditEnemyTroopDialog extends javax.swing.JDialog {

    /** Creates new form EditEnemyTroopDialog
     * @param parent
     * @param enemyTroop
     * @param modal
     */
    public EditEnemyTroopDialog(EnemyTroopPanel parent, boolean modal, EnemyTroop enemyTroop) {
        setModal(modal);
        initComponents();
        setLocationRelativeTo(null);
        setEnemyTroop(enemyTroop);
    }
    private EnemyTroop enemyTroop;

    private void setEnemyTroop(EnemyTroop enemyTroop) {
        this.enemyTroop = enemyTroop;
        troopNameTextField.setText(enemyTroop.name);
        DefaultListModel allEnemylistModel = new DefaultListModel();
        for (int i = 0; i < AppData.getInstance().getCurProject().getDataManager().size(Model.ENEMY); i++) {
            allEnemylistModel.addElement(((Enemy) AppData.getInstance().getCurProject().getDataManager().getModels(Model.ENEMY)[i]));
        }
        allEnemyList.setModel(allEnemylistModel);
        DefaultListModel troopEnemylistModel = new DefaultListModel();
        for (int i = 0; i < enemyTroop.enemys.size(); i++) {
            troopEnemylistModel.addElement(enemyTroop.enemys.get(i));
        }
        troopEnemyList.setModel(troopEnemylistModel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        troopNameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        troopEnemyList = new javax.swing.JList();
        addEnemyButton = new javax.swing.JButton();
        removeEnemyButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        allEnemyList = new javax.swing.JList();
        autoTroopNameButton = new javax.swing.JButton();
        clearEnemyButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("编辑敌人队伍"); // NOI18N
        setResizable(false);

        jLabel1.setText("名称");
        jLabel1.setName("jLabel1"); // NOI18N

        troopNameTextField.setName("troopNameTextField"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        troopEnemyList.setName("troopEnemyList"); // NOI18N
        jScrollPane1.setViewportView(troopEnemyList);

        addEnemyButton.setText("< 添加");
        addEnemyButton.setName("addEnemyButton"); // NOI18N
        addEnemyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnemyButtonActionPerformed(evt);
            }
        });

        removeEnemyButton.setText("删除 >");
        removeEnemyButton.setName("removeEnemyButton"); // NOI18N
        removeEnemyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEnemyButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        allEnemyList.setName("allEnemyList"); // NOI18N
        jScrollPane2.setViewportView(allEnemyList);

        autoTroopNameButton.setText("自动生成名称");
        autoTroopNameButton.setName("autoTroopNameButton"); // NOI18N
        autoTroopNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoTroopNameButtonActionPerformed(evt);
            }
        });

        clearEnemyButton.setText("清空");
        clearEnemyButton.setName("clearEnemyButton"); // NOI18N
        clearEnemyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEnemyButtonActionPerformed(evt);
            }
        });

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        closeButton.setText("关闭");
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clearEnemyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeEnemyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addEnemyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(troopNameTextField)
                        .addGap(18, 18, 18)
                        .addComponent(autoTroopNameButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(troopNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autoTroopNameButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(okButton)
                            .addComponent(closeButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(addEnemyButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeEnemyButton)
                        .addGap(18, 18, 18)
                        .addComponent(clearEnemyButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        enemyTroop.enemys.clear();
        enemyTroop.name = troopNameTextField.getText();
        for (int i = 0; i < ((DefaultListModel) troopEnemyList.getModel()).size(); i++) {
            enemyTroop.enemys.add((Enemy) ((DefaultListModel) troopEnemyList.getModel()).elementAt(i));
        }
        dispose();
}//GEN-LAST:event_okButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_closeButtonActionPerformed

    private void addEnemyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnemyButtonActionPerformed
        // TODO add your handling code here:
        if (allEnemyList.getSelectedIndex() != -1) {
            ((DefaultListModel) troopEnemyList.getModel()).addElement((Enemy) allEnemyList.getSelectedValue());
        }
        troopEnemyList.updateUI();
    }//GEN-LAST:event_addEnemyButtonActionPerformed

    private void removeEnemyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEnemyButtonActionPerformed
        // TODO add your handling code here:
        if (troopEnemyList.getSelectedIndex() != -1) {
            ((DefaultListModel) troopEnemyList.getModel()).removeElement((Enemy) troopEnemyList.getSelectedValue());
        }
        troopEnemyList.updateUI();
    }//GEN-LAST:event_removeEnemyButtonActionPerformed

    private void clearEnemyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEnemyButtonActionPerformed
        // TODO add your handling code here:
        ((DefaultListModel) troopEnemyList.getModel()).removeAllElements();
        troopEnemyList.updateUI();
    }//GEN-LAST:event_clearEnemyButtonActionPerformed

    private void autoTroopNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoTroopNameButtonActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < troopEnemyList.getModel().getSize(); i++) {
            if (i == troopEnemyList.getModel().getSize() - 1) {
                sb.append(((Enemy) troopEnemyList.getModel().getElementAt(i)).name);
            } else {
                sb.append(((Enemy) troopEnemyList.getModel().getElementAt(i)).name).append(",");
            }
        }
        troopNameTextField.setText(sb.toString());
    }//GEN-LAST:event_autoTroopNameButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEnemyButton;
    private javax.swing.JList allEnemyList;
    private javax.swing.JButton autoTroopNameButton;
    private javax.swing.JButton clearEnemyButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okButton;
    private javax.swing.JButton removeEnemyButton;
    private javax.swing.JList troopEnemyList;
    private javax.swing.JTextField troopNameTextField;
    // End of variables declaration//GEN-END:variables
}
