/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditEnemyDialog.java
 *
 * Created on 2011-9-30, 22:15:26
 */
package com.soyomaker.data.ui;

import com.soyomaker.data.model.Enemy;
import com.soyomaker.data.model.ModelActionTableModel;
import com.soyomaker.data.model.ModelAttributeTableModel;
import com.soyomaker.data.model.ModelEquipTableModel;
import com.soyomaker.data.model.ModelStatusTableModel;
import com.soyomaker.data.model.ModelTreasureTableModel;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class EditEnemyDialog extends javax.swing.JDialog {

    /** Creates new form EditEnemyDialog
     * @param parent
     * @param enemy
     * @param modal
     */
    public EditEnemyDialog(EnemyPanel parent, boolean modal, Enemy enemy) {
        setModal(modal);
        metm = new ModelEquipTableModel(enemy.equips);
        mttm = new ModelTreasureTableModel(enemy.treasures);
        matm = new ModelAttributeTableModel(enemy.attributes);
        mstm = new ModelStatusTableModel(enemy.status);
        mactm = new ModelActionTableModel(enemy.actions);
        initComponents();
        setLocationRelativeTo(null);

//        TableColumnModel tcm2 = equipTable.getColumnModel();
//        TableColumn iconC2 = tcm2.getColumn(0);
//        JTabelComboBoxRender strI2 = new JTabelComboBoxRender((Equip[]) AppData.getInstance().getCurProject().getDataManager().getModels(Model.EQUIP));
//        JTableComboBoxEditor steI2 = new JTableComboBoxEditor((Equip[]) AppData.getInstance().getCurProject().getDataManager().getModels(Model.EQUIP));
//        iconC2.setCellRenderer(strI2);
//        iconC2.setCellEditor(steI2);

//        TableColumnModel tcm3 = attributeTable.getColumnModel();
//        TableColumn iconC3 = tcm3.getColumn(0);
//        ArrayList<Attribute> attrs3 = ((Config) AppData.getInstance().getCurProject().getDataManager().getModels(Model.CONFIG)[0]).system.attributes;
//        String[] ats3 = new String[attrs3.size()];
//        for (int i = 0; i < attrs3.size(); i++) {
//            ats3[i] = attrs3.get(i).name;
//        }
//        JTabelComboBoxRender strI3 = new JTabelComboBoxRender(ats3);
//        JTableComboBoxEditor steI3 = new JTableComboBoxEditor(ats3);
//        iconC3.setCellRenderer(strI3);
//        iconC3.setCellEditor(steI3);

//        TableColumnModel tcm4 = statusTable.getColumnModel();
//        TableColumn iconC4 = tcm4.getColumn(0);
//        JTabelComboBoxRender strI4 = new JTabelComboBoxRender((Status[]) AppData.getInstance().getCurProject().getDataManager().getModels(Model.STATUS));
//        JTableComboBoxEditor steI4 = new JTableComboBoxEditor((Status[]) AppData.getInstance().getCurProject().getDataManager().getModels(Model.STATUS));
//        iconC4.setCellRenderer(strI4);
//        iconC4.setCellEditor(steI4);
        setEnemy(enemy);
    }
    private Enemy enemy;
    private ModelTreasureTableModel mttm;
    private ModelEquipTableModel metm;
    private ModelAttributeTableModel matm;
    private ModelStatusTableModel mstm;
    private ModelActionTableModel mactm;

    private void setEnemy(Enemy enemy) {
        this.enemy = enemy;
        enemyNameTextField.setText(enemy.name);
        enemyIntroTextArea.setText(enemy.intro);
        enemyLevTextField.setText("" + enemy.lev);
        enemyMaxHpTextField.setText("" + enemy.maxHp);
        enemyMaxSpTextField.setText("" + enemy.maxSp);
        enemyBodyTextField.setText("" + enemy.body);
        enemyStreTextField.setText("" + enemy.stre);
        enemyInteTextField.setText("" + enemy.inte);
        enemyAgilTextField.setText("" + enemy.agil);
        enemyDexTextField.setText("" + enemy.dex);
        enemyLuckTextField.setText("" + enemy.luck);
        enemyExpTextField.setText("" + enemy.exp);
        enemyMoneyTextField.setText("" + enemy.money);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enemyNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enemyIntroTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        enemyLevTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        enemyMaxHpTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        enemyMaxSpTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        enemyStreTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        enemyInteTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        enemyAgilTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        enemyDexTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        enemyLuckTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        enemyExpTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        enemyMoneyTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        actionTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        statusTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        treasureTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        attributeTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        equipTable = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        addEquipButton = new javax.swing.JButton();
        removeEquipButton = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        addTreasureButton = new javax.swing.JButton();
        removeTreasureButton = new javax.swing.JButton();
        jToolBar4 = new javax.swing.JToolBar();
        addActionButton = new javax.swing.JButton();
        removeActionButton = new javax.swing.JButton();
        jToolBar5 = new javax.swing.JToolBar();
        addAttributeButton = new javax.swing.JButton();
        removeAttributeButton = new javax.swing.JButton();
        jToolBar6 = new javax.swing.JToolBar();
        addStausButton = new javax.swing.JButton();
        removeStatusButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        chooseEnemyBattleImgButton = new javax.swing.JButton();
        enemyBattleImgPanel = new javax.swing.JPanel(){
            public void paint(Graphics g){
                g.setColor(new Color(255,153,153));
                g.fillRect(0, 0, this.getWidth(), this.getHeight());
                Image img;
                if(enemy.battleImg.equals("")){
                    return;
                }
                try{
                    img = ImageIO.read(new File(com.soyomaker.AppData.getInstance().getCurProject().getPath()
                        +File.separator+"image"+File.separator+"battler"+File.separator+
                        enemy.battleImg));
                g.drawImage(img, this.getWidth()/2-img.getWidth(null)/2,
                    this.getHeight()/2-img.getHeight(null)/2, null);
            }catch(IOException e){
            }
        }
    };
    jLabel13 = new javax.swing.JLabel();
    enemyBodyTextField = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(EditEnemyDialog.class);
    setTitle(resourceMap.getString("title")); // NOI18N
    setResizable(false);

    jLabel1.setText("名称");
    jLabel1.setName("jLabel1"); // NOI18N

    enemyNameTextField.setName("enemyNameTextField"); // NOI18N

    jLabel2.setText("说明");
    jLabel2.setName("jLabel2"); // NOI18N

    jScrollPane1.setName("jScrollPane1"); // NOI18N

    enemyIntroTextArea.setColumns(20);
    enemyIntroTextArea.setLineWrap(true);
    enemyIntroTextArea.setRows(5);
    enemyIntroTextArea.setName("enemyIntroTextArea"); // NOI18N
    jScrollPane1.setViewportView(enemyIntroTextArea);

    jLabel3.setText("等级");
    jLabel3.setName("jLabel3"); // NOI18N

    enemyLevTextField.setName("enemyLevTextField"); // NOI18N

    jLabel4.setText("MaxHp");
    jLabel4.setName("jLabel4"); // NOI18N

    enemyMaxHpTextField.setName("enemyMaxHpTextField"); // NOI18N

    jLabel5.setText("MaxSp");
    jLabel5.setName("jLabel5"); // NOI18N

    enemyMaxSpTextField.setName("enemyMaxSpTextField"); // NOI18N

    jLabel6.setText("力量");
    jLabel6.setName("jLabel6"); // NOI18N

    enemyStreTextField.setName("enemyStreTextField"); // NOI18N

    jLabel7.setText("智力");
    jLabel7.setName("jLabel7"); // NOI18N

    enemyInteTextField.setName("enemyInteTextField"); // NOI18N

    jLabel8.setText("敏捷");
    jLabel8.setName("jLabel8"); // NOI18N

    enemyAgilTextField.setName("enemyAgilTextField"); // NOI18N

    jLabel9.setText("灵巧");
    jLabel9.setName("jLabel9"); // NOI18N

    enemyDexTextField.setName("enemyDexTextField"); // NOI18N

    jLabel10.setText("幸运");
    jLabel10.setName("jLabel10"); // NOI18N

    enemyLuckTextField.setName("enemyLuckTextField"); // NOI18N

    jLabel11.setText("经验");
    jLabel11.setName("jLabel11"); // NOI18N

    enemyExpTextField.setName("enemyExpTextField"); // NOI18N

    jLabel12.setText("金钱");
    jLabel12.setName("jLabel12"); // NOI18N

    enemyMoneyTextField.setName("enemyMoneyTextField"); // NOI18N

    jPanel3.setName("jPanel3"); // NOI18N

    jScrollPane2.setName("jScrollPane2"); // NOI18N

    actionTable.setModel(mactm);
    actionTable.setName("actionTable"); // NOI18N
    actionTable.setRowHeight(20);
    jScrollPane2.setViewportView(actionTable);

    jScrollPane3.setName("jScrollPane3"); // NOI18N

    statusTable.setModel(mstm);
    statusTable.setName("statusTable"); // NOI18N
    statusTable.setRowHeight(20);
    jScrollPane3.setViewportView(statusTable);

    jScrollPane4.setName("jScrollPane4"); // NOI18N

    treasureTable.setModel(mttm);
    treasureTable.setName("treasureTable"); // NOI18N
    treasureTable.setRowHeight(20);
    jScrollPane4.setViewportView(treasureTable);

    jScrollPane5.setName("jScrollPane5"); // NOI18N

    attributeTable.setModel(matm);
    attributeTable.setName("attributeTable"); // NOI18N
    attributeTable.setRowHeight(20);
    jScrollPane5.setViewportView(attributeTable);

    jScrollPane6.setName("jScrollPane6"); // NOI18N

    equipTable.setModel(metm);
    equipTable.setName("equipTable"); // NOI18N
    equipTable.setRowHeight(20);
    jScrollPane6.setViewportView(equipTable);

    jToolBar2.setFloatable(false);
    jToolBar2.setRollover(true);
    jToolBar2.setName("jToolBar2"); // NOI18N

    addEquipButton.setText("添加装备");
    addEquipButton.setFocusable(false);
    addEquipButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    addEquipButton.setName("addEquipButton"); // NOI18N
    addEquipButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    addEquipButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addEquipButtonActionPerformed(evt);
        }
    });
    jToolBar2.add(addEquipButton);

    removeEquipButton.setText("删除装备");
    removeEquipButton.setFocusable(false);
    removeEquipButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    removeEquipButton.setName("removeEquipButton"); // NOI18N
    removeEquipButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    removeEquipButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            removeEquipButtonActionPerformed(evt);
        }
    });
    jToolBar2.add(removeEquipButton);

    jToolBar3.setFloatable(false);
    jToolBar3.setRollover(true);
    jToolBar3.setName("jToolBar3"); // NOI18N

    addTreasureButton.setText("添加宝物");
    addTreasureButton.setFocusable(false);
    addTreasureButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    addTreasureButton.setName("addTreasureButton"); // NOI18N
    addTreasureButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    addTreasureButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addTreasureButtonActionPerformed(evt);
        }
    });
    jToolBar3.add(addTreasureButton);

    removeTreasureButton.setText("删除宝物");
    removeTreasureButton.setFocusable(false);
    removeTreasureButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    removeTreasureButton.setName("removeTreasureButton"); // NOI18N
    removeTreasureButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    removeTreasureButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            removeTreasureButtonActionPerformed(evt);
        }
    });
    jToolBar3.add(removeTreasureButton);

    jToolBar4.setFloatable(false);
    jToolBar4.setRollover(true);
    jToolBar4.setName("jToolBar4"); // NOI18N

    addActionButton.setText("添加动作");
    addActionButton.setFocusable(false);
    addActionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    addActionButton.setName("addActionButton"); // NOI18N
    addActionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    addActionButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addActionButtonActionPerformed(evt);
        }
    });
    jToolBar4.add(addActionButton);

    removeActionButton.setText("删除动作");
    removeActionButton.setFocusable(false);
    removeActionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    removeActionButton.setName("removeActionButton"); // NOI18N
    removeActionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    removeActionButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            removeActionButtonActionPerformed(evt);
        }
    });
    jToolBar4.add(removeActionButton);

    jToolBar5.setFloatable(false);
    jToolBar5.setRollover(true);
    jToolBar5.setName("jToolBar5"); // NOI18N

    addAttributeButton.setText("添加属性");
    addAttributeButton.setFocusable(false);
    addAttributeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    addAttributeButton.setName("addAttributeButton"); // NOI18N
    addAttributeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    addAttributeButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addAttributeButtonActionPerformed(evt);
        }
    });
    jToolBar5.add(addAttributeButton);

    removeAttributeButton.setText("删除属性");
    removeAttributeButton.setFocusable(false);
    removeAttributeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    removeAttributeButton.setName("removeAttributeButton"); // NOI18N
    removeAttributeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    removeAttributeButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            removeAttributeButtonActionPerformed(evt);
        }
    });
    jToolBar5.add(removeAttributeButton);

    jToolBar6.setFloatable(false);
    jToolBar6.setRollover(true);
    jToolBar6.setName("jToolBar6"); // NOI18N

    addStausButton.setText("添加状态");
    addStausButton.setFocusable(false);
    addStausButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    addStausButton.setName("addStausButton"); // NOI18N
    addStausButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    addStausButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addStausButtonActionPerformed(evt);
        }
    });
    jToolBar6.add(addStausButton);

    removeStatusButton.setText("删除状态");
    removeStatusButton.setFocusable(false);
    removeStatusButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    removeStatusButton.setName("removeStatusButton"); // NOI18N
    removeStatusButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    removeStatusButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            removeStatusButtonActionPerformed(evt);
        }
    });
    jToolBar6.add(removeStatusButton);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jToolBar6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
    );

    jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane2, jScrollPane3, jScrollPane4, jScrollPane5, jScrollPane6, jToolBar2, jToolBar3, jToolBar4, jToolBar5, jToolBar6});

    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jToolBar6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jToolBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addComponent(jScrollPane5, 0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE)))
    );

    okButton.setText("确定");
    okButton.setName("okButton"); // NOI18N
    okButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            okButtonActionPerformed(evt);
        }
    });

    closeButton.setText("关闭");
    closeButton.setName("closeButton"); // NOI18N
    closeButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            closeButtonActionPerformed(evt);
        }
    });

    jPanel1.setName("jPanel1"); // NOI18N

    jToolBar1.setFloatable(false);
    jToolBar1.setOrientation(javax.swing.JToolBar.VERTICAL);
    jToolBar1.setRollover(true);
    jToolBar1.setName("jToolBar1"); // NOI18N

    chooseEnemyBattleImgButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soyomaker/resources/menu_open.PNG"))); // NOI18N
    chooseEnemyBattleImgButton.setFocusable(false);
    chooseEnemyBattleImgButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    chooseEnemyBattleImgButton.setName("chooseEnemyBattleImgButton"); // NOI18N
    chooseEnemyBattleImgButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    chooseEnemyBattleImgButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            chooseEnemyBattleImgButtonActionPerformed(evt);
        }
    });
    jToolBar1.add(chooseEnemyBattleImgButton);

    enemyBattleImgPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    enemyBattleImgPanel.setName("enemyBattleImgPanel"); // NOI18N

    javax.swing.GroupLayout enemyBattleImgPanelLayout = new javax.swing.GroupLayout(enemyBattleImgPanel);
    enemyBattleImgPanel.setLayout(enemyBattleImgPanelLayout);
    enemyBattleImgPanelLayout.setHorizontalGroup(
        enemyBattleImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 171, Short.MAX_VALUE)
    );
    enemyBattleImgPanelLayout.setVerticalGroup(
        enemyBattleImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 115, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(enemyBattleImgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        .addComponent(enemyBattleImgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    jLabel13.setText("体力");
    jLabel13.setName("jLabel13"); // NOI18N

    enemyBodyTextField.setName("enemyBodyTextField"); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(enemyNameTextField))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(enemyLevTextField))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel13)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(enemyInteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enemyStreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(enemyMaxHpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enemyMaxSpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enemyBodyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(enemyMoneyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enemyExpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enemyLuckTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enemyDexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(enemyAgilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(326, 326, 326))))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {enemyAgilTextField, enemyBodyTextField, enemyDexTextField, enemyExpTextField, enemyInteTextField, enemyLuckTextField, enemyMaxHpTextField, enemyMaxSpTextField, enemyMoneyTextField, enemyStreTextField});

    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(enemyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(enemyLevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(enemyDexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(enemyLuckTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(enemyExpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(enemyAgilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enemyMoneyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(enemyMaxSpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addComponent(enemyMaxHpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enemyBodyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enemyStreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enemyInteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(closeButton)
                .addComponent(okButton))
            .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {enemyAgilTextField, enemyBodyTextField, enemyDexTextField, enemyExpTextField, enemyInteTextField, enemyLuckTextField, enemyMaxHpTextField, enemyMaxSpTextField, enemyMoneyTextField, enemyStreTextField});

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        enemy.name = enemyNameTextField.getText();
        enemy.intro = enemyIntroTextArea.getText();
        enemy.lev = Integer.parseInt(enemyLevTextField.getText());
        enemy.maxHp = Integer.parseInt(enemyMaxHpTextField.getText());
        enemy.maxSp = Integer.parseInt(enemyMaxSpTextField.getText());
        enemy.body = Integer.parseInt(enemyBodyTextField.getText());
        enemy.stre = Integer.parseInt(enemyStreTextField.getText());
        enemy.inte = Integer.parseInt(enemyInteTextField.getText());
        enemy.agil = Integer.parseInt(enemyAgilTextField.getText());
        enemy.dex = Integer.parseInt(enemyDexTextField.getText());
        enemy.luck = Integer.parseInt(enemyLuckTextField.getText());
        enemy.exp = Integer.parseInt(enemyExpTextField.getText());
        enemy.money = Integer.parseInt(enemyMoneyTextField.getText());
        dispose();
}//GEN-LAST:event_okButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_closeButtonActionPerformed

    private void chooseEnemyBattleImgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseEnemyBattleImgButtonActionPerformed
        // TODO add your handling code here:
        ChooseImageDialog ebd = new ChooseImageDialog(this, true, "image" + File.separator + "battler");
        ebd.setVisible(true);
        if (!ebd.getSelectedImage().equals("")) {
            enemy.battleImg = ebd.getSelectedImage();
            enemyBattleImgPanel.updateUI();
        }
    }//GEN-LAST:event_chooseEnemyBattleImgButtonActionPerformed

    private void addAttributeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAttributeButtonActionPerformed
        // TODO add your handling code here:
        AddModelAttributeDialog etd = new AddModelAttributeDialog(this, true);
        etd.setVisible(true);
        if (etd.getSelectAttribute() != null) {
            enemy.attributes.add(etd.getSelectAttribute());
            attributeTable.updateUI();
        }
    }//GEN-LAST:event_addAttributeButtonActionPerformed

    private void addStausButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStausButtonActionPerformed
        // TODO add your handling code here:
        AddModelStatusDialog etd = new AddModelStatusDialog(this, true);
        etd.setVisible(true);
        if (etd.getSelectStatus() != null) {
            enemy.status.add(etd.getSelectStatus());
            statusTable.updateUI();
        }
    }//GEN-LAST:event_addStausButtonActionPerformed

    private void removeAttributeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAttributeButtonActionPerformed
        // TODO add your handling code here:
        if (attributeTable.getSelectedRow() >= 0 && attributeTable.getSelectedRow() < enemy.attributes.size()) {
            enemy.attributes.remove(attributeTable.getSelectedRow());
        }
        attributeTable.updateUI();
    }//GEN-LAST:event_removeAttributeButtonActionPerformed

    private void removeStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStatusButtonActionPerformed
        // TODO add your handling code here:
        if (statusTable.getSelectedRow() >= 0 && statusTable.getSelectedRow() < enemy.status.size()) {
            enemy.status.remove(statusTable.getSelectedRow());
        }
        statusTable.updateUI();
    }//GEN-LAST:event_removeStatusButtonActionPerformed

    private void addEquipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEquipButtonActionPerformed
        // TODO add your handling code here:
        AddModelEquipDialog etd = new AddModelEquipDialog(this, true);
        etd.setVisible(true);
        if (etd.getSelectEquip() != null) {
            for (int i = 0; i < enemy.equips.size(); i++) {
                if (enemy.equips.get(i).equipType == etd.getSelectEquip().equipType) {
                    JOptionPane.showMessageDialog(this,
                            "同类型装备只能装备一个！");
                    return;
                }
            }
            enemy.equips.add(etd.getSelectEquip());
            equipTable.updateUI();
        }
    }//GEN-LAST:event_addEquipButtonActionPerformed

    private void removeEquipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEquipButtonActionPerformed
        // TODO add your handling code here:
        if (equipTable.getSelectedRow() >= 0 && equipTable.getSelectedRow() < enemy.equips.size()) {
            enemy.equips.remove(equipTable.getSelectedRow());
        }
        equipTable.updateUI();
    }//GEN-LAST:event_removeEquipButtonActionPerformed

    private void addTreasureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTreasureButtonActionPerformed
        // TODO add your handling code here:
        AddModelTreasureDialog etd = new AddModelTreasureDialog(this, true);
        etd.setVisible(true);
        if (etd.getSelectTreasure() != null) {
            enemy.treasures.add(etd.getSelectTreasure());
            treasureTable.updateUI();
        }
    }//GEN-LAST:event_addTreasureButtonActionPerformed

    private void removeTreasureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTreasureButtonActionPerformed
        // TODO add your handling code here:
        if (treasureTable.getSelectedRow() >= 0 && treasureTable.getSelectedRow() < enemy.treasures.size()) {
            enemy.treasures.remove(treasureTable.getSelectedRow());
        }
        treasureTable.updateUI();
    }//GEN-LAST:event_removeTreasureButtonActionPerformed

    private void addActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionButtonActionPerformed
        // TODO add your handling code here:
        AddModelActionDialog etd = new AddModelActionDialog(this, true);
        etd.setVisible(true);
        if (etd.getSelectAction() != null) {
            enemy.actions.add(etd.getSelectAction());
            actionTable.updateUI();
        }
    }//GEN-LAST:event_addActionButtonActionPerformed

    private void removeActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionButtonActionPerformed
        // TODO add your handling code here:
        if (actionTable.getSelectedRow() >= 0 && actionTable.getSelectedRow() < enemy.actions.size()) {
            enemy.actions.remove(actionTable.getSelectedRow());
        }
        actionTable.updateUI();
    }//GEN-LAST:event_removeActionButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable actionTable;
    private javax.swing.JButton addActionButton;
    private javax.swing.JButton addAttributeButton;
    private javax.swing.JButton addEquipButton;
    private javax.swing.JButton addStausButton;
    private javax.swing.JButton addTreasureButton;
    private javax.swing.JTable attributeTable;
    private javax.swing.JButton chooseEnemyBattleImgButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField enemyAgilTextField;
    public javax.swing.JPanel enemyBattleImgPanel;
    private javax.swing.JTextField enemyBodyTextField;
    private javax.swing.JTextField enemyDexTextField;
    private javax.swing.JTextField enemyExpTextField;
    private javax.swing.JTextField enemyInteTextField;
    private javax.swing.JTextArea enemyIntroTextArea;
    private javax.swing.JTextField enemyLevTextField;
    private javax.swing.JTextField enemyLuckTextField;
    private javax.swing.JTextField enemyMaxHpTextField;
    private javax.swing.JTextField enemyMaxSpTextField;
    private javax.swing.JTextField enemyMoneyTextField;
    private javax.swing.JTextField enemyNameTextField;
    private javax.swing.JTextField enemyStreTextField;
    private javax.swing.JTable equipTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JToolBar jToolBar6;
    private javax.swing.JButton okButton;
    private javax.swing.JButton removeActionButton;
    private javax.swing.JButton removeAttributeButton;
    private javax.swing.JButton removeEquipButton;
    private javax.swing.JButton removeStatusButton;
    private javax.swing.JButton removeTreasureButton;
    private javax.swing.JTable statusTable;
    private javax.swing.JTable treasureTable;
    // End of variables declaration//GEN-END:variables
}
