/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SpriteEditorDialog.java
 *
 * Created on 2011-6-1, 23:44:17
 */
package com.soyomaker.dialog;

import com.soyomaker.listener.ProjectChangeListener;
import com.soyomaker.listener.ProjectChangedEvent;
import com.soyomaker.tablemodel.ActionTableModel;
import com.soyomaker.tablemodel.AnimationTableModel;
import com.soyomaker.tablemodel.FrameTableModel;
import com.soyomaker.model.animation.Animation;
import com.soyomaker.model.animation.Frame;
import com.soyomaker.model.animation.Picture;
import com.soyomaker.model.map.Map;
import com.soyomaker.model.map.Npc;
import com.soyomaker.model.map.ScriptFile;
import com.soyomaker.AppData;
import com.soyomaker.model.animation.Clip;
import com.soyomaker.widget.JAccordionPane;
import com.soyomaker.widget.HandlePicturePane;
import com.soyomaker.widget.JFileChooserImagePreview;
import com.soyomaker.widget.JSnapTipTabbedPane;
import com.soyomaker.widget.ChoosePicturePane;
import com.soyomaker.widget.HandleFramePane;
import com.soyomaker.widget.ShowPicturePane;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DragSource;
import java.awt.dnd.DropTarget;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Administrator
 */
public class SpriteEditorDialog extends javax.swing.JDialog implements ProjectChangeListener {

    /** Creates new form SpriteEditorDialog
     * @param parent 
     * @param modal 
     */
    public SpriteEditorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initialize();
        AppData.getInstance().getCurProject().addProjectChangeListener(this);
        JScrollPane scrollPane = new JScrollPane(aspp,
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        tabbedPane.add("元件库", scrollPane);
    }
    private JAccordionPane aspp = new JAccordionPane();
    private HashMap<Picture, HandlePicturePane> handlePicturePanes = new HashMap<Picture, HandlePicturePane>();
    private HashMap<Picture, JScrollPane> showPictureScrollPanes = new HashMap<Picture, JScrollPane>();

    private void initialize() {
        setLocationRelativeTo(null);
    }

    /**
     *
     */
    public void removeProjectChangeListener() {
        AppData.getInstance().getCurProject().removeProjectChangeListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spriteTabbedPane = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jSplitPane5 = new javax.swing.JSplitPane();
        jPanel8 = new javax.swing.JPanel();
        jToolBar6 = new javax.swing.JToolBar();
        zoomInPictureButton = new javax.swing.JButton();
        zoomOutPictureButton = new javax.swing.JButton();
        normalPictureButton = new javax.swing.JButton();
        handlePictureScrollPane = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        addImageButton = new javax.swing.JButton();
        removeImageButton = new javax.swing.JButton();
        showPictureScrollPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane6 = new javax.swing.JSplitPane();
        jSplitPane7 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        newAniButton = new javax.swing.JButton();
        removeAniButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        aniTable = new javax.swing.JTable();
        jSplitPane8 = new javax.swing.JSplitPane();
        jPanel11 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        addFrameButton = new javax.swing.JButton();
        removeFrameButton = new javax.swing.JButton();
        cloneFrameButton = new javax.swing.JButton();
        upFrameButton = new javax.swing.JButton();
        downFrameButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        frameTable = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jToolBar4 = new javax.swing.JToolBar();
        addActionButton = new javax.swing.JButton();
        removeActionButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        actionTable = new javax.swing.JTable();
        jSplitPane9 = new javax.swing.JSplitPane();
        jPanel9 = new javax.swing.JPanel();
        jToolBar5 = new javax.swing.JToolBar();
        playAnimationButton = new javax.swing.JButton();
        loopCheckBox = new javax.swing.JCheckBox();
        zoomInFrameButton = new javax.swing.JButton();
        zoomOutFrameButton = new javax.swing.JButton();
        normalFrameButton = new javax.swing.JButton();
        alphaSlider = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        handleFramePane = new com.soyomaker.widget.HandleFramePane();
        jToolBar7 = new javax.swing.JToolBar();
        outButton = new javax.swing.JButton();
        inButton = new javax.swing.JButton();
        flipHorizontalButton = new javax.swing.JButton();
        flipVerticalButton = new javax.swing.JButton();
        rightRoate90Button = new javax.swing.JButton();
        leftRoate90Button = new javax.swing.JButton();
        jToolBar8 = new javax.swing.JToolBar();
        centerAlignButton = new javax.swing.JButton();
        rightAlignButton = new javax.swing.JButton();
        leftAlignButton = new javax.swing.JButton();
        downAlignButton = new javax.swing.JButton();
        upAlignButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabbedPane = new JSnapTipTabbedPane();
        bottomLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(SpriteEditorDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N

        spriteTabbedPane.setName("spriteTabbedPane"); // NOI18N
        spriteTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spriteTabbedPaneStateChanged(evt);
            }
        });

        jPanel7.setName("jPanel7"); // NOI18N

        jSplitPane5.setResizeWeight(1.0);
        jSplitPane5.setName("jSplitPane5"); // NOI18N
        jSplitPane5.setOneTouchExpandable(true);

        jPanel8.setName("jPanel8"); // NOI18N

        jToolBar6.setFloatable(false);
        jToolBar6.setRollover(true);
        jToolBar6.setName("jToolBar6"); // NOI18N

        zoomInPictureButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soyomaker/resources/menu_zoomin.png"))); // NOI18N
        zoomInPictureButton.setFocusable(false);
        zoomInPictureButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoomInPictureButton.setName("zoomInPictureButton"); // NOI18N
        zoomInPictureButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomInPictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomInPictureButtonActionPerformed(evt);
            }
        });
        jToolBar6.add(zoomInPictureButton);

        zoomOutPictureButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soyomaker/resources/menu_zoomout.png"))); // NOI18N
        zoomOutPictureButton.setFocusable(false);
        zoomOutPictureButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoomOutPictureButton.setName("zoomOutPictureButton"); // NOI18N
        zoomOutPictureButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomOutPictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomOutPictureButtonActionPerformed(evt);
            }
        });
        jToolBar6.add(zoomOutPictureButton);

        normalPictureButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soyomaker/resources/menu_return.png"))); // NOI18N
        normalPictureButton.setFocusable(false);
        normalPictureButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        normalPictureButton.setName("normalPictureButton"); // NOI18N
        normalPictureButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        normalPictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalPictureButtonActionPerformed(evt);
            }
        });
        jToolBar6.add(normalPictureButton);

        handlePictureScrollPane.setName("handlePictureScrollPane"); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar6, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
            .addComponent(handlePictureScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jToolBar6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(handlePictureScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
        );

        jSplitPane5.setLeftComponent(jPanel8);

        jPanel6.setName("jPanel6"); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        addImageButton.setText("添加素材");
        addImageButton.setFocusable(false);
        addImageButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addImageButton.setName("addImageButton"); // NOI18N
        addImageButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(addImageButton);

        removeImageButton.setText("删除素材");
        removeImageButton.setFocusable(false);
        removeImageButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeImageButton.setName("removeImageButton"); // NOI18N
        removeImageButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeImageButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(removeImageButton);

        showPictureScrollPane.setName("showPictureScrollPane"); // NOI18N
        picturePane = new com.soyomaker.widget.ChoosePicturePane(this);
        showPictureScrollPane.setViewportView(picturePane);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showPictureScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPictureScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
        );

        jSplitPane5.setRightComponent(jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        spriteTabbedPane.addTab("素材编辑窗口", jPanel7);

        jPanel1.setName("jPanel1"); // NOI18N

        jSplitPane6.setName("jSplitPane6"); // NOI18N
        jSplitPane6.setOneTouchExpandable(true);

        jSplitPane7.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane7.setResizeWeight(0.3);
        jSplitPane7.setName("jSplitPane7"); // NOI18N
        jSplitPane7.setOneTouchExpandable(true);

        jPanel4.setName("jPanel4"); // NOI18N

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setName("jToolBar2"); // NOI18N

        newAniButton.setText("新建动画");
        newAniButton.setFocusable(false);
        newAniButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newAniButton.setName("newAniButton"); // NOI18N
        newAniButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newAniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAniButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(newAniButton);

        removeAniButton.setText("删除动画");
        removeAniButton.setFocusable(false);
        removeAniButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeAniButton.setName("removeAniButton"); // NOI18N
        removeAniButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeAniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAniButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(removeAniButton);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        atm = new AnimationTableModel();
        aniTable.setModel(atm);
        aniTable.setName("aniTable"); // NOI18N
        aniTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        DefaultTableCellRenderer aniRender = new DefaultTableCellRenderer();
        aniRender.setHorizontalAlignment(SwingConstants.CENTER);
        for(int i = 0;i < aniTable.getColumnCount();i++) {
            aniTable.getColumn(aniTable.getModel().getColumnName(i)) .setCellRenderer(aniRender);
        }
        aniTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aniTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(aniTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
        );

        jSplitPane7.setTopComponent(jPanel4);

        jSplitPane8.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane8.setResizeWeight(0.7);
        jSplitPane8.setName("jSplitPane8"); // NOI18N
        jSplitPane8.setOneTouchExpandable(true);

        jPanel11.setName("jPanel11"); // NOI18N

        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);
        jToolBar3.setName("jToolBar3"); // NOI18N

        addFrameButton.setText("添加帧");
        addFrameButton.setFocusable(false);
        addFrameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addFrameButton.setName("addFrameButton"); // NOI18N
        addFrameButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFrameButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(addFrameButton);

        removeFrameButton.setText("删除帧");
        removeFrameButton.setFocusable(false);
        removeFrameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeFrameButton.setName("removeFrameButton"); // NOI18N
        removeFrameButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFrameButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(removeFrameButton);

        cloneFrameButton.setText("克隆帧");
        cloneFrameButton.setFocusable(false);
        cloneFrameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cloneFrameButton.setName("cloneFrameButton"); // NOI18N
        cloneFrameButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cloneFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cloneFrameButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(cloneFrameButton);

        upFrameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soyomaker/resources/little_up.png"))); // NOI18N
        upFrameButton.setFocusable(false);
        upFrameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        upFrameButton.setName("upFrameButton"); // NOI18N
        upFrameButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        upFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upFrameButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(upFrameButton);

        downFrameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soyomaker/resources/little_down.png"))); // NOI18N
        downFrameButton.setFocusable(false);
        downFrameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        downFrameButton.setName("downFrameButton"); // NOI18N
        downFrameButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        downFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downFrameButtonActionPerformed(evt);
            }
        });
        jToolBar3.add(downFrameButton);

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        ftm = new FrameTableModel();
        frameTable.setModel(ftm);
        frameTable.setName("frameTable"); // NOI18N
        frameTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        DefaultTableCellRenderer frameRender = new DefaultTableCellRenderer();
        frameRender.setHorizontalAlignment(SwingConstants.CENTER);
        for(int i = 0;i < frameTable.getColumnCount();i++) {
            frameTable.getColumn(frameTable.getModel().getColumnName(i)) .setCellRenderer(frameRender);
        }
        frameTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frameTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(frameTable);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
        );

        jSplitPane8.setTopComponent(jPanel11);

        jPanel12.setName("jPanel12"); // NOI18N

        jToolBar4.setFloatable(false);
        jToolBar4.setRollover(true);
        jToolBar4.setName("jToolBar4"); // NOI18N

        addActionButton.setText("添加特效");
        addActionButton.setFocusable(false);
        addActionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addActionButton.setName("addActionButton"); // NOI18N
        addActionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionButtonActionPerformed(evt);
            }
        });
        jToolBar4.add(addActionButton);

        removeActionButton.setText("删除特效");
        removeActionButton.setFocusable(false);
        removeActionButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeActionButton.setName("removeActionButton"); // NOI18N
        removeActionButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionButtonActionPerformed(evt);
            }
        });
        jToolBar4.add(removeActionButton);

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        actm = new ActionTableModel();
        actionTable.setModel(actm);
        actionTable.setName("actionTable"); // NOI18N
        actionTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        DefaultTableCellRenderer actionRender = new DefaultTableCellRenderer();
        actionRender.setHorizontalAlignment(SwingConstants.CENTER);
        for(int i = 0;i < actionTable.getColumnCount();i++) {
            actionTable.getColumn(actionTable.getModel().getColumnName(i)) .setCellRenderer(actionRender);
        }
        actionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(actionTable);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
        );

        jSplitPane8.setRightComponent(jPanel12);

        jSplitPane7.setRightComponent(jSplitPane8);

        jSplitPane6.setLeftComponent(jSplitPane7);

        jSplitPane9.setName("jSplitPane9"); // NOI18N
        jSplitPane9.setOneTouchExpandable(true);

        jPanel9.setName("jPanel9"); // NOI18N

        jToolBar5.setFloatable(false);
        jToolBar5.setRollover(true);
        jToolBar5.setName("jToolBar5"); // NOI18N

        playAnimationButton.setText("播放");
        playAnimationButton.setFocusable(false);
        playAnimationButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playAnimationButton.setName("playAnimationButton"); // NOI18N
        playAnimationButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        playAnimationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAnimationButtonActionPerformed(evt);
            }
        });
        jToolBar5.add(playAnimationButton);

        loopCheckBox.setSelected(true);
        loopCheckBox.setText("循环");
        loopCheckBox.setFocusable(false);
        loopCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        loopCheckBox.setName("loopCheckBox"); // NOI18N
        loopCheckBox.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        loopCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loopCheckBoxActionPerformed(evt);
            }
        });
        jToolBar5.add(loopCheckBox);

        zoomInFrameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soyomaker/resources/menu_zoomin.png"))); // NOI18N
        zoomInFrameButton.setFocusable(false);
        zoomInFrameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoomInFrameButton.setName("zoomInFrameButton"); // NOI18N
        zoomInFrameButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomInFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomInFrameButtonActionPerformed(evt);
            }
        });
        jToolBar5.add(zoomInFrameButton);

        zoomOutFrameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soyomaker/resources/menu_zoomout.png"))); // NOI18N
        zoomOutFrameButton.setFocusable(false);
        zoomOutFrameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoomOutFrameButton.setName("zoomOutFrameButton"); // NOI18N
        zoomOutFrameButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomOutFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomOutFrameButtonActionPerformed(evt);
            }
        });
        jToolBar5.add(zoomOutFrameButton);

        normalFrameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soyomaker/resources/menu_return.png"))); // NOI18N
        normalFrameButton.setFocusable(false);
        normalFrameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        normalFrameButton.setName("normalFrameButton"); // NOI18N
        normalFrameButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        normalFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalFrameButtonActionPerformed(evt);
            }
        });
        jToolBar5.add(normalFrameButton);

        alphaSlider.setMaximum(255);
        alphaSlider.setValue(0);
        alphaSlider.setName("alphaSlider"); // NOI18N
        alphaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                alphaSliderStateChanged(evt);
            }
        });
        jToolBar5.add(alphaSlider);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        handleFramePane.setName("handleFramePane"); // NOI18N

        javax.swing.GroupLayout handleFramePaneLayout = new javax.swing.GroupLayout(handleFramePane);
        handleFramePane.setLayout(handleFramePaneLayout);
        handleFramePaneLayout.setHorizontalGroup(
            handleFramePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        handleFramePaneLayout.setVerticalGroup(
            handleFramePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(handleFramePane);

        jToolBar7.setFloatable(false);
        jToolBar7.setRollover(true);
        jToolBar7.setName("jToolBar7"); // NOI18N

        outButton.setText("向外");
        outButton.setFocusable(false);
        outButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        outButton.setName("outButton"); // NOI18N
        outButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        outButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outButtonActionPerformed(evt);
            }
        });
        jToolBar7.add(outButton);

        inButton.setText("向里");
        inButton.setFocusable(false);
        inButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inButton.setName("inButton"); // NOI18N
        inButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        inButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inButtonActionPerformed(evt);
            }
        });
        jToolBar7.add(inButton);

        flipHorizontalButton.setText("水平镜像");
        flipHorizontalButton.setFocusable(false);
        flipHorizontalButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        flipHorizontalButton.setName("flipHorizontalButton"); // NOI18N
        flipHorizontalButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        flipHorizontalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flipHorizontalButtonActionPerformed(evt);
            }
        });
        jToolBar7.add(flipHorizontalButton);

        flipVerticalButton.setText("垂直镜像");
        flipVerticalButton.setFocusable(false);
        flipVerticalButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        flipVerticalButton.setName("flipVerticalButton"); // NOI18N
        flipVerticalButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        flipVerticalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flipVerticalButtonActionPerformed(evt);
            }
        });
        jToolBar7.add(flipVerticalButton);

        rightRoate90Button.setText("右旋90度");
        rightRoate90Button.setToolTipText("图块右旋90度"); // NOI18N
        rightRoate90Button.setFocusable(false);
        rightRoate90Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rightRoate90Button.setName("rightRoate90Button"); // NOI18N
        rightRoate90Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rightRoate90Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightRoate90ButtonActionPerformed(evt);
            }
        });
        jToolBar7.add(rightRoate90Button);

        leftRoate90Button.setText("左旋90度");
        leftRoate90Button.setToolTipText("图块左旋90度"); // NOI18N
        leftRoate90Button.setFocusable(false);
        leftRoate90Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        leftRoate90Button.setName("leftRoate90Button"); // NOI18N
        leftRoate90Button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        leftRoate90Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftRoate90ButtonActionPerformed(evt);
            }
        });
        jToolBar7.add(leftRoate90Button);

        jToolBar8.setFloatable(false);
        jToolBar8.setRollover(true);
        jToolBar8.setName("jToolBar8"); // NOI18N

        centerAlignButton.setText("居中");
        centerAlignButton.setToolTipText("图块中心对齐中心线");
        centerAlignButton.setFocusable(false);
        centerAlignButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        centerAlignButton.setName("centerAlignButton"); // NOI18N
        centerAlignButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        centerAlignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centerAlignButtonActionPerformed(evt);
            }
        });
        jToolBar8.add(centerAlignButton);

        rightAlignButton.setText("右对齐");
        rightAlignButton.setToolTipText("图块右边对齐中心线");
        rightAlignButton.setFocusable(false);
        rightAlignButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rightAlignButton.setName("rightAlignButton"); // NOI18N
        rightAlignButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rightAlignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightAlignButtonActionPerformed(evt);
            }
        });
        jToolBar8.add(rightAlignButton);

        leftAlignButton.setText("左对齐");
        leftAlignButton.setToolTipText("图块左边对齐中心线");
        leftAlignButton.setFocusable(false);
        leftAlignButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        leftAlignButton.setName("leftAlignButton"); // NOI18N
        leftAlignButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        leftAlignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftAlignButtonActionPerformed(evt);
            }
        });
        jToolBar8.add(leftAlignButton);

        downAlignButton.setText("下对齐");
        downAlignButton.setToolTipText("图块下边对齐中心线");
        downAlignButton.setFocusable(false);
        downAlignButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        downAlignButton.setName("downAlignButton"); // NOI18N
        downAlignButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        downAlignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downAlignButtonActionPerformed(evt);
            }
        });
        jToolBar8.add(downAlignButton);

        upAlignButton.setText("上对齐");
        upAlignButton.setToolTipText("图块上边对齐中心线");
        upAlignButton.setFocusable(false);
        upAlignButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        upAlignButton.setName("upAlignButton"); // NOI18N
        upAlignButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        upAlignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upAlignButtonActionPerformed(evt);
            }
        });
        jToolBar8.add(upAlignButton);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addComponent(jToolBar7, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addComponent(jToolBar8, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jToolBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane9.setLeftComponent(jPanel9);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tabbedPane.setName("tabbedPane"); // NOI18N
        jScrollPane2.setViewportView(tabbedPane);

        jSplitPane9.setRightComponent(jScrollPane2);

        jSplitPane6.setRightComponent(jSplitPane9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        spriteTabbedPane.addTab("动画编辑窗口", jPanel1);

        bottomLabel.setText("按住Shift再拖动可改变切块大小");
        bottomLabel.setName("bottomLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bottomLabel)
                .addContainerGap(903, Short.MAX_VALUE))
            .addComponent(spriteTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(spriteTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser ch = new JFileChooser(AppData.getInstance().getCurProject().getPath() + File.separatorChar + "image" + File.separatorChar + "animation");
        ch.setMultiSelectionEnabled(true);
        JFileChooserImagePreview preview = new JFileChooserImagePreview(ch);
        ch.addPropertyChangeListener(preview);
        ch.setAccessory(preview);
        int ret = ch.showOpenDialog(this);
        if (ret == JFileChooser.APPROVE_OPTION) {
            File[] files = ch.getSelectedFiles();
            for (int i = 0; i < files.length; i++) {
                Picture pic = new Picture();
                try {
                    pic.setSourceImageFile(files[i].getName());
                } catch (IOException ex) {
                    System.out.println("不支持的图像文件:" + files[i].getPath());
                }
                AppData.getInstance().getCurProject().addPicture(pic);
            }
        }
    }//GEN-LAST:event_addImageButtonActionPerformed

    /**
     *
     * @return
     */
    public HashMap<Picture, HandlePicturePane> getHandlePicturePanes() {
        return handlePicturePanes;
    }
    private void zoomInPictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomInPictureButtonActionPerformed
        // TODO add your handling code here:
        if (picturePane.getSelectedIndex() == -1) {
            return;
        }
        handlePicturePanes.get(picturePane.getSelectedPicture()).zoomIn();
}//GEN-LAST:event_zoomInPictureButtonActionPerformed

    private void zoomOutPictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomOutPictureButtonActionPerformed
        // TODO add your handling code here:
        if (picturePane.getSelectedIndex() == -1) {
            return;
        }
        handlePicturePanes.get(picturePane.getSelectedPicture()).zoomOut();
}//GEN-LAST:event_zoomOutPictureButtonActionPerformed

    private void normalPictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalPictureButtonActionPerformed
        // TODO add your handling code here:
        if (picturePane.getSelectedIndex() == -1) {
            return;
        }
        handlePicturePanes.get(picturePane.getSelectedPicture()).setZoomLevel(HandlePicturePane.ZOOM_NORMALSIZE);
}//GEN-LAST:event_normalPictureButtonActionPerformed

    private void removeImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeImageButtonActionPerformed
        // TODO add your handling code here:
        if (picturePane.getSelectedIndex() == -1) {
            return;
        }
        int choose = JOptionPane.showConfirmDialog(this, "素材可能正在使用，你确定要删除吗？", "警告", JOptionPane.OK_CANCEL_OPTION);
        if (choose == JOptionPane.OK_OPTION) {
            AppData.getInstance().getCurProject().removePicture(picturePane.getSelectedIndex());
        }
    }//GEN-LAST:event_removeImageButtonActionPerformed

    private void spriteTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spriteTabbedPaneStateChanged
        // TODO add your handling code here:
        if (spriteTabbedPane.getSelectedIndex() == 0) {
            bottomLabel.setText("选中切好的图块后，再按住Shift然后拖动可改变切块大小");
        } else {
            bottomLabel.setText("拖动右方元件库中切好的图块拖到中央面板进行拼装");
        }
    }//GEN-LAST:event_spriteTabbedPaneStateChanged

    private void newAniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAniButtonActionPerformed
        // TODO add your handling code here:
        Animation ani = new Animation();
        ani.setName("双击设置动画名称");
        AppData.getInstance().getCurProject().addAnimation(ani);
        Frame frame = new Frame();
        frame.setName("双击设置帧名称");
        ani.addFrame(frame);
        handleFramePane.setCurFrame(frame);
    }//GEN-LAST:event_newAniButtonActionPerformed

    private void removeAniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAniButtonActionPerformed
        // TODO add your handling code here:

        if (aniTable.getSelectedRow() < 0 || aniTable.getSelectedRow() > AppData.getInstance().getCurProject().getAnimationCounts() - 1) {
            return;
        }
        int id = JOptionPane.showConfirmDialog(this, "你确定要删除该动画吗？", "删除动画", JOptionPane.OK_CANCEL_OPTION);
        if (id == JOptionPane.OK_OPTION) {
            AppData.getInstance().getCurProject().removeAnimation(Integer.parseInt(atm.getValueAt(aniTable.getSelectedRow(), 0).toString()));
            AppData.getInstance().setCurrentAnimationIndex(-1);
            atm.updateData();
            aniTable.getSelectionModel().clearSelection();
            aniTable.updateUI();
            handleFramePane.setCurFrame(null);
            frameTable.getSelectionModel().clearSelection();
            frameTable.updateUI();
        }

    }//GEN-LAST:event_removeAniButtonActionPerformed
    private AppData data = AppData.getInstance();
    private void addFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFrameButtonActionPerformed
        // TODO add your handling code here:
        if (data.getCurrentAnimationIndex() < 0 || data.getCurrentAnimationIndex() > data.getCurProject().getAnimationCounts() - 1) {
            return;
        }
        Animation ani = data.getCurProject().getAnimation(data.getCurrentAnimationIndex());
        Frame frame = new Frame();
        frame.setName("双击设置帧名称");
        frame.setAnimation(ani);
        ani.addFrame(frame);
        handleFramePane.setCurFrame(frame);
        frameTable.getSelectionModel().setSelectionInterval(ani.getFrames().size() - 1,
                ani.getFrames().size() - 1);
        frameTable.updateUI();
    }//GEN-LAST:event_addFrameButtonActionPerformed

    private void removeFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFrameButtonActionPerformed
        // TODO add your handling code here:
        if (data.getCurrentAnimationIndex() < 0 || data.getCurrentAnimationIndex() > data.getCurProject().getAnimationCounts() - 1) {
            return;
        }
        Animation ani = data.getCurProject().getAnimation(data.getCurrentAnimationIndex());
        if (frameTable.getSelectedRow() < 0 || frameTable.getSelectedRow() > ani.getFrames().size() - 1) {
            return;
        }
        ani.removeFrame(frameTable.getSelectedRow());
        handleFramePane.setCurFrame(ani.getFrame(0));
        if (ani.getFrames().size() > 0) {
            frameTable.getSelectionModel().setSelectionInterval(0, 0);
        } else {
            frameTable.getSelectionModel().clearSelection();
        }
        frameTable.updateUI();
    }//GEN-LAST:event_removeFrameButtonActionPerformed

    private void removeActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionButtonActionPerformed
        // TODO add your handling code here:
        if (data.getCurrentAnimationIndex() < 0 || data.getCurrentAnimationIndex() > data.getCurProject().getAnimationCounts() - 1) {
            return;
        }
        Animation ani = data.getCurProject().getAnimation(data.getCurrentAnimationIndex());
        if (actionTable.getSelectedRow() < 0 || actionTable.getSelectedRow() > ani.getActions().size() - 1) {
            return;
        }
        ani.removeAction(actionTable.getSelectedRow());
        if (ani.getActions().size() > 0) {
            actionTable.getSelectionModel().setSelectionInterval(0, 0);
        } else {
            actionTable.getSelectionModel().clearSelection();
        }
        actionTable.updateUI();
    }//GEN-LAST:event_removeActionButtonActionPerformed

    private void addActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionButtonActionPerformed
        // TODO add your handling code here:
        if (data.getCurrentAnimationIndex() < 0 || data.getCurrentAnimationIndex() > data.getCurProject().getAnimationCounts() - 1) {
            return;
        }
        ActionDialog nad = new ActionDialog(this, true);
        nad.setVisible(true);
    }//GEN-LAST:event_addActionButtonActionPerformed

    private void aniTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aniTableMouseClicked
        // TODO add your handling code here:
        AppData.getInstance().setCurrentAnimationIndex(Integer.parseInt(atm.getValueAt(aniTable.getSelectedRow(), 0).toString()));
        Animation ani = data.getCurProject().getAnimation(data.getCurrentAnimationIndex());
        handleFramePane.setCurFrame(ani.getFrame(0));
        if (ani.getFrames().size() > 0) {
            frameTable.getSelectionModel().setSelectionInterval(0, 0);
        } else {
            frameTable.getSelectionModel().clearSelection();
        }
        frameTable.updateUI();
        if (ani.getActions().size() > 0) {
            actionTable.getSelectionModel().setSelectionInterval(0, 0);
        } else {
            actionTable.getSelectionModel().clearSelection();
        }
        actionTable.updateUI();
    }//GEN-LAST:event_aniTableMouseClicked

    private void playAnimationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAnimationButtonActionPerformed
        // TODO add your handling code here:
        handleFramePane.playOrPause(loopCheckBox.isSelected());
        if (handleFramePane.isIsPlay()) {
            playAnimationButton.setText("暂停");
        } else {
            playAnimationButton.setText("播放");
        }

    }//GEN-LAST:event_playAnimationButtonActionPerformed

    private void loopCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loopCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loopCheckBoxActionPerformed

    private void zoomInFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomInFrameButtonActionPerformed
        // TODO add your handling code here:
        if (handleFramePane.getCurFrame() != null) {
            handleFramePane.zoomIn();
        }
    }//GEN-LAST:event_zoomInFrameButtonActionPerformed

    private void zoomOutFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomOutFrameButtonActionPerformed
        // TODO add your handling code here:
        if (handleFramePane.getCurFrame() != null) {
            handleFramePane.zoomOut();
        }
    }//GEN-LAST:event_zoomOutFrameButtonActionPerformed

    private void normalFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalFrameButtonActionPerformed
        // TODO add your handling code here:
        if (handleFramePane.getCurFrame() != null) {
            handleFramePane.setZoomLevel(handleFramePane.ZOOM_NORMALSIZE);
        }
    }//GEN-LAST:event_normalFrameButtonActionPerformed

    private void frameTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameTableMouseClicked
        // TODO add your handling code here:

        Animation ani = data.getCurProject().getAnimation(data.getCurrentAnimationIndex());
        if (frameTable.getSelectedRow() < 0 || frameTable.getSelectedRow() > ani.getFrames().size() - 1) {
            return;
        }
        handleFramePane.setCurFrame(ani.getFrame(frameTable.getSelectedRow()));
    }//GEN-LAST:event_frameTableMouseClicked

    private void actionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 2) {
            Animation ani = data.getCurProject().getAnimation(data.getCurrentAnimationIndex());
            if (actionTable.getSelectedRow() < 0 || actionTable.getSelectedRow() > ani.getActions().size() - 1) {
                return;
            }
            ActionDialog ad = new ActionDialog(this, true);
            ad.setCurAction(ani.getAction(actionTable.getSelectedRow()));
            ad.setVisible(true);
        }
    }//GEN-LAST:event_actionTableMouseClicked

    private void upFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upFrameButtonActionPerformed
        // TODO add your handling code here:
        if (data.getCurrentAnimationIndex() < 0 || data.getCurrentAnimationIndex() > data.getCurProject().getAnimationCounts() - 1) {
            return;
        }
        Animation ani = data.getCurProject().getAnimation(data.getCurrentAnimationIndex());
        int frameIndex = ani.getFrames().indexOf(handleFramePane.getCurFrame());
        if (frameIndex > 0) {
            ani.swapFrameUp(frameIndex);
            frameTable.getSelectionModel().setSelectionInterval(frameIndex - 1,
                    frameIndex - 1);
            handleFramePane.setCurFrame(ani.getFrame(frameTable.getSelectedRow()));
            frameTable.updateUI();
        }
    }//GEN-LAST:event_upFrameButtonActionPerformed

    private void downFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downFrameButtonActionPerformed
        // TODO add your handling code here:
        if (data.getCurrentAnimationIndex() < 0 || data.getCurrentAnimationIndex() > data.getCurProject().getAnimationCounts() - 1) {
            return;
        }
        Animation ani = data.getCurProject().getAnimation(data.getCurrentAnimationIndex());
        int frameIndex = ani.getFrames().indexOf(handleFramePane.getCurFrame());
        int totalFrames = ani.getFrames().size();
        if (frameIndex < totalFrames - 1) {
            ani.swapFrameDown(frameIndex);
            frameTable.getSelectionModel().setSelectionInterval(frameIndex + 1,
                    frameIndex + 1);
            handleFramePane.setCurFrame(ani.getFrame(frameTable.getSelectedRow()));
            frameTable.updateUI();
        }
    }//GEN-LAST:event_downFrameButtonActionPerformed

    private void leftRoate90ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftRoate90ButtonActionPerformed
        // TODO add your handling code here:
        Clip clip = handleFramePane.getSelectedTile();
        if (clip != null) {
            if (clip.getRotation() - 90 >= 0) {
                clip.setRotation(clip.getRotation() - 90);
            } else {
                clip.setRotation(clip.getRotation() - 90 + 360);
            }
            handleFramePane.repaint();
        }
    }//GEN-LAST:event_leftRoate90ButtonActionPerformed

    private void rightRoate90ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightRoate90ButtonActionPerformed
        // TODO add your handling code here:
        Clip clip = handleFramePane.getSelectedTile();
        if (clip != null) {
            if (clip.getRotation() + 90 < 360) {
                clip.setRotation(clip.getRotation() + 90);
            } else {
                clip.setRotation(clip.getRotation() + 90 - 360);
            }
            handleFramePane.repaint();
        }
    }//GEN-LAST:event_rightRoate90ButtonActionPerformed

    private void flipHorizontalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flipHorizontalButtonActionPerformed
        // TODO add your handling code here:
        Clip clip = handleFramePane.getSelectedTile();
        if (clip != null) {
            if (clip.getRotation() == 90 || clip.getRotation() == 270) {
                if (clip.getRotation() + 180 < 360) {
                    clip.setRotation(clip.getRotation() + 180);
                } else {
                    clip.setRotation(clip.getRotation() + 180 - 360);
                }
            }
            clip.setMirror(!clip.isMirror());
            handleFramePane.repaint();
        }
    }//GEN-LAST:event_flipHorizontalButtonActionPerformed

    private void outButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outButtonActionPerformed
        // TODO add your handling code here:
        Clip clip = handleFramePane.getSelectedTile();
        if (clip != null) {
            Frame frame = handleFramePane.getCurFrame();
            int id = frame.getTiles().indexOf(clip);
            if (id < frame.getTiles().size() - 1) {
                frame.swapClipUp(id);
                handleFramePane.setSelectedTileIndex(id + 1);
                handleFramePane.repaint();
            }
        }
    }//GEN-LAST:event_outButtonActionPerformed

    private void inButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inButtonActionPerformed
        // TODO add your handling code here:
        Clip clip = handleFramePane.getSelectedTile();
        if (clip != null) {
            Frame frame = handleFramePane.getCurFrame();
            int id = frame.getTiles().indexOf(clip);
            if (id > 0) {
                frame.swapClipDown(id);
                handleFramePane.setSelectedTileIndex(id - 1);
                handleFramePane.repaint();
            }
        }
    }//GEN-LAST:event_inButtonActionPerformed

    private void cloneFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cloneFrameButtonActionPerformed
        // TODO add your handling code here:
        if (data.getCurrentAnimationIndex() < 0 || data.getCurrentAnimationIndex() > data.getCurProject().getAnimationCounts() - 1) {
            return;
        }
        Animation ani = data.getCurProject().getAnimation(data.getCurrentAnimationIndex());
        Frame frame = null;
        if (handleFramePane.getCurFrame() != null) {
            try {
                frame = (Frame) handleFramePane.getCurFrame().clone();
            } catch (CloneNotSupportedException ex) {
                ex.printStackTrace();
            }
            ani.addFrame(frame);
            handleFramePane.setCurFrame(frame);
            frameTable.getSelectionModel().setSelectionInterval(ani.getFrames().size() - 1,
                    ani.getFrames().size() - 1);
            frameTable.updateUI();
        }
    }//GEN-LAST:event_cloneFrameButtonActionPerformed

    private void flipVerticalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flipVerticalButtonActionPerformed
        // TODO add your handling code here:
        Clip clip = handleFramePane.getSelectedTile();
        if (clip != null) {
            if (clip.getRotation() == 0 || clip.getRotation() == 180) {
                if (clip.getRotation() + 180 < 360) {
                    clip.setRotation(clip.getRotation() + 180);
                } else {
                    clip.setRotation(clip.getRotation() + 180 - 360);
                }
            }
            clip.setMirror(!clip.isMirror());
            handleFramePane.repaint();
        }
    }//GEN-LAST:event_flipVerticalButtonActionPerformed

    private void centerAlignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centerAlignButtonActionPerformed
        // TODO add your handling code here:
        Clip clip = handleFramePane.getSelectedTile();
        if (clip != null) {
            clip.getFramePoint().x = HandleFramePane.FRAME_PANEL_W / 2 - clip.getW() / 2;
            clip.getFramePoint().y = HandleFramePane.FRAME_PANEL_H / 2 - clip.getH() / 2;
            handleFramePane.repaint();
        }
}//GEN-LAST:event_centerAlignButtonActionPerformed

    private void rightAlignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightAlignButtonActionPerformed
        // TODO add your handling code here:
        Clip clip = handleFramePane.getSelectedTile();
        if (clip != null) {
            clip.getFramePoint().x = HandleFramePane.FRAME_PANEL_W / 2 - clip.getW();
            handleFramePane.repaint();
        }
}//GEN-LAST:event_rightAlignButtonActionPerformed

    private void leftAlignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftAlignButtonActionPerformed
        // TODO add your handling code here:
        Clip clip = handleFramePane.getSelectedTile();
        if (clip != null) {
            clip.getFramePoint().x = HandleFramePane.FRAME_PANEL_W / 2;
            handleFramePane.repaint();
        }
}//GEN-LAST:event_leftAlignButtonActionPerformed

    private void downAlignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downAlignButtonActionPerformed
        // TODO add your handling code here:
        Clip clip = handleFramePane.getSelectedTile();
        if (clip != null) {
            clip.getFramePoint().y = HandleFramePane.FRAME_PANEL_H / 2 - clip.getH();
            handleFramePane.repaint();
        }
}//GEN-LAST:event_downAlignButtonActionPerformed

    private void upAlignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upAlignButtonActionPerformed
        // TODO add your handling code here:
        Clip clip = handleFramePane.getSelectedTile();
        if (clip != null) {
            clip.getFramePoint().y = HandleFramePane.FRAME_PANEL_H / 2;
            handleFramePane.repaint();
        }
}//GEN-LAST:event_upAlignButtonActionPerformed

    private void alphaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_alphaSliderStateChanged
        // TODO add your handling code here:
        Clip clip = handleFramePane.getSelectedTile();
        if (clip != null) {
            clip.setTransparency(alphaSlider.getValue());
            handleFramePane.repaint();
        }
    }//GEN-LAST:event_alphaSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SpriteEditorDialog dialog = new SpriteEditorDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private AnimationTableModel atm;
    private FrameTableModel ftm;
    private ActionTableModel actm;
    private ChoosePicturePane picturePane;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable actionTable;
    private javax.swing.JButton addActionButton;
    private javax.swing.JButton addFrameButton;
    private javax.swing.JButton addImageButton;
    private javax.swing.JSlider alphaSlider;
    private javax.swing.JTable aniTable;
    private javax.swing.JLabel bottomLabel;
    private javax.swing.JButton centerAlignButton;
    private javax.swing.JButton cloneFrameButton;
    private javax.swing.JButton downAlignButton;
    private javax.swing.JButton downFrameButton;
    private javax.swing.JButton flipHorizontalButton;
    private javax.swing.JButton flipVerticalButton;
    private javax.swing.JTable frameTable;
    private com.soyomaker.widget.HandleFramePane handleFramePane;
    public javax.swing.JScrollPane handlePictureScrollPane;
    private javax.swing.JButton inButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JSplitPane jSplitPane6;
    private javax.swing.JSplitPane jSplitPane7;
    private javax.swing.JSplitPane jSplitPane8;
    private javax.swing.JSplitPane jSplitPane9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JToolBar jToolBar6;
    private javax.swing.JToolBar jToolBar7;
    private javax.swing.JToolBar jToolBar8;
    private javax.swing.JButton leftAlignButton;
    private javax.swing.JButton leftRoate90Button;
    private javax.swing.JCheckBox loopCheckBox;
    private javax.swing.JButton newAniButton;
    private javax.swing.JButton normalFrameButton;
    private javax.swing.JButton normalPictureButton;
    private javax.swing.JButton outButton;
    private javax.swing.JButton playAnimationButton;
    private javax.swing.JButton removeActionButton;
    private javax.swing.JButton removeAniButton;
    private javax.swing.JButton removeFrameButton;
    private javax.swing.JButton removeImageButton;
    private javax.swing.JButton rightAlignButton;
    private javax.swing.JButton rightRoate90Button;
    public javax.swing.JScrollPane showPictureScrollPane;
    private javax.swing.JTabbedPane spriteTabbedPane;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JButton upAlignButton;
    private javax.swing.JButton upFrameButton;
    private javax.swing.JButton zoomInFrameButton;
    private javax.swing.JButton zoomInPictureButton;
    private javax.swing.JButton zoomOutFrameButton;
    private javax.swing.JButton zoomOutPictureButton;
    // End of variables declaration//GEN-END:variables

    public void projectChanged(ProjectChangedEvent e) {
    }

    public void animationAdded(ProjectChangedEvent e, final Animation ani) {

        AppData.getInstance().setCurrentAnimationIndex(AppData.getInstance().getCurProject().getAnimationCounts() - 1);
        atm.updateData();
        aniTable.getSelectionModel().setSelectionInterval(AppData.getInstance().getCurProject().getAnimationCounts() - 1,
                AppData.getInstance().getCurProject().getAnimationCounts() - 1);
        aniTable.updateUI();
        frameTable.getSelectionModel().setSelectionInterval(ani.getFrames().size() - 1,
                ani.getFrames().size() - 1);
        frameTable.updateUI();
        if (ani.getFrames().size() > 0) {
            handleFramePane.setCurFrame(ani.getFrame(ani.getFrames().size() - 1));
        }
        actionTable.getSelectionModel().setSelectionInterval(ani.getActions().size() - 1,
                ani.getActions().size() - 1);
        actionTable.updateUI();
    }

    public void pictureAdded(ProjectChangedEvent e, final Picture pic) {

        ShowPicturePane spp = new ShowPicturePane(SpriteEditorDialog.this, pic);
        JScrollPane paletteScrollPane = new JScrollPane(spp,
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        aspp.addPanel(pic.getSourceImageFile(), paletteScrollPane);
        //tabbedPane.add(pic.getSourceImageFile(), paletteScrollPane);
        showPictureScrollPanes.put(pic, paletteScrollPane);
        HandlePicturePane hpp = new HandlePicturePane(SpriteEditorDialog.this, pic);
        DragSource dragSource = DragSource.getDefaultDragSource();
        dragSource.createDefaultDragGestureRecognizer(spp,
                DnDConstants.ACTION_COPY_OR_MOVE, spp);
        DropTarget dropTarget = new DropTarget(handleFramePane, DnDConstants.ACTION_COPY, handleFramePane);
        handlePicturePanes.put(pic, hpp);
        picturePane.setSelectedIndex(AppData.getInstance().getCurProject().getPictures().size() - 1);
        handlePictureScrollPane.setViewportView(hpp);
    }

    public void mapAdded(ProjectChangedEvent e, Map map) {
    }

    public void npcAdded(ProjectChangedEvent e, Npc npc) {
    }

    public void scriptAdded(ProjectChangedEvent e, ScriptFile npc) {
    }

    public void animationRemoved(ProjectChangedEvent e, int index) {
    }

    public void pictureRemoved(ProjectChangedEvent e, int index) {
        //tabbedPane.remove(showPictureScrollPanes.get(picturePane.getSelectedPicture()));
        handlePicturePanes.remove(picturePane.getSelectedPicture());
        aspp.removePanel(showPictureScrollPanes.get(picturePane.getSelectedPicture()));
        showPictureScrollPanes.remove(picturePane.getSelectedPicture());
        picturePane.setSelectedIndex(-1);
        handlePictureScrollPane.setViewportView(null);
    }

    public void mapRemoved(ProjectChangedEvent e, int index) {
    }

    public void npcRemoved(ProjectChangedEvent e, int index) {
    }

    public void scriptRemoved(ProjectChangedEvent e, int index) {
    }
}
