/*
 * Copyright 2010-2011 Soyostar Software, Inc. All rights reserved.
 */
package com.soyostar.script;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Administrator
 */
public class SearchDialog extends javax.swing.JDialog {

    /** Creates new form SearchDialog */
    public SearchDialog() {
        this.setModal(true);
        initComponents();
        initialize();
    }
    private ScriptManagerDialog smd;

    /**
     *
     * @param smd
     */
    public SearchDialog(ScriptManagerDialog smd) {
        this.smd = smd;
        this.setModal(true);
        initComponents();
        initialize();
    }

    private void initialize() {
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        findField = new javax.swing.JTextField();
        uplowCase = new javax.swing.JCheckBox();
        allReplaceButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        replaceField = new javax.swing.JTextField();
        findNextButton = new javax.swing.JButton();
        replaceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(SearchDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setResizable(false);

        jLabel1.setText("查找内容");
        jLabel1.setName("jLabel1"); // NOI18N

        findField.setName("findField"); // NOI18N

        uplowCase.setText("区分大小写");
        uplowCase.setName("uplowCase"); // NOI18N
        uplowCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uplowCaseActionPerformed(evt);
            }
        });

        allReplaceButton.setText("全部替换");
        allReplaceButton.setName("allReplaceButton"); // NOI18N
        allReplaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allReplaceButtonActionPerformed(evt);
            }
        });

        cancleButton.setText("取消");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("替换为：");
        jLabel2.setName("jLabel2"); // NOI18N

        replaceField.setName("replaceField"); // NOI18N

        findNextButton.setText("查找下一个");
        findNextButton.setName("findNextButton"); // NOI18N
        findNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findNextButtonActionPerformed(evt);
            }
        });

        replaceButton.setText("替换");
        replaceButton.setName("replaceButton"); // NOI18N
        replaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(cancleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uplowCase)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(replaceField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(findField))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(allReplaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(findNextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(replaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(findNextButton)
                    .addComponent(findField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(replaceButton)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uplowCase)
                    .addComponent(allReplaceButton))
                .addGap(10, 10, 10)
                .addComponent(cancleButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancleButtonActionPerformed

    private void allReplaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allReplaceButtonActionPerformed
        // TODO add your handling code here:
        replaceAll();
    }//GEN-LAST:event_allReplaceButtonActionPerformed

    /**
     *
     */
    public void replaceAll() {
        while (true) {
            String sfind = findField.getText();
            String sreplace = replaceField.getText();
            String cur = smd.mainTextPanel.getText().replaceAll("\n", "");
            if (cur.indexOf(sfind) == -1) {
                break;
            }
            if (smd.mainTextPanel.getCaretPosition() == cur.length()) {
                smd.mainTextPanel.setCaretPosition(0);
            }
            smd.mainTextPanel.setSelectionStart(cur.indexOf(sfind, smd.mainTextPanel.getCaretPosition()));
            smd.mainTextPanel.setSelectionEnd(cur.indexOf(sfind, smd.mainTextPanel.getCaretPosition()) + sfind.length());
            smd.mainTextPanel.replaceSelection(sreplace);
        }
    }
    private void uplowCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uplowCaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uplowCaseActionPerformed

    private void findNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findNextButtonActionPerformed
        // TODO add your handling code here:
        String sfind = findField.getText();
        String cur = smd.mainTextPanel.getText().replaceAll("\n", "");
        if (cur.indexOf(sfind) == -1) {
            System.out.println("找不到该字符串!");
        } else {
            if (smd.mainTextPanel.getCaretPosition() == cur.length()) {
                smd.mainTextPanel.setCaretPosition(0);
            }
            smd.mainTextPanel.setSelectionStart(cur.indexOf(sfind, smd.mainTextPanel.getCaretPosition()));
            smd.mainTextPanel.setSelectionEnd(cur.indexOf(sfind, smd.mainTextPanel.getCaretPosition()) + sfind.length());
        }
    }//GEN-LAST:event_findNextButtonActionPerformed

    private void replaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceButtonActionPerformed
        // TODO add your handling code here:
        replace();
    }//GEN-LAST:event_replaceButtonActionPerformed

    private void replace() {
        String sfind = findField.getText();
        String sreplace = replaceField.getText();
        String cur = smd.mainTextPanel.getText().replaceAll("\n", "");
        if (cur.indexOf(sfind) == -1) {
            System.out.println("找不到该字符串!");
        } else {
            if (smd.mainTextPanel.getCaretPosition() == cur.length()) {
                smd.mainTextPanel.setCaretPosition(0);
            }
            smd.mainTextPanel.setSelectionStart(cur.indexOf(sfind, smd.mainTextPanel.getCaretPosition()));
            smd.mainTextPanel.setSelectionEnd(cur.indexOf(sfind, smd.mainTextPanel.getCaretPosition()) + sfind.length());
            smd.mainTextPanel.replaceSelection(sreplace);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SearchDialog dialog = new SearchDialog();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allReplaceButton;
    private javax.swing.JButton cancleButton;
    private javax.swing.JTextField findField;
    private javax.swing.ButtonGroup findGroup;
    private javax.swing.JButton findNextButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton replaceButton;
    private javax.swing.JTextField replaceField;
    private javax.swing.JCheckBox uplowCase;
    // End of variables declaration//GEN-END:variables
}