/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NpcStatePane.java
 *
 * Created on 2011-6-7, 1:45:46
 */
package com.soyomaker.widget;

import com.soyomaker.dialog.EventManagerDialog;
import com.soyomaker.dialog.NpcHeadImageDialog;
import com.soyomaker.dialog.NpcMoveImageDialog;
import com.soyomaker.dialog.ScriptDialog;
import com.soyomaker.model.map.NpcState;
import com.soyomaker.script.ScriptEditorDialog;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class NpcStatePane extends javax.swing.JPanel implements TableModelListener {

    /** Creates new form NpcStatePane
     * @param emd 
     */
    public NpcStatePane(EventManagerDialog emd) {
        this.emd = emd;
        initComponents();
//        addScript();
    }
    private NpcState npcState = new NpcState();
    private String[] col = {"执行内容"};
    /**
     * 
     */
    public DefaultTableModel eventTM = new javax.swing.table.DefaultTableModel(col, 0) {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * 
     * @return
     */
    public NpcState getNpcState() {
        return npcState;
    }

    /**
     * 
     * @param state
     */
    public void setNpcState(NpcState state) {

        npcState = state;
        typeComboBox.setSelectedIndex(state.getMove());
        speedComboBox.setSelectedIndex(state.getSpeed());
        switch (state.getStartType()) {
            case NpcState.AUTOMATIC:
                automaticRadioButton.setSelected(true);
                break;
            case NpcState.BUTTON:
                buttonRadioButton.setSelected(true);
                break;
            case NpcState.CONTACT:
                contactRadioButton.setSelected(true);
                break;
        }
        crossCheckBox.setSelected(state.isCross());
        npcMoveImgPane.repaint();
        npcHeadImgPane.repaint();
        int n = 0;
        String[] s = state.getScript().getFunc().split("\n");
        if (!state.getScript().getFunc().equals("")) {
            n = s.length;
        }
        eventTM.getDataVector().clear();
        for (int i = 0; i < n; i++) {
            String[] ss = {s[i]};
            eventTM.addRow(ss);
            eventTable.getSelectionModel().setSelectionInterval(i, i);
        }
        String[] sss = {""};
        eventTM.addRow(sss);
        eventTable.getSelectionModel().setSelectionInterval(s.length, s.length);
    }
    private EventManagerDialog emd;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        eventPopupMenu = new javax.swing.JPopupMenu();
        addMenuItem = new javax.swing.JMenuItem();
        insertMenuItem = new javax.swing.JMenuItem();
        removeMenuItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        switchCheckBox = new javax.swing.JCheckBox();
        varCheckBox = new javax.swing.JCheckBox();
        switchComboBox = new javax.swing.JComboBox();
        varComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        upVarTextField = new javax.swing.JTextField();
        varOperationTypeComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        onComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        npcMoveImgPane = new javax.swing.JPanel(){
            public void paint(Graphics g){
                super.paint(g);
                if(npcState.getImg()!=null){
                    Image img = null;
                    switch(npcState.getFace()){
                        case 0:
                        img = npcState.getImg().getSubimage(0, 0,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 1:
                        img = npcState.getImg().getSubimage(npcState.getImg().getWidth(null)/4, 0,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 2:
                        img = npcState.getImg().getSubimage(npcState.getImg().getWidth(null)/2, 0,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 3:
                        img = npcState.getImg().getSubimage(npcState.getImg().getWidth(null)*3/4, 0,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 4:
                        img = npcState.getImg().getSubimage(0, npcState.getImg().getHeight(null)/4,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 5:
                        img = npcState.getImg().getSubimage(npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 6:
                        img = npcState.getImg().getSubimage(npcState.getImg().getWidth(null)/2,
                            npcState.getImg().getHeight(null)/4,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 7:
                        img = npcState.getImg().getSubimage(npcState.getImg().getWidth(null)*3/4,
                            npcState.getImg().getHeight(null)/4,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 8:
                        img = npcState.getImg().getSubimage(0, npcState.getImg().getHeight(null)/2,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 9:
                        img = npcState.getImg().getSubimage(npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/2,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 10:
                        img = npcState.getImg().getSubimage(npcState.getImg().getWidth(null)/2,
                            npcState.getImg().getHeight(null)/2,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 11:
                        img = npcState.getImg().getSubimage(npcState.getImg().getWidth(null)*3/4,
                            npcState.getImg().getHeight(null)/2,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 12:
                        img = npcState.getImg().getSubimage(0, npcState.getImg().getHeight(null)*3/4,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 13:
                        img = npcState.getImg().getSubimage(npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)*3/4,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 14:
                        img = npcState.getImg().getSubimage(npcState.getImg().getWidth(null)/2,
                            npcState.getImg().getHeight(null)*3/4,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                        case 15:
                        img = npcState.getImg().getSubimage(npcState.getImg().getWidth(null)*3/4,
                            npcState.getImg().getHeight(null)*3/4,
                            npcState.getImg().getWidth(null)/4,
                            npcState.getImg().getHeight(null)/4);
                        break;
                    }
                    g.drawImage(img,this.getWidth()/2-img.getWidth(null)/2, this.getHeight()/2-img.getHeight(null)/2,null);
                }
            }
        }
        ;
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();
        speedComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        automaticRadioButton = new javax.swing.JRadioButton();
        contactRadioButton = new javax.swing.JRadioButton();
        buttonRadioButton = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        crossCheckBox = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        parallelRadioButton = new javax.swing.JRadioButton();
        serialRadioButton = new javax.swing.JRadioButton();
        jToolBar1 = new javax.swing.JToolBar();
        addScriptButton = new javax.swing.JButton();
        insertScriptButton = new javax.swing.JButton();
        removeScriptButton = new javax.swing.JButton();
        showScriptButton = new javax.swing.JButton();
        npcHeadImgPane = new javax.swing.JPanel(){
            public void paint(Graphics g){
                super.paint(g);
                if(npcState.getHeadImg()!=null){
                    g.drawImage(npcState.getHeadImg(), 0, 0,null);
                }
            }
        }
        ;
        jLabel7 = new javax.swing.JLabel();

        eventPopupMenu.setName("eventPopupMenu"); // NOI18N

        addMenuItem.setText("添加脚本");
        addMenuItem.setName("addMenuItem"); // NOI18N
        addMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuItemActionPerformed(evt);
            }
        });
        eventPopupMenu.add(addMenuItem);

        insertMenuItem.setText("插入脚本");
        insertMenuItem.setName("insertMenuItem"); // NOI18N
        insertMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertMenuItemActionPerformed(evt);
            }
        });
        eventPopupMenu.add(insertMenuItem);

        removeMenuItem.setText("删除脚本");
        removeMenuItem.setName("removeMenuItem"); // NOI18N
        removeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMenuItemActionPerformed(evt);
            }
        });
        eventPopupMenu.add(removeMenuItem);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("事件出现条件"));
        jPanel1.setName("jPanel1"); // NOI18N

        switchCheckBox.setText("开关");
        switchCheckBox.setName("switchCheckBox"); // NOI18N
        switchCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchCheckBoxActionPerformed(evt);
            }
        });

        varCheckBox.setText("变量");
        varCheckBox.setName("varCheckBox"); // NOI18N
        varCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varCheckBoxActionPerformed(evt);
            }
        });

        switchComboBox.setEnabled(false);
        switchComboBox.setFocusTraversalPolicyProvider(true);
        switchComboBox.setName("switchComboBox"); // NOI18N
        for(int i =0;i<100;i++){
            switchComboBox.addItem(i);
        }

        varComboBox.setEnabled(false);
        varComboBox.setName("varComboBox"); // NOI18N
        for(int i =0;i<100;i++){
            varComboBox.addItem(i);
        }

        jLabel1.setText("值为");
        jLabel1.setName("jLabel1"); // NOI18N

        upVarTextField.setEnabled(false);
        upVarTextField.setName("upVarTextField"); // NOI18N

        varOperationTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "等于", "大于", "小于", "大于等于", "小于等于", "不等于" }));
        varOperationTypeComboBox.setEnabled(false);
        varOperationTypeComboBox.setName("varOperationTypeComboBox"); // NOI18N

        jLabel3.setText("时");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel2.setText("为");
        jLabel2.setName("jLabel2"); // NOI18N

        onComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ON", "OFF" }));
        onComboBox.setEnabled(false);
        onComboBox.setName("onComboBox"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(switchCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(switchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(varCheckBox)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(varOperationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(upVarTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                            .addComponent(varComboBox, 0, 153, Short.MAX_VALUE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(onComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(switchCheckBox)
                    .addComponent(switchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varCheckBox)
                    .addComponent(varComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upVarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varOperationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Npc行走图：");
        jLabel4.setName("jLabel4"); // NOI18N

        npcMoveImgPane.setBackground(new java.awt.Color(255, 204, 255));
        npcMoveImgPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        npcMoveImgPane.setName("npcMoveImgPane"); // NOI18N
        npcMoveImgPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                npcMoveImgPaneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout npcMoveImgPaneLayout = new javax.swing.GroupLayout(npcMoveImgPane);
        npcMoveImgPane.setLayout(npcMoveImgPaneLayout);
        npcMoveImgPaneLayout.setHorizontalGroup(
            npcMoveImgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
        npcMoveImgPaneLayout.setVerticalGroup(
            npcMoveImgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("移动规则"));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel5.setText("类型:");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("速度:");
        jLabel6.setName("jLabel6"); // NOI18N

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "固定", "随机", "接近" }));
        typeComboBox.setName("typeComboBox"); // NOI18N
        typeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeComboBoxItemStateChanged(evt);
            }
        });

        speedComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "快", "中", "慢" }));
        speedComboBox.setName("speedComboBox"); // NOI18N
        speedComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                speedComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(speedComboBox, 0, 97, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speedComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        eventTable.setModel(eventTM);
        eventTable.setComponentPopupMenu(eventPopupMenu);
        eventTable.setName("eventTable"); // NOI18N
        eventTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        eventTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventTableMouseClicked(evt);
            }
        });
        eventTable.getModel().addTableModelListener(this);
        jScrollPane1.setViewportView(eventTable);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("触发条件"));
        jPanel5.setName("jPanel5"); // NOI18N

        buttonGroup2.add(automaticRadioButton);
        automaticRadioButton.setSelected(true);
        automaticRadioButton.setText("自动");
        automaticRadioButton.setName("automaticRadioButton"); // NOI18N
        automaticRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                automaticRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(contactRadioButton);
        contactRadioButton.setText("接触");
        contactRadioButton.setName("contactRadioButton"); // NOI18N
        contactRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(buttonRadioButton);
        buttonRadioButton.setText("按键");
        buttonRadioButton.setName("buttonRadioButton"); // NOI18N
        buttonRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(automaticRadioButton)
                .addGap(18, 18, 18)
                .addComponent(contactRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(buttonRadioButton)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(automaticRadioButton)
                    .addComponent(buttonRadioButton)
                    .addComponent(contactRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("选项"));
        jPanel6.setName("jPanel6"); // NOI18N

        crossCheckBox.setText("允许穿透");
        crossCheckBox.setName("crossCheckBox"); // NOI18N
        crossCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crossCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crossCheckBox)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(crossCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("执行策略"));
        jPanel4.setName("jPanel4"); // NOI18N

        buttonGroup3.add(parallelRadioButton);
        parallelRadioButton.setText("并行");
        parallelRadioButton.setName("parallelRadioButton"); // NOI18N

        buttonGroup3.add(serialRadioButton);
        serialRadioButton.setSelected(true);
        serialRadioButton.setText("串行");
        serialRadioButton.setName("serialRadioButton"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parallelRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(serialRadioButton)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parallelRadioButton)
                    .addComponent(serialRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        addScriptButton.setText("添加脚本");
        addScriptButton.setFocusable(false);
        addScriptButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addScriptButton.setName("addScriptButton"); // NOI18N
        addScriptButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addScriptButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(addScriptButton);

        insertScriptButton.setText("插入脚本");
        insertScriptButton.setFocusable(false);
        insertScriptButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        insertScriptButton.setName("insertScriptButton"); // NOI18N
        insertScriptButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        insertScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertScriptButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(insertScriptButton);

        removeScriptButton.setText("删除脚本");
        removeScriptButton.setFocusable(false);
        removeScriptButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeScriptButton.setName("removeScriptButton"); // NOI18N
        removeScriptButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeScriptButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(removeScriptButton);

        showScriptButton.setText("查看脚本代码");
        showScriptButton.setFocusable(false);
        showScriptButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showScriptButton.setName("showScriptButton"); // NOI18N
        showScriptButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        showScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showScriptButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(showScriptButton);

        npcHeadImgPane.setBackground(new java.awt.Color(255, 204, 255));
        npcHeadImgPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        npcHeadImgPane.setName("npcHeadImgPane"); // NOI18N
        npcHeadImgPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                npcHeadImgPaneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout npcHeadImgPaneLayout = new javax.swing.GroupLayout(npcHeadImgPane);
        npcHeadImgPane.setLayout(npcHeadImgPaneLayout);
        npcHeadImgPaneLayout.setHorizontalGroup(
            npcHeadImgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        npcHeadImgPaneLayout.setVerticalGroup(
            npcHeadImgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jLabel7.setText("Npc头像图");
        jLabel7.setName("jLabel7"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(npcMoveImgPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(npcHeadImgPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(npcHeadImgPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(npcMoveImgPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void switchCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchCheckBoxActionPerformed
        // TODO add your handling code here:
        if (switchCheckBox.isSelected()) {
            switchComboBox.setEnabled(true);
            onComboBox.setEnabled(true);
        } else {
            switchComboBox.setEnabled(false);
            onComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_switchCheckBoxActionPerformed

    private void varCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varCheckBoxActionPerformed
        // TODO add your handling code here:
        if (varCheckBox.isSelected()) {
            varComboBox.setEnabled(true);
            upVarTextField.setEnabled(true);
            varOperationTypeComboBox.setEnabled(true);
        } else {
            varComboBox.setEnabled(false);
            upVarTextField.setEnabled(false);
            varOperationTypeComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_varCheckBoxActionPerformed

    private void npcMoveImgPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_npcMoveImgPaneMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 2) {
            NpcMoveImageDialog cid = new NpcMoveImageDialog(this, true);
            cid.setVisible(true);
        }
    }//GEN-LAST:event_npcMoveImgPaneMouseClicked
    private ScriptDialog sd;
    private void eventTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 2) {
            if (sd == null) {
                sd = new ScriptDialog(this, true);
            }
            sd.setVisible(true);
        }
}//GEN-LAST:event_eventTableMouseClicked

    private void automaticRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_automaticRadioButtonActionPerformed
        // TODO add your handling code here:
        npcState.setStartType(NpcState.AUTOMATIC);
}//GEN-LAST:event_automaticRadioButtonActionPerformed

    private void contactRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactRadioButtonActionPerformed
        // TODO add your handling code here:

        npcState.setStartType(NpcState.CONTACT);
}//GEN-LAST:event_contactRadioButtonActionPerformed

    private void buttonRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRadioButtonActionPerformed
        // TODO add your handling code here:
        npcState.setStartType(NpcState.BUTTON);
}//GEN-LAST:event_buttonRadioButtonActionPerformed

    private void crossCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crossCheckBoxActionPerformed
        // TODO add your handling code here:
        npcState.setCross(crossCheckBox.isSelected());
}//GEN-LAST:event_crossCheckBoxActionPerformed

    private void speedComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_speedComboBoxItemStateChanged
        // TODO add your handling code here:
        npcState.setSpeed(Byte.parseByte("" + speedComboBox.getSelectedIndex()));
    }//GEN-LAST:event_speedComboBoxItemStateChanged

    private void typeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeComboBoxItemStateChanged
        // TODO add your handling code here:
        npcState.setMove(Byte.parseByte("" + typeComboBox.getSelectedIndex()));
    }//GEN-LAST:event_typeComboBoxItemStateChanged

    private void insertMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertMenuItemActionPerformed
        // TODO add your handling code here:
        if (sd == null) {
            sd = new ScriptDialog(this, true);
        }
        sd.setVisible(true);
    }//GEN-LAST:event_insertMenuItemActionPerformed

    private void removeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMenuItemActionPerformed
        // TODO add your handling code here:
        removeScript();
    }//GEN-LAST:event_removeMenuItemActionPerformed

    private void insertScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertScriptButtonActionPerformed
        // TODO add your handling code here:
        if (sd == null) {
            sd = new ScriptDialog(this, true);
        }
        sd.setVisible(true);
    }//GEN-LAST:event_insertScriptButtonActionPerformed

    private void removeScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeScriptButtonActionPerformed
        // TODO add your handling code here:
        removeScript();
    }//GEN-LAST:event_removeScriptButtonActionPerformed
    private void removeScript() {
        if (eventTable.getSelectedRow() == -1) {
            return;
        }
        eventTM.removeRow(eventTable.getSelectedRow());
        if (eventTM.getRowCount() == 0) {
            addScript();
        }
        eventTable.getSelectionModel().clearSelection();
    }
    private void addScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addScriptButtonActionPerformed
        // TODO add your handling code here:
        addScript();
    }//GEN-LAST:event_addScriptButtonActionPerformed
    private void addScript() {
        String[] s = {""};
        eventTM.addRow(s);
        eventTable.getSelectionModel().setSelectionInterval(eventTM.getRowCount() - 1, eventTM.getRowCount() - 1);
    }
    private void addMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMenuItemActionPerformed
        // TODO add your handling code here:
        addScript();
    }//GEN-LAST:event_addMenuItemActionPerformed

    private void showScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showScriptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showScriptButtonActionPerformed

    private void npcHeadImgPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_npcHeadImgPaneMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 2) {
            NpcHeadImageDialog cid = new NpcHeadImageDialog(this, true);
            cid.setVisible(true);
        }
    }//GEN-LAST:event_npcHeadImgPaneMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addMenuItem;
    private javax.swing.JButton addScriptButton;
    private javax.swing.JRadioButton automaticRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton buttonRadioButton;
    private javax.swing.JRadioButton contactRadioButton;
    private javax.swing.JCheckBox crossCheckBox;
    private javax.swing.JPopupMenu eventPopupMenu;
    public javax.swing.JTable eventTable;
    private javax.swing.JMenuItem insertMenuItem;
    private javax.swing.JButton insertScriptButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JPanel npcHeadImgPane;
    public javax.swing.JPanel npcMoveImgPane;
    private javax.swing.JComboBox onComboBox;
    private javax.swing.JRadioButton parallelRadioButton;
    private javax.swing.JMenuItem removeMenuItem;
    private javax.swing.JButton removeScriptButton;
    private javax.swing.JRadioButton serialRadioButton;
    private javax.swing.JButton showScriptButton;
    private javax.swing.JComboBox speedComboBox;
    private javax.swing.JCheckBox switchCheckBox;
    private javax.swing.JComboBox switchComboBox;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JTextField upVarTextField;
    private javax.swing.JCheckBox varCheckBox;
    private javax.swing.JComboBox varComboBox;
    private javax.swing.JComboBox varOperationTypeComboBox;
    // End of variables declaration//GEN-END:variables

    public void tableChanged(TableModelEvent e) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < eventTM.getRowCount(); i++) {
            sb.append(eventTM.getValueAt(i, 0)).append("\n");
        }
        npcState.getScript().setFunc(sb.toString());
    }
}
