/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IfDialog.java
 *
 * Created on 2011-6-21, 0:56:11
 */
package com.soyomaker.dialog.event.processcontrol;

import com.soyomaker.dialog.ScriptDialog;

/**
 *
 * @author Administrator
 */
public class IfDialog extends javax.swing.JDialog {

    /** Creates new form IfDialog
     * @param parent
     * @param modal  
     */
    public IfDialog(ScriptDialog parent, boolean modal) {
        super(parent, modal);
        sd = parent;
        initComponents();
        setLocationRelativeTo(null);
    }
    private ScriptDialog sd;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        switchRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        switchComboBox = new javax.swing.JComboBox();
        onComboBox = new javax.swing.JComboBox();
        varComboBox = new javax.swing.JComboBox();
        varOperationTypeComboBox = new javax.swing.JComboBox();
        varTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        varRadioButton = new javax.swing.JRadioButton();
        cancleButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(IfDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        buttonGroup1.add(switchRadioButton);
        switchRadioButton.setSelected(true);
        switchRadioButton.setText("开关");
        switchRadioButton.setName("switchRadioButton"); // NOI18N
        switchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchRadioButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("为");
        jLabel1.setName("jLabel1"); // NOI18N

        switchComboBox.setName("switchComboBox"); // NOI18N
        for(int i =0;i<100;i++){
            switchComboBox.addItem(i);
        }

        onComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ON", "OFF" }));
        onComboBox.setName("onComboBox"); // NOI18N

        varComboBox.setEnabled(false);
        varComboBox.setName("varComboBox"); // NOI18N
        for(int i =0;i<100;i++){
            varComboBox.addItem(i);
        }

        varOperationTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "等于", "大于", "小于", "大于等于", "小于等于", "不等于" }));
        varOperationTypeComboBox.setEnabled(false);
        varOperationTypeComboBox.setName("varOperationTypeComboBox"); // NOI18N

        varTextField.setText("0");
        varTextField.setEnabled(false);
        varTextField.setName("varTextField"); // NOI18N

        jLabel3.setText("时");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel2.setText("值为");
        jLabel2.setName("jLabel2"); // NOI18N

        buttonGroup1.add(varRadioButton);
        varRadioButton.setText("变量");
        varRadioButton.setName("varRadioButton"); // NOI18N
        varRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(switchRadioButton)
                    .addComponent(varRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(varOperationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varTextField))
                    .addComponent(varComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(switchComboBox, 0, 138, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addComponent(onComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(switchRadioButton)
                    .addComponent(switchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(onComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(varComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(varTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varOperationTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel2))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("1", jPanel1);

        cancleButton.setText("取消");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(okButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cancleButton)
                    .addGap(12, 12, 12))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancleButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        sd.insertScriptData(sd.npcPane.eventTable.getSelectedRow(), "end");
        sd.insertScriptData(sd.npcPane.eventTable.getSelectedRow(), "");
        if (switchRadioButton.isSelected()) {
            if (onComboBox.getSelectedIndex() == 0) {
                sd.insertScriptData(sd.npcPane.eventTable.getSelectedRow(), "if " + "getSwitch(" + switchComboBox.getSelectedIndex() + ")" + " then");
            } else {
                sd.insertScriptData(sd.npcPane.eventTable.getSelectedRow(), "if " + "!getSwitch(" + switchComboBox.getSelectedIndex() + ")" + " then");
            }
        }
        if (varRadioButton.isSelected()) {
            switch (varOperationTypeComboBox.getSelectedIndex()) {
                case 0:
                    sd.insertScriptData(sd.npcPane.eventTable.getSelectedRow(),
                            "if " + "getVar(" + varComboBox.getSelectedIndex() + ")" + "==" + varTextField.getText() + " then");
                    break;
                case 1:
                    sd.insertScriptData(sd.npcPane.eventTable.getSelectedRow(),
                            "if " + "getVar(" + varComboBox.getSelectedIndex() + ")" + ">" + varTextField.getText() + " then");
                    break;
                case 2:
                    sd.insertScriptData(sd.npcPane.eventTable.getSelectedRow(),
                            "if " + "getVar(" + varComboBox.getSelectedIndex() + ")" + "<" + varTextField.getText() + " then");
                    break;
                case 3:
                    sd.insertScriptData(sd.npcPane.eventTable.getSelectedRow(),
                            "if " + "getVar(" + varComboBox.getSelectedIndex() + ")" + ">=" + varTextField.getText() + " then");
                    break;
                case 4:
                    sd.insertScriptData(sd.npcPane.eventTable.getSelectedRow(),
                            "if " + "getVar(" + varComboBox.getSelectedIndex() + ")" + "<=" + varTextField.getText() + " then");
                    break;
                case 5:
                    sd.insertScriptData(sd.npcPane.eventTable.getSelectedRow(),
                            "if " + "getVar(" + varComboBox.getSelectedIndex() + ")" + "!=" + varTextField.getText() + " then");
                    break;
            }
        }
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancleButtonActionPerformed

    private void varRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varRadioButtonActionPerformed
        // TODO add your handling code here:
        varComboBox.setEnabled(true);
        varOperationTypeComboBox.setEnabled(true);
        varTextField.setEnabled(true);
        switchComboBox.setEnabled(false);
        onComboBox.setEnabled(false);
    }//GEN-LAST:event_varRadioButtonActionPerformed

    private void switchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchRadioButtonActionPerformed
        // TODO add your handling code here:
        varComboBox.setEnabled(false);
        varOperationTypeComboBox.setEnabled(false);
        varTextField.setEnabled(false);
        switchComboBox.setEnabled(true);
        onComboBox.setEnabled(true);
    }//GEN-LAST:event_switchRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                IfDialog dialog = new IfDialog(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox onComboBox;
    private javax.swing.JComboBox switchComboBox;
    private javax.swing.JRadioButton switchRadioButton;
    private javax.swing.JComboBox varComboBox;
    private javax.swing.JComboBox varOperationTypeComboBox;
    private javax.swing.JRadioButton varRadioButton;
    private javax.swing.JTextField varTextField;
    // End of variables declaration//GEN-END:variables
}
