/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewActionDialog.java
 *
 * Created on 2011-7-30, 11:38:41
 */
package com.soyomaker.dialog;

import com.soyomaker.model.animation.Action;
import com.soyomaker.model.animation.Animation;
import com.soyomaker.AppData;
import java.awt.Color;
import java.io.File;

/**
 *
 * @author Administrator
 */
public class ActionDialog extends javax.swing.JDialog {

    /** Creates new form NewActionDialog
     * @param parent
     * @param modal
     */
    public ActionDialog(SpriteEditorDialog parent, boolean modal) {
        super(parent, modal);
        this.sed = parent;
        initComponents();
        setLocationRelativeTo(null);
    }
    private Action action;

    /**
     *
     * @param act
     */
    public void setCurAction(Action act) {
        this.action = act;
        frameSpinner.setValue(act.getFrameId());
        musicComboBox.setSelectedItem(act.getMusicFile());
        switch (act.getType()) {
            case Action.NOTHING:
                nullRadioButton.setSelected(true);
                nullRadioButtonActionPerformed(null);
                break;
            case Action.PLAY_DISAPPEAR:
                objectDisappearRadioButton.setSelected(true);
                objectDisappearRadioButtonActionPerformed(null);
                break;
            case Action.PLAY_TWINKLE:
                objectTwinkleRadioButton.setSelected(true);
                objectTwinkleRadioButtonActionPerformed(null);
                break;
            case Action.SCEEN_TWINKLE:
                screenTwinkleRadioButton.setSelected(true);
                screenTwinkleRadioButtonActionPerformed(null);
                break;
        }
        durationSpinner.setValue(act.getDuration());
        redSlider.setValue(act.getRed());
        greenSlider.setValue(act.getGreen());
        blueSlider.setValue(act.getBlue());
        alphaSlider.setValue(act.getAlpha());
        showColorPanel.repaint();
    }
    private SpriteEditorDialog sed;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nullRadioButton = new javax.swing.JRadioButton();
        objectTwinkleRadioButton = new javax.swing.JRadioButton();
        screenTwinkleRadioButton = new javax.swing.JRadioButton();
        objectDisappearRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        redSlider = new javax.swing.JSlider();
        greenSlider = new javax.swing.JSlider();
        blueSlider = new javax.swing.JSlider();
        alphaSlider = new javax.swing.JSlider();
        redTextField = new javax.swing.JTextField();
        greenTextField = new javax.swing.JTextField();
        blueTextField = new javax.swing.JTextField();
        alphaTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        showColorPanel = new javax.swing.JPanel();
        durationSpinner = new javax.swing.JSpinner();
        cancleButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        musicComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        frameSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("添加特效");
        setResizable(false);

        jPanel1.setName("jPanel1"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("效果"));
        jPanel2.setName("jPanel2"); // NOI18N

        buttonGroup1.add(nullRadioButton);
        nullRadioButton.setSelected(true);
        nullRadioButton.setText("无");
        nullRadioButton.setName("nullRadioButton"); // NOI18N
        nullRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nullRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(objectTwinkleRadioButton);
        objectTwinkleRadioButton.setText("对象闪烁");
        objectTwinkleRadioButton.setName("objectTwinkleRadioButton"); // NOI18N
        objectTwinkleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objectTwinkleRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(screenTwinkleRadioButton);
        screenTwinkleRadioButton.setText("屏幕闪烁");
        screenTwinkleRadioButton.setName("screenTwinkleRadioButton"); // NOI18N
        screenTwinkleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenTwinkleRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(objectDisappearRadioButton);
        objectDisappearRadioButton.setText("对象消失");
        objectDisappearRadioButton.setName("objectDisappearRadioButton"); // NOI18N
        objectDisappearRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objectDisappearRadioButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("红色");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("绿色");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("蓝色");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText("透明度");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText("持续时间");
        jLabel8.setName("jLabel8"); // NOI18N

        redSlider.setMaximum(255);
        redSlider.setValue(255);
        redSlider.setEnabled(false);
        redSlider.setName("redSlider"); // NOI18N
        redSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                redSliderStateChanged(evt);
            }
        });

        greenSlider.setMaximum(255);
        greenSlider.setValue(255);
        greenSlider.setEnabled(false);
        greenSlider.setName("greenSlider"); // NOI18N
        greenSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                greenSliderStateChanged(evt);
            }
        });

        blueSlider.setMaximum(255);
        blueSlider.setValue(255);
        blueSlider.setEnabled(false);
        blueSlider.setName("blueSlider"); // NOI18N
        blueSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                blueSliderStateChanged(evt);
            }
        });

        alphaSlider.setMaximum(255);
        alphaSlider.setValue(255);
        alphaSlider.setEnabled(false);
        alphaSlider.setName("alphaSlider"); // NOI18N
        alphaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                alphaSliderStateChanged(evt);
            }
        });

        redTextField.setText("255");
        redTextField.setEnabled(false);
        redTextField.setName("redTextField"); // NOI18N

        greenTextField.setText("255");
        greenTextField.setEnabled(false);
        greenTextField.setName("greenTextField"); // NOI18N

        blueTextField.setText("255");
        blueTextField.setEnabled(false);
        blueTextField.setName("blueTextField"); // NOI18N

        alphaTextField.setText("255");
        alphaTextField.setEnabled(false);
        alphaTextField.setName("alphaTextField"); // NOI18N

        jLabel9.setText("帧");
        jLabel9.setName("jLabel9"); // NOI18N

        showColorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        showColorPanel.setEnabled(false);
        showColorPanel.setName("showColorPanel"); // NOI18N

        javax.swing.GroupLayout showColorPanelLayout = new javax.swing.GroupLayout(showColorPanel);
        showColorPanel.setLayout(showColorPanelLayout);
        showColorPanelLayout.setHorizontalGroup(
            showColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        showColorPanelLayout.setVerticalGroup(
            showColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        durationSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));
        durationSpinner.setName("durationSpinner"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nullRadioButton)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(durationSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(alphaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alphaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(blueSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(blueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(greenSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(greenTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(redSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(redTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(objectTwinkleRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(screenTwinkleRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(objectDisappearRadioButton)))
                .addGap(18, 18, 18)
                .addComponent(showColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nullRadioButton)
                    .addComponent(objectTwinkleRadioButton)
                    .addComponent(screenTwinkleRadioButton)
                    .addComponent(objectDisappearRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(durationSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(showColorPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(redTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(greenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(redSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(greenSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(blueSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(blueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alphaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(alphaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        cancleButton.setText("取消");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        File file = new File(data.getCurProject().getPath()+File.separator
            +"audio"+File.separator+"sound");
        File[] files = file.listFiles();
        musicComboBox.setName("musicComboBox"); // NOI18N
        musicComboBox.addItem("");
        for(int i = 0;i<files.length;i++){
            musicComboBox.addItem(files[i].getName());
        }

        jLabel2.setText("音效");
        jLabel2.setName("jLabel2"); // NOI18N

        frameSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        frameSpinner.setName("frameSpinner"); // NOI18N

        jLabel1.setText("开始帧");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(frameSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(musicComboBox, 0, 250, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancleButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(frameSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancleButton))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private AppData data = AppData.getInstance();
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        if (action != null) {
            action.setFrameId(Integer.parseInt(frameSpinner.getValue().toString()));
            action.setMusicFile(musicComboBox.getSelectedItem().toString());
            if (nullRadioButton.isSelected()) {
                action.setType(Action.NOTHING);
            } else if (objectTwinkleRadioButton.isSelected()) {
                action.setType(Action.PLAY_TWINKLE);
                action.setAlpha(alphaSlider.getValue());
                action.setBlue(blueSlider.getValue());
                action.setGreen(greenSlider.getValue());
                action.setRed(redSlider.getValue());
                action.setDuration(Integer.parseInt(durationSpinner.getValue().toString()));
            } else if (screenTwinkleRadioButton.isSelected()) {
                action.setType(Action.SCEEN_TWINKLE);
                action.setAlpha(alphaSlider.getValue());
                action.setBlue(blueSlider.getValue());
                action.setGreen(greenSlider.getValue());
                action.setRed(redSlider.getValue());
                action.setDuration(Integer.parseInt(durationSpinner.getValue().toString()));
            } else if (objectDisappearRadioButton.isSelected()) {
                action.setType(Action.PLAY_DISAPPEAR);
                action.setDuration(Integer.parseInt(durationSpinner.getValue().toString()));
            }
        } else {
            Action act = new Action();
            act.setFrameId(Integer.parseInt(frameSpinner.getValue().toString()));
            act.setMusicFile(musicComboBox.getSelectedItem().toString());
            if (nullRadioButton.isSelected()) {
                act.setType(Action.NOTHING);
            } else if (objectTwinkleRadioButton.isSelected()) {
                act.setType(Action.PLAY_TWINKLE);
                act.setAlpha(alphaSlider.getValue());
                act.setBlue(blueSlider.getValue());
                act.setGreen(greenSlider.getValue());
                act.setRed(redSlider.getValue());
                act.setDuration(Integer.parseInt(durationSpinner.getValue().toString()));
            } else if (screenTwinkleRadioButton.isSelected()) {
                act.setType(Action.SCEEN_TWINKLE);
                act.setAlpha(alphaSlider.getValue());
                act.setBlue(blueSlider.getValue());
                act.setGreen(greenSlider.getValue());
                act.setRed(redSlider.getValue());
                act.setDuration(Integer.parseInt(durationSpinner.getValue().toString()));
            } else if (objectDisappearRadioButton.isSelected()) {
                act.setType(Action.PLAY_DISAPPEAR);
                act.setDuration(Integer.parseInt(durationSpinner.getValue().toString()));
            }
            Animation ani = data.getCurProject().getAnimation(data.getCurrentAnimationIndex());
            ani.addAction(act);
            sed.actionTable.getSelectionModel().setSelectionInterval(ani.getActions().size() - 1,
                    ani.getActions().size() - 1);
        }
        sed.actionTable.updateUI();
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancleButtonActionPerformed

    private void objectTwinkleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objectTwinkleRadioButtonActionPerformed
        // TODO add your handling code here:
        redSlider.setEnabled(true);
        greenSlider.setEnabled(true);
        blueSlider.setEnabled(true);
        alphaSlider.setEnabled(true);
        showColorPanel.setEnabled(true);
        durationSpinner.setEnabled(true);
    }//GEN-LAST:event_objectTwinkleRadioButtonActionPerformed

    private void nullRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nullRadioButtonActionPerformed
        // TODO add your handling code here:
        redSlider.setEnabled(false);
        greenSlider.setEnabled(false);
        blueSlider.setEnabled(false);
        alphaSlider.setEnabled(false);
        showColorPanel.setEnabled(false);
        durationSpinner.setEnabled(false);
    }//GEN-LAST:event_nullRadioButtonActionPerformed

    private void screenTwinkleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenTwinkleRadioButtonActionPerformed
        // TODO add your handling code here:
        redSlider.setEnabled(true);
        greenSlider.setEnabled(true);
        blueSlider.setEnabled(true);
        alphaSlider.setEnabled(true);
        showColorPanel.setEnabled(true);
        durationSpinner.setEnabled(true);
    }//GEN-LAST:event_screenTwinkleRadioButtonActionPerformed

    private void objectDisappearRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objectDisappearRadioButtonActionPerformed
        // TODO add your handling code here:
        redSlider.setEnabled(false);
        greenSlider.setEnabled(false);
        blueSlider.setEnabled(false);
        alphaSlider.setEnabled(false);
        showColorPanel.setEnabled(false);
        durationSpinner.setEnabled(true);
    }//GEN-LAST:event_objectDisappearRadioButtonActionPerformed

    private void redSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_redSliderStateChanged
        // TODO add your handling code here:
        int red = redSlider.getValue();
        int green = greenSlider.getValue();
        int blue = blueSlider.getValue();
        int alpha = alphaSlider.getValue();
        showColorPanel.setBackground(new Color(red, green, blue, alpha));
        redTextField.setText("" + red);
    }//GEN-LAST:event_redSliderStateChanged

    private void greenSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_greenSliderStateChanged
        // TODO add your handling code here:
        int red = redSlider.getValue();
        int green = greenSlider.getValue();
        int blue = blueSlider.getValue();
        int alpha = alphaSlider.getValue();
        showColorPanel.setBackground(new Color(red, green, blue, alpha));
        greenTextField.setText("" + green);
    }//GEN-LAST:event_greenSliderStateChanged

    private void blueSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_blueSliderStateChanged
        // TODO add your handling code here:
        int red = redSlider.getValue();
        int green = greenSlider.getValue();
        int blue = blueSlider.getValue();
        int alpha = alphaSlider.getValue();
        showColorPanel.setBackground(new Color(red, green, blue, alpha));
        blueTextField.setText("" + blue);
    }//GEN-LAST:event_blueSliderStateChanged

    private void alphaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_alphaSliderStateChanged
        // TODO add your handling code here:
        int red = redSlider.getValue();
        int green = greenSlider.getValue();
        int blue = blueSlider.getValue();
        int alpha = alphaSlider.getValue();
        showColorPanel.setBackground(new Color(red, green, blue, alpha));
        alphaTextField.setText("" + alpha);
    }//GEN-LAST:event_alphaSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ActionDialog dialog = new ActionDialog(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider alphaSlider;
    private javax.swing.JTextField alphaTextField;
    private javax.swing.JSlider blueSlider;
    private javax.swing.JTextField blueTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancleButton;
    private javax.swing.JSpinner durationSpinner;
    private javax.swing.JSpinner frameSpinner;
    private javax.swing.JSlider greenSlider;
    private javax.swing.JTextField greenTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox musicComboBox;
    private javax.swing.JRadioButton nullRadioButton;
    private javax.swing.JRadioButton objectDisappearRadioButton;
    private javax.swing.JRadioButton objectTwinkleRadioButton;
    private javax.swing.JButton okButton;
    private javax.swing.JSlider redSlider;
    private javax.swing.JTextField redTextField;
    private javax.swing.JRadioButton screenTwinkleRadioButton;
    private javax.swing.JPanel showColorPanel;
    // End of variables declaration//GEN-END:variables
}
