/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScriptDialog.java
 *
 * Created on 2011-3-27, 13:57:50
 */
package com.soyomaker.dialog;

import com.soyomaker.dialog.event.dataprocess.ChangeEnemyHpDialog;
import com.soyomaker.dialog.event.dataprocess.ChangeEnemyModelDialog;
import com.soyomaker.dialog.event.dataprocess.ChangeEnemySpDialog;
import com.soyomaker.dialog.event.dataprocess.ChangeEquipDialog;
import com.soyomaker.dialog.event.dataprocess.ChangePlayerModelDialog;
import com.soyomaker.dialog.event.dataprocess.ChangePlayerNameDialog;
import com.soyomaker.dialog.event.gameperformance.BattleDialog;
import com.soyomaker.dialog.event.dataprocess.EquipDialog;
import com.soyomaker.dialog.event.gameperformance.EquipShopDialog;
import com.soyomaker.dialog.event.gameperformance.FaceDialog;
import com.soyomaker.dialog.event.dataprocess.ItemDialog;
import com.soyomaker.dialog.event.gameperformance.ItemShopDialog;
import com.soyomaker.dialog.event.gameperformance.MapDialog;
import com.soyomaker.dialog.event.gameperformance.ShowMessageDialog;
import com.soyomaker.dialog.event.dataprocess.MoneyDialog;
import com.soyomaker.dialog.event.gameperformance.MoveDialog;
import com.soyomaker.dialog.event.gameperformance.PlayMusicDialog;
import com.soyomaker.dialog.event.dataprocess.PowerDialog;
import com.soyomaker.dialog.event.dataprocess.RecoverEnemyDialog;
import com.soyomaker.dialog.event.dataprocess.ShowEnemyAniDialog;
import com.soyomaker.dialog.event.dataprocess.SkillDialog;
import com.soyomaker.dialog.event.dataprocess.SwitchDialog;
import com.soyomaker.dialog.event.dataprocess.VarDialog;
import com.soyomaker.dialog.event.gameperformance.ChangeImageARGBDialog;
import com.soyomaker.dialog.event.gameperformance.ChangeScreenARGBDialog;
import com.soyomaker.dialog.event.gameperformance.ChangeSkinDialog;
import com.soyomaker.dialog.event.gameperformance.CustomScriptDialog;
import com.soyomaker.dialog.event.gameperformance.MoveImageDialog;
import com.soyomaker.dialog.event.gameperformance.RemoveImageDialog;
import com.soyomaker.dialog.event.gameperformance.RotateImageDialog;
import com.soyomaker.dialog.event.gameperformance.ScreenShockDialog;
import com.soyomaker.dialog.event.gameperformance.ShowAniDialog;
import com.soyomaker.dialog.event.gameperformance.ShowChooseDialog;
import com.soyomaker.dialog.event.gameperformance.ShowCountDownDialog;
import com.soyomaker.dialog.event.gameperformance.ShowImageDialog;
import com.soyomaker.dialog.event.gameperformance.ShowInputDialog;
import com.soyomaker.dialog.event.gameperformance.StopMusicDialog;
import com.soyomaker.dialog.event.processcontrol.IfDialog;
import com.soyomaker.dialog.event.processcontrol.PublicEventDialog;
import com.soyomaker.dialog.event.processcontrol.WaitDialog;
import com.soyomaker.widget.NpcStatePane;

/**
 *
 * @author Administrator
 */
public class ScriptDialog extends javax.swing.JDialog {

    /** Creates new form ScriptDialog
     * @param parent 
     * @param modal 
     */
    public ScriptDialog(NpcStatePane parent, boolean modal) {
        setModal(modal);
        npcPane = parent;
        initComponents();
        initialize();
    }
    /**
     * 
     */
    public NpcStatePane npcPane;

    private void initialize() {
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scriptTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        breakButton = new javax.swing.JButton();
        ifButton = new javax.swing.JButton();
        whileButton = new javax.swing.JButton();
        continueButton = new javax.swing.JButton();
        exitScriptButton = new javax.swing.JButton();
        publicEventButton = new javax.swing.JButton();
        exitGameButton = new javax.swing.JButton();
        waitButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        mapButton = new javax.swing.JButton();
        moveButton = new javax.swing.JButton();
        showMessageButton = new javax.swing.JButton();
        playMusicButton = new javax.swing.JButton();
        itemShopButton = new javax.swing.JButton();
        battleButton = new javax.swing.JButton();
        equipShopButton = new javax.swing.JButton();
        faceButton = new javax.swing.JButton();
        showChooseButton = new javax.swing.JButton();
        showInputButton = new javax.swing.JButton();
        showImageButton = new javax.swing.JButton();
        showCountDownButton = new javax.swing.JButton();
        showAniButton = new javax.swing.JButton();
        stopMusicButton = new javax.swing.JButton();
        moveImageButton = new javax.swing.JButton();
        rotateImageButton = new javax.swing.JButton();
        changeImageARGBButton = new javax.swing.JButton();
        changeSkinButton = new javax.swing.JButton();
        removeImageButton = new javax.swing.JButton();
        shakeScreenButton = new javax.swing.JButton();
        changeScreenColorButton = new javax.swing.JButton();
        systemMenuButton = new javax.swing.JButton();
        gameSaveButton = new javax.swing.JButton();
        mainMenuButton = new javax.swing.JButton();
        customScriptButton = new javax.swing.JButton();
        endBattleButton = new javax.swing.JButton();
        enemyAniButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        powButton = new javax.swing.JButton();
        skillButton = new javax.swing.JButton();
        equipButton = new javax.swing.JButton();
        itemButton = new javax.swing.JButton();
        moneyButton = new javax.swing.JButton();
        varButton = new javax.swing.JButton();
        switchButton = new javax.swing.JButton();
        changeEquipButton = new javax.swing.JButton();
        playerCompletRecoverButton = new javax.swing.JButton();
        changeModalButton = new javax.swing.JButton();
        changeNameButton = new javax.swing.JButton();
        changeEnemyHpButton = new javax.swing.JButton();
        changeEnemySpButton = new javax.swing.JButton();
        enemyRecoverButton = new javax.swing.JButton();
        enemyTransButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ScriptDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setResizable(false);

        scriptTabbedPane.setName("scriptTabbedPane"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N

        breakButton.setText("跳出循环");
        breakButton.setName("breakButton"); // NOI18N
        breakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakButtonActionPerformed(evt);
            }
        });

        ifButton.setText("条件分支");
        ifButton.setName("ifButton"); // NOI18N
        ifButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifButtonActionPerformed(evt);
            }
        });

        whileButton.setText("循环结构");
        whileButton.setName("whileButton"); // NOI18N
        whileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whileButtonActionPerformed(evt);
            }
        });

        continueButton.setText("下次循环");
        continueButton.setName("continueButton"); // NOI18N
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        exitScriptButton.setText("结束脚本");
        exitScriptButton.setName("exitScriptButton"); // NOI18N
        exitScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitScriptButtonActionPerformed(evt);
            }
        });

        publicEventButton.setText("公共事件");
        publicEventButton.setName("publicEventButton"); // NOI18N
        publicEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicEventButtonActionPerformed(evt);
            }
        });

        exitGameButton.setText("结束游戏");
        exitGameButton.setName("exitGameButton"); // NOI18N
        exitGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitGameButtonActionPerformed(evt);
            }
        });

        waitButton.setText("强制等待");
        waitButton.setName("waitButton"); // NOI18N
        waitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(breakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publicEventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ifButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(continueButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(waitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(whileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exitScriptButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(exitGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {breakButton, continueButton, exitGameButton, exitScriptButton, ifButton, publicEventButton, waitButton, whileButton});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(ifButton)
                    .addComponent(exitScriptButton)
                    .addComponent(whileButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(breakButton)
                    .addComponent(continueButton)
                    .addComponent(exitGameButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(publicEventButton)
                    .addComponent(waitButton))
                .addGap(303, 303, 303))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {breakButton, continueButton, exitGameButton, exitScriptButton, ifButton, publicEventButton, waitButton, whileButton});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        scriptTabbedPane.addTab("流程控制", jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N

        jPanel5.setName("jPanel5"); // NOI18N

        mapButton.setText("切换地图");
        mapButton.setName("mapButton"); // NOI18N
        mapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapButtonActionPerformed(evt);
            }
        });

        moveButton.setText("设置移动");
        moveButton.setName("moveButton"); // NOI18N
        moveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveButtonActionPerformed(evt);
            }
        });

        showMessageButton.setText("显示对话框");
        showMessageButton.setName("showMessageButton"); // NOI18N
        showMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMessageButtonActionPerformed(evt);
            }
        });

        playMusicButton.setText("播放音乐");
        playMusicButton.setName("playMusicButton"); // NOI18N
        playMusicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playMusicButtonActionPerformed(evt);
            }
        });

        itemShopButton.setText("物品商店");
        itemShopButton.setName("itemShopButton"); // NOI18N
        itemShopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemShopButtonActionPerformed(evt);
            }
        });

        battleButton.setText("开启战斗");
        battleButton.setName("battleButton"); // NOI18N
        battleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battleButtonActionPerformed(evt);
            }
        });

        equipShopButton.setText("装备商店");
        equipShopButton.setName("equipShopButton"); // NOI18N
        equipShopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipShopButtonActionPerformed(evt);
            }
        });

        faceButton.setText("改变面向");
        faceButton.setName("faceButton"); // NOI18N
        faceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faceButtonActionPerformed(evt);
            }
        });

        showChooseButton.setText("显示选项框");
        showChooseButton.setName("showChooseButton"); // NOI18N
        showChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showChooseButtonActionPerformed(evt);
            }
        });

        showInputButton.setText("显示输入框");
        showInputButton.setName("showInputButton"); // NOI18N
        showInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInputButtonActionPerformed(evt);
            }
        });

        showImageButton.setText("显示图片");
        showImageButton.setName("showImageButton"); // NOI18N
        showImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showImageButtonActionPerformed(evt);
            }
        });

        showCountDownButton.setText("显示倒计时");
        showCountDownButton.setName("showCountDownButton"); // NOI18N
        showCountDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCountDownButtonActionPerformed(evt);
            }
        });

        showAniButton.setText("显示动画");
        showAniButton.setName("showAniButton"); // NOI18N
        showAniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAniButtonActionPerformed(evt);
            }
        });

        stopMusicButton.setText("停止音乐");
        stopMusicButton.setName("stopMusicButton"); // NOI18N
        stopMusicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopMusicButtonActionPerformed(evt);
            }
        });

        moveImageButton.setText("移动图片");
        moveImageButton.setName("moveImageButton"); // NOI18N
        moveImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveImageButtonActionPerformed(evt);
            }
        });

        rotateImageButton.setText("旋转图片");
        rotateImageButton.setName("rotateImageButton"); // NOI18N
        rotateImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateImageButtonActionPerformed(evt);
            }
        });

        changeImageARGBButton.setText("更改图片色调");
        changeImageARGBButton.setName("changeImageARGBButton"); // NOI18N
        changeImageARGBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeImageARGBButtonActionPerformed(evt);
            }
        });

        changeSkinButton.setText("更换皮肤");
        changeSkinButton.setName("changeSkinButton"); // NOI18N
        changeSkinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSkinButtonActionPerformed(evt);
            }
        });

        removeImageButton.setText("移除图片");
        removeImageButton.setName("removeImageButton"); // NOI18N
        removeImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeImageButtonActionPerformed(evt);
            }
        });

        shakeScreenButton.setText("画面震动");
        shakeScreenButton.setName("shakeScreenButton"); // NOI18N
        shakeScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shakeScreenButtonActionPerformed(evt);
            }
        });

        changeScreenColorButton.setText("更改画面色调");
        changeScreenColorButton.setName("changeScreenColorButton"); // NOI18N
        changeScreenColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeScreenColorButtonActionPerformed(evt);
            }
        });

        systemMenuButton.setText("打开系统菜单");
        systemMenuButton.setName("systemMenuButton"); // NOI18N
        systemMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemMenuButtonActionPerformed(evt);
            }
        });

        gameSaveButton.setText("打开存档菜单");
        gameSaveButton.setName("gameSaveButton"); // NOI18N
        gameSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameSaveButtonActionPerformed(evt);
            }
        });

        mainMenuButton.setText("回主菜单");
        mainMenuButton.setName("mainMenuButton"); // NOI18N
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        customScriptButton.setText("自定义脚本");
        customScriptButton.setName("customScriptButton"); // NOI18N
        customScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customScriptButtonActionPerformed(evt);
            }
        });

        endBattleButton.setText("结束战斗");
        endBattleButton.setName("endBattleButton"); // NOI18N
        endBattleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endBattleButtonActionPerformed(evt);
            }
        });

        enemyAniButton.setText("敌人动画");
        enemyAniButton.setName("enemyAniButton"); // NOI18N
        enemyAniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enemyAniButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gameSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeScreenColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeImageARGBButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stopMusicButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(battleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(faceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playMusicButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemShopButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(equipShopButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(moveImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(rotateImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(changeSkinButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(systemMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(mainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(endBattleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showChooseButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(showInputButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(showAniButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(showMessageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(showImageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(shakeScreenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(showCountDownButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(customScriptButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(enemyAniButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {battleButton, changeImageARGBButton, changeScreenColorButton, changeSkinButton, customScriptButton, endBattleButton, enemyAniButton, equipShopButton, faceButton, gameSaveButton, itemShopButton, mainMenuButton, mapButton, moveButton, moveImageButton, playMusicButton, removeImageButton, rotateImageButton, shakeScreenButton, showAniButton, showChooseButton, showCountDownButton, showImageButton, showInputButton, showMessageButton, stopMusicButton, systemMenuButton});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(endBattleButton)
                            .addGap(123, 123, 123))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(moveButton)
                            .addGap(18, 18, 18)
                            .addComponent(itemShopButton)
                            .addGap(18, 18, 18)
                            .addComponent(equipShopButton)
                            .addGap(18, 18, 18)
                            .addComponent(moveImageButton)
                            .addGap(18, 18, 18)
                            .addComponent(rotateImageButton)
                            .addGap(59, 59, 59)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(changeSkinButton)
                                .addComponent(customScriptButton))
                            .addGap(18, 18, 18)
                            .addComponent(systemMenuButton)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mainMenuButton)
                                .addComponent(enemyAniButton))))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(showCountDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showChooseButton)
                            .addGap(18, 18, 18)
                            .addComponent(showInputButton)
                            .addGap(18, 18, 18)
                            .addComponent(showAniButton)
                            .addGap(18, 18, 18)
                            .addComponent(showMessageButton)
                            .addGap(18, 18, 18)
                            .addComponent(showImageButton)
                            .addGap(59, 59, 59)
                            .addComponent(shakeScreenButton)
                            .addGap(41, 41, 41))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(mapButton)
                            .addGap(18, 18, 18)
                            .addComponent(playMusicButton)
                            .addGap(18, 18, 18)
                            .addComponent(faceButton)
                            .addGap(18, 18, 18)
                            .addComponent(battleButton)
                            .addGap(18, 18, 18)
                            .addComponent(removeImageButton)
                            .addGap(18, 18, 18)
                            .addComponent(stopMusicButton)
                            .addGap(18, 18, 18)
                            .addComponent(changeImageARGBButton)
                            .addGap(18, 18, 18)
                            .addComponent(changeScreenColorButton)
                            .addGap(18, 18, 18)
                            .addComponent(gameSaveButton))))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {battleButton, changeImageARGBButton, changeScreenColorButton, changeSkinButton, customScriptButton, endBattleButton, enemyAniButton, equipShopButton, faceButton, gameSaveButton, itemShopButton, mainMenuButton, mapButton, moveButton, moveImageButton, playMusicButton, removeImageButton, rotateImageButton, shakeScreenButton, showAniButton, showChooseButton, showCountDownButton, showImageButton, showInputButton, showMessageButton, stopMusicButton, systemMenuButton});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        scriptTabbedPane.addTab("游戏表现", jPanel2);

        jPanel3.setName("jPanel3"); // NOI18N

        jPanel6.setName("jPanel6"); // NOI18N

        powButton.setText("增减属性");
        powButton.setName("powButton"); // NOI18N
        powButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powButtonActionPerformed(evt);
            }
        });

        skillButton.setText("增减技能");
        skillButton.setName("skillButton"); // NOI18N
        skillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skillButtonActionPerformed(evt);
            }
        });

        equipButton.setText("增减装备");
        equipButton.setName("equipButton"); // NOI18N
        equipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipButtonActionPerformed(evt);
            }
        });

        itemButton.setText("增减物品");
        itemButton.setName("itemButton"); // NOI18N
        itemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemButtonActionPerformed(evt);
            }
        });

        moneyButton.setText("增减金钱");
        moneyButton.setName("moneyButton"); // NOI18N
        moneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyButtonActionPerformed(evt);
            }
        });

        varButton.setText("变量操作");
        varButton.setName("varButton"); // NOI18N
        varButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varButtonActionPerformed(evt);
            }
        });

        switchButton.setText("开关操作");
        switchButton.setName("switchButton"); // NOI18N
        switchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchButtonActionPerformed(evt);
            }
        });

        changeEquipButton.setText("切换装备");
        changeEquipButton.setName("changeEquipButton"); // NOI18N
        changeEquipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeEquipButtonActionPerformed(evt);
            }
        });

        playerCompletRecoverButton.setText("角色完全恢复");
        playerCompletRecoverButton.setName("playerCompletRecoverButton"); // NOI18N
        playerCompletRecoverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerCompletRecoverButtonActionPerformed(evt);
            }
        });

        changeModalButton.setText("角色变身");
        changeModalButton.setName("changeModalButton"); // NOI18N
        changeModalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeModalButtonActionPerformed(evt);
            }
        });

        changeNameButton.setText("修改角色名称");
        changeNameButton.setName("changeNameButton"); // NOI18N
        changeNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNameButtonActionPerformed(evt);
            }
        });

        changeEnemyHpButton.setText("增减敌人HP");
        changeEnemyHpButton.setName("changeEnemyHpButton"); // NOI18N
        changeEnemyHpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeEnemyHpButtonActionPerformed(evt);
            }
        });

        changeEnemySpButton.setText("增减敌人SP");
        changeEnemySpButton.setName("changeEnemySpButton"); // NOI18N
        changeEnemySpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeEnemySpButtonActionPerformed(evt);
            }
        });

        enemyRecoverButton.setText("敌人完全恢复");
        enemyRecoverButton.setName("enemyRecoverButton"); // NOI18N
        enemyRecoverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enemyRecoverButtonActionPerformed(evt);
            }
        });

        enemyTransButton.setText("敌人变身");
        enemyTransButton.setName("enemyTransButton"); // NOI18N
        enemyTransButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enemyTransButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(powButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(skillButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(changeEnemyHpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(varButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeEquipButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(moneyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(equipButton, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(changeNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(changeModalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(enemyRecoverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(playerCompletRecoverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(switchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(changeEnemySpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enemyTransButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {changeEnemyHpButton, changeEnemySpButton, changeEquipButton, changeModalButton, changeNameButton, enemyRecoverButton, enemyTransButton, equipButton, itemButton, moneyButton, playerCompletRecoverButton, powButton, skillButton, switchButton, varButton});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(switchButton)
                        .addGap(18, 18, 18)
                        .addComponent(playerCompletRecoverButton)
                        .addGap(18, 18, 18)
                        .addComponent(enemyRecoverButton))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(itemButton)
                                .addGap(18, 18, 18)
                                .addComponent(moneyButton)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(powButton)
                                .addGap(18, 18, 18)
                                .addComponent(skillButton)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(equipButton)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(changeNameButton)
                                    .addComponent(changeEnemySpButton))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(changeModalButton)
                                    .addComponent(enemyTransButton)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(varButton)
                                .addGap(18, 18, 18)
                                .addComponent(changeEquipButton)
                                .addGap(18, 18, 18)
                                .addComponent(changeEnemyHpButton)))))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {changeEnemyHpButton, changeEnemySpButton, changeEquipButton, changeModalButton, changeNameButton, enemyRecoverButton, enemyTransButton, equipButton, itemButton, moneyButton, playerCompletRecoverButton, powButton, skillButton, switchButton, varButton});

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        scriptTabbedPane.addTab("数据处理", jPanel3);

        cancleButton.setText("关闭");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scriptTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(cancleButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(scriptTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancleButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancleButtonActionPerformed

    private void ifButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifButtonActionPerformed
        // TODO add your handling code here:
        IfDialog md = new IfDialog(this, true);
        md.setVisible(true);
    }//GEN-LAST:event_ifButtonActionPerformed

    private void whileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whileButtonActionPerformed
        // TODO add your handling code here:
        insertScriptData(npcPane.eventTable.getSelectedRow(), "end");
        insertScriptData(npcPane.eventTable.getSelectedRow(), "");
        insertScriptData(npcPane.eventTable.getSelectedRow(), "while true do");
    }//GEN-LAST:event_whileButtonActionPerformed

    private void exitScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitScriptButtonActionPerformed
        // TODO add your handling code here:
        insertScriptData(npcPane.eventTable.getSelectedRow(), "do return end");
    }//GEN-LAST:event_exitScriptButtonActionPerformed
    /**
     * 
     * @param row
     * @param sc
     */
    public void insertScriptData(int row, String sc) {
        if (row == -1) {
            row = 0;
        }
        int n = 0;
        for (int i = 0; i < npcPane.eventTable.getSelectedRow(); i++) {
            String s = npcPane.eventTable.getValueAt(i, 0).toString();
            if (s.trim().endsWith("then") || s.trim().endsWith("do")) {
                n += 1;
            }
            if (s.trim().startsWith("end")) {
                n -= 1;
            }
        }
        StringBuilder c = new StringBuilder();
        for (int i = 0; i < n; i++) {
            c.append("    ");
        }
        String[] rowData = {c.toString() + sc};
        npcPane.eventTM.insertRow(row, rowData);
        npcPane.eventTable.getSelectionModel().setSelectionInterval(row, row);
        this.dispose();
    }
    private void breakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakButtonActionPerformed
        // TODO add your handling code here:
        insertScriptData(npcPane.eventTable.getSelectedRow(), "do break end");
    }//GEN-LAST:event_breakButtonActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        // TODO add your handling code here:
        insertScriptData(npcPane.eventTable.getSelectedRow(), "--暂不支持");
    }//GEN-LAST:event_continueButtonActionPerformed

    private void mapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapButtonActionPerformed
        // TODO add your handling code here:
        MapDialog md = new MapDialog(this, true);
        md.setVisible(true);
    }//GEN-LAST:event_mapButtonActionPerformed

    private void moveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveButtonActionPerformed
        // TODO add your handling code here:
        MoveDialog md = new MoveDialog(this, true);
        md.setVisible(true);
    }//GEN-LAST:event_moveButtonActionPerformed

    private void showMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMessageButtonActionPerformed
        // TODO add your handling code here:
        ShowMessageDialog md = new ShowMessageDialog(this, true);
        md.setVisible(true);
    }//GEN-LAST:event_showMessageButtonActionPerformed

    private void playMusicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playMusicButtonActionPerformed
        // TODO add your handling code here:
        PlayMusicDialog dialog = new PlayMusicDialog(null, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_playMusicButtonActionPerformed

    private void itemShopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemShopButtonActionPerformed
        // TODO add your handling code here:
        ItemShopDialog dialog = new ItemShopDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_itemShopButtonActionPerformed

    private void battleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battleButtonActionPerformed
        // TODO add your handling code here:
        BattleDialog dialog = new BattleDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_battleButtonActionPerformed

    private void varButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varButtonActionPerformed
        // TODO add your handling code here:
        VarDialog dialog = new VarDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_varButtonActionPerformed

    private void equipShopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipShopButtonActionPerformed
        // TODO add your handling code here:
        EquipShopDialog dialog = new EquipShopDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_equipShopButtonActionPerformed

    private void switchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchButtonActionPerformed
        // TODO add your handling code here:
        SwitchDialog dialog = new SwitchDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_switchButtonActionPerformed

    private void faceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faceButtonActionPerformed
        // TODO add your handling code here:
        FaceDialog fd = new FaceDialog(this, true);
        fd.setVisible(true);
    }//GEN-LAST:event_faceButtonActionPerformed

    private void waitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitButtonActionPerformed
        // TODO add your handling code here:
        WaitDialog hd = new WaitDialog(this, true);
        hd.setVisible(true);
    }//GEN-LAST:event_waitButtonActionPerformed

    private void moneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyButtonActionPerformed
        // TODO add your handling code here:
        MoneyDialog md = new MoneyDialog(this, true);
        md.setVisible(true);
    }//GEN-LAST:event_moneyButtonActionPerformed

    private void powButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powButtonActionPerformed
        // TODO add your handling code here:
        PowerDialog dialog = new PowerDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_powButtonActionPerformed

    private void skillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skillButtonActionPerformed
        // TODO add your handling code here:
        SkillDialog dialog = new SkillDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_skillButtonActionPerformed

    private void itemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemButtonActionPerformed
        // TODO add your handling code here:
        ItemDialog dialog = new ItemDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_itemButtonActionPerformed

    private void equipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipButtonActionPerformed
        // TODO add your handling code here:
        EquipDialog dialog = new EquipDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_equipButtonActionPerformed

    private void publicEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicEventButtonActionPerformed
        // TODO add your handling code here:
        PublicEventDialog ped = new PublicEventDialog(this, true);
        ped.setVisible(true);
    }//GEN-LAST:event_publicEventButtonActionPerformed

    private void showCountDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCountDownButtonActionPerformed
        // TODO add your handling code here:
        ShowCountDownDialog scdd = new ShowCountDownDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_showCountDownButtonActionPerformed

    private void showChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showChooseButtonActionPerformed
        // TODO add your handling code here:
        ShowChooseDialog scdd = new ShowChooseDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_showChooseButtonActionPerformed

    private void showInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInputButtonActionPerformed
        // TODO add your handling code here:
        ShowInputDialog scdd = new ShowInputDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_showInputButtonActionPerformed

    private void moveImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveImageButtonActionPerformed
        // TODO add your handling code here:
        MoveImageDialog scdd = new MoveImageDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_moveImageButtonActionPerformed

    private void showAniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAniButtonActionPerformed
        // TODO add your handling code here:
        ShowAniDialog scdd = new ShowAniDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_showAniButtonActionPerformed

    private void removeImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeImageButtonActionPerformed
        // TODO add your handling code here:
        RemoveImageDialog scdd = new RemoveImageDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_removeImageButtonActionPerformed

    private void rotateImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateImageButtonActionPerformed
        // TODO add your handling code here:
        RotateImageDialog scdd = new RotateImageDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_rotateImageButtonActionPerformed

    private void stopMusicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopMusicButtonActionPerformed
        // TODO add your handling code here:
        StopMusicDialog scdd = new StopMusicDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_stopMusicButtonActionPerformed

    private void endBattleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endBattleButtonActionPerformed
        // TODO add your handling code here:
        insertScriptData(npcPane.eventTable.getSelectedRow(), "globalData.proxy:exitFight()");
    }//GEN-LAST:event_endBattleButtonActionPerformed

    private void showImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showImageButtonActionPerformed
        // TODO add your handling code here:
        ShowImageDialog scdd = new ShowImageDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_showImageButtonActionPerformed

    private void changeImageARGBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeImageARGBButtonActionPerformed
        // TODO add your handling code here:
        ChangeImageARGBDialog scdd = new ChangeImageARGBDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_changeImageARGBButtonActionPerformed

    private void changeSkinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSkinButtonActionPerformed
        // TODO add your handling code here:
        ChangeSkinDialog scdd = new ChangeSkinDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_changeSkinButtonActionPerformed

    private void changeScreenColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeScreenColorButtonActionPerformed
        // TODO add your handling code here:
        ChangeScreenARGBDialog scdd = new ChangeScreenARGBDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_changeScreenColorButtonActionPerformed

    private void customScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customScriptButtonActionPerformed
        // TODO add your handling code here:
        CustomScriptDialog scdd = new CustomScriptDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_customScriptButtonActionPerformed

    private void systemMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemMenuButtonActionPerformed
        // TODO add your handling code here:
        insertScriptData(npcPane.eventTable.getSelectedRow(), "globalData.proxy:openSystemMenu()");
    }//GEN-LAST:event_systemMenuButtonActionPerformed

    private void shakeScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shakeScreenButtonActionPerformed
        // TODO add your handling code here:
        ScreenShockDialog scdd = new ScreenShockDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_shakeScreenButtonActionPerformed

    private void gameSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameSaveButtonActionPerformed
        // TODO add your handling code here:
        insertScriptData(npcPane.eventTable.getSelectedRow(), "globalData.proxy:openRecordMenu()");
    }//GEN-LAST:event_gameSaveButtonActionPerformed

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // TODO add your handling code here:
        insertScriptData(npcPane.eventTable.getSelectedRow(), "globalData.proxy:returnToMainMenu()");
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void changeNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNameButtonActionPerformed
        // TODO add your handling code here:
        ChangePlayerNameDialog scdd = new ChangePlayerNameDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_changeNameButtonActionPerformed

    private void changeModalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeModalButtonActionPerformed
        // TODO add your handling code here:
        ChangePlayerModelDialog scdd = new ChangePlayerModelDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_changeModalButtonActionPerformed

    private void changeEquipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeEquipButtonActionPerformed
        // TODO add your handling code here:
        ChangeEquipDialog scdd = new ChangeEquipDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_changeEquipButtonActionPerformed

    private void playerCompletRecoverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerCompletRecoverButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerCompletRecoverButtonActionPerformed

    private void changeEnemyHpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeEnemyHpButtonActionPerformed
        // TODO add your handling code here:
        ChangeEnemyHpDialog scdd = new ChangeEnemyHpDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_changeEnemyHpButtonActionPerformed

    private void changeEnemySpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeEnemySpButtonActionPerformed
        // TODO add your handling code here:
        ChangeEnemySpDialog scdd = new ChangeEnemySpDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_changeEnemySpButtonActionPerformed

    private void enemyRecoverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enemyRecoverButtonActionPerformed
        // TODO add your handling code here:
        RecoverEnemyDialog scdd = new RecoverEnemyDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_enemyRecoverButtonActionPerformed

    private void enemyTransButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enemyTransButtonActionPerformed
        // TODO add your handling code here:
        ChangeEnemyModelDialog scdd = new ChangeEnemyModelDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_enemyTransButtonActionPerformed

    private void enemyAniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enemyAniButtonActionPerformed
        // TODO add your handling code here:
        ShowEnemyAniDialog scdd = new ShowEnemyAniDialog(this, true);
        scdd.setVisible(true);
    }//GEN-LAST:event_enemyAniButtonActionPerformed

    private void exitGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitGameButtonActionPerformed
        // TODO add your handling code here:
        insertScriptData(npcPane.eventTable.getSelectedRow(), "globalData.proxy:stopGame()");
    }//GEN-LAST:event_exitGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ScriptDialog dialog = new ScriptDialog(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton battleButton;
    private javax.swing.JButton breakButton;
    private javax.swing.JButton cancleButton;
    private javax.swing.JButton changeEnemyHpButton;
    private javax.swing.JButton changeEnemySpButton;
    private javax.swing.JButton changeEquipButton;
    private javax.swing.JButton changeImageARGBButton;
    private javax.swing.JButton changeModalButton;
    private javax.swing.JButton changeNameButton;
    private javax.swing.JButton changeScreenColorButton;
    private javax.swing.JButton changeSkinButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JButton customScriptButton;
    private javax.swing.JButton endBattleButton;
    private javax.swing.JButton enemyAniButton;
    private javax.swing.JButton enemyRecoverButton;
    private javax.swing.JButton enemyTransButton;
    private javax.swing.JButton equipButton;
    private javax.swing.JButton equipShopButton;
    private javax.swing.JButton exitGameButton;
    private javax.swing.JButton exitScriptButton;
    private javax.swing.JButton faceButton;
    private javax.swing.JButton gameSaveButton;
    private javax.swing.JButton ifButton;
    private javax.swing.JButton itemButton;
    private javax.swing.JButton itemShopButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton mapButton;
    private javax.swing.JButton moneyButton;
    private javax.swing.JButton moveButton;
    private javax.swing.JButton moveImageButton;
    private javax.swing.JButton playMusicButton;
    private javax.swing.JButton playerCompletRecoverButton;
    private javax.swing.JButton powButton;
    private javax.swing.JButton publicEventButton;
    private javax.swing.JButton removeImageButton;
    private javax.swing.JButton rotateImageButton;
    private javax.swing.JTabbedPane scriptTabbedPane;
    private javax.swing.JButton shakeScreenButton;
    private javax.swing.JButton showAniButton;
    private javax.swing.JButton showChooseButton;
    private javax.swing.JButton showCountDownButton;
    private javax.swing.JButton showImageButton;
    private javax.swing.JButton showInputButton;
    private javax.swing.JButton showMessageButton;
    private javax.swing.JButton skillButton;
    private javax.swing.JButton stopMusicButton;
    private javax.swing.JButton switchButton;
    private javax.swing.JButton systemMenuButton;
    private javax.swing.JButton varButton;
    private javax.swing.JButton waitButton;
    private javax.swing.JButton whileButton;
    // End of variables declaration//GEN-END:variables
}
