/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EnemyChooseSkillDialog.java
 *
 * Created on 2011-5-9, 15:39:14
 */
package com.soyostar.dialog;

import com.soyostar.data.DataManager;
import com.soyostar.data.model.Enemy;
import com.soyostar.data.model.Model;
import com.soyostar.data.model.Skill;
import com.soyostar.project.Project;
import com.soyostar.proxy.SoftProxy;

/**
 *
 * @author Administrator
 */
public class EnemyChooseSkillDialog extends javax.swing.JDialog {

    /** Creates new form EnemyChooseSkillDialog
     * @param parent 
     * @param modal 
     */
    public EnemyChooseSkillDialog(DataEditorDialog parent, boolean modal) {
        super(parent, modal);
        ded = parent;
        initComponents();
        initialize();
    }
    private DataEditorDialog ded;

    private void initialize() {
        setLocationRelativeTo(null);
        int n = SoftProxy.getInstance().getCurProject().getDataManager().getModels(Model.SKILL).length;
        for (int i = 0; i < n; i++) {
            Skill skill = (Skill) SoftProxy.getInstance().getCurProject().getDataManager().getModels(Model.SKILL)[i];
            skillComboBox.addItem(skill.name);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        skillComboBox = new javax.swing.JComboBox();
        okButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(EnemyChooseSkillDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N

        jLabel1.setText("技能名称");
        jLabel1.setName("jLabel1"); // NOI18N

        skillComboBox.setName("skillComboBox"); // NOI18N

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancleButton.setText("取消");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(skillComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(cancleButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(skillComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancleButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        Enemy enemy = (Enemy) SoftProxy.getInstance().getCurProject().getDataManager().getModels(Model.ENEMY)[ded.getCurSelectEnemyIndex()];
        Skill skill = (Skill) SoftProxy.getInstance().getCurProject().getDataManager().getModels(Model.SKILL)[skillComboBox.getSelectedIndex()];
        enemy.skillList.add(skill);
        ded.enemySkillTable.getSelectionModel().setSelectionInterval(enemy.skillList.size() - 1, enemy.skillList.size() - 1);
        ded.setCurSelectEnemySkillIndex(enemy.skillList.size() - 1);
        ded.enemySkillTable.updateUI();
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EnemyChooseSkillDialog dialog = new EnemyChooseSkillDialog(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox skillComboBox;
    // End of variables declaration//GEN-END:variables
}
