/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MoveDialog.java
 *
 * Created on 2011-5-14, 19:06:27
 */
package com.soyomaker.dialog.event.gameperformance;

import com.soyomaker.AppData;
import com.soyomaker.dialog.AbCommandDialog;
import com.soyomaker.dialog.ScriptDialog;
import com.soyomaker.model.map.CommandFactory;
import com.soyomaker.model.map.Map;
import com.soyomaker.render.PreviewRender;
import com.soyomaker.render.PreviewRenderFactory;
import com.soyomaker.render.RenderListener;
import java.awt.Point;

/**
 *
 * @author Administrator
 */
public class MoveDialog extends AbCommandDialog implements RenderListener {

    /** Creates new form MoveDialog
     * @param parent
     * @param modal
     * @param typeId
     */
    public MoveDialog(ScriptDialog parent, boolean modal, int typeId) {
        super(parent, modal, typeId);
        sd = parent;
        initComponents();
        setLocationRelativeTo(null);
        Map map = AppData.getInstance().getCurrentMap();
        if (map != null) {
            pr = map.getPreviewRender();
            if (pr == null) {
                pr = PreviewRenderFactory.createPreviewRender(map);
            }
            pr.addRenderListener(this);
            pr.setShowCollide(false);
            pr.setShowSprite(true);
            pr.setShowTile(true);
            pr.setShowPressPoint(true);
            mapScrollPane.setViewportView(pr);
            pr.repaint();
        } else {
            mapScrollPane.setViewportView(null);
        }
    }
    private ScriptDialog sd;
    private PreviewRender pr = null;
    private Point pressPoint = new Point();

    /**
     *
     * @param p
     */
    public void focusPointChanged(Point p) {
    }

    /**
     *
     * @param p
     */
    public void pressPointChanged(Point p) {
        pr.repaint();
        pressPoint.x = p.x;
        pressPoint.y = p.y;
        jLabel4.setText("移动到： " + pressPoint.y + "行，" + pressPoint.x + "列");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mapScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(MoveDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancleButton.setText("取消");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("移动到： 0行，0列");
        jLabel4.setName("jLabel4"); // NOI18N

        mapScrollPane.setName("mapScrollPane"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mapScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 451, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancleButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cancleButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancleButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        mCommand = CommandFactory.createCommand(mTypeId);
        mCommand.addParameter(pressPoint.y + "");
        mCommand.addParameter(pressPoint.x + "");
        System.out.println(mCommand);
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancleButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane mapScrollPane;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
