/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AutoCutDialog.java
 *
 * Created on 2012-5-2, 18:12:15
 */
package com.soyomaker.dialog;

import java.awt.Rectangle;
import javax.swing.JDialog;

/**
 *
 * @author Administrator
 */
public class AutoCutDialog extends javax.swing.JDialog {

    /** Creates new form AutoCutDialog
     * @param parent
     * @param modal
     */
    public AutoCutDialog(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    private Rectangle rect = null;

    /**
     *
     * @return
     */
    public Rectangle getAutoCutRect() {
        return rect;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mCancleButton = new javax.swing.JButton();
        mOkButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mWidthTextField = new javax.swing.JTextField();
        mHeightTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("自动切块");
        setResizable(false);

        mCancleButton.setText("取消");
        mCancleButton.setName("mCancleButton"); // NOI18N
        mCancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCancleButtonActionPerformed(evt);
            }
        });

        mOkButton.setText("确定");
        mOkButton.setName("mOkButton"); // NOI18N
        mOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOkButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("图块宽度");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("图块高度");
        jLabel2.setName("jLabel2"); // NOI18N

        mWidthTextField.setText("192");
        mWidthTextField.setName("mWidthTextField"); // NOI18N

        mHeightTextField.setText("192");
        mHeightTextField.setName("mHeightTextField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mHeightTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(mWidthTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mOkButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mCancleButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {mHeightTextField, mWidthTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mWidthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mHeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mCancleButton)
                    .addComponent(mOkButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {mHeightTextField, mWidthTextField});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOkButtonActionPerformed
        // TODO add your handling code here:
        rect = new Rectangle(Integer.parseInt(mWidthTextField.getText()), Integer.parseInt(mHeightTextField.getText()));
        dispose();
    }//GEN-LAST:event_mOkButtonActionPerformed

    private void mCancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCancleButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mCancleButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mCancleButton;
    private javax.swing.JTextField mHeightTextField;
    private javax.swing.JButton mOkButton;
    private javax.swing.JTextField mWidthTextField;
    // End of variables declaration//GEN-END:variables
}
