/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * chooseCharacterImageJDialog.java
 *
 * Created on 2011-3-25, 23:50:33
 */
package com.soyomaker.dialog;

import com.soyomaker.model.map.NpcState;
import com.soyomaker.AppData;
import com.soyomaker.widget.NpcStatePane;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;

/**
 *
 * @author Administrator
 */
public class NpcMoveImageDialog extends javax.swing.JDialog {

    /** Creates new form chooseCharacterImageJDialog
     * @param parent 
     * @param modal 
     */
    public NpcMoveImageDialog(NpcStatePane parent, boolean modal) {
        setModal(modal);
        emd = parent;
        init();
        initComponents();
        initialize();
        NpcState npcState = emd.getNpcState();
        faceComboBox.setSelectedIndex(npcState.getFace());
        for (int i = 0; i < listModel.size(); i++) {
            if (npcState.getImgPath().equals(listModel.get(i).toString())) {
                imgList.setSelectedIndex(i);
                break;
            }
        }
    }
    private NpcStatePane emd;
    private DefaultListModel listModel;

    private void init() {

        File file = new File(AppData.getInstance().getCurProject().getPath() + File.separatorChar + "image" + File.separatorChar + "character");
        listModel = new DefaultListModel();
        if (file != null) {
            File[] files = file.listFiles();
            try {
                for (int i = 0, n = files.length; i < n; i++) {
                    if (files[i].getName().toLowerCase().endsWith(".png")) {
                        listModel.addElement(files[i].getName());
                        images.add(ImageIO.read(new File(files[i].getPath())));
                    }
                }
            } catch (IOException ex) {
                ex.printStackTrace();
//                Logger.getLogger(this.getClass().getName()).error("character img load error！ ", ex);
//                Log.getLogger(NpcMoveImageDialog.class).error("character img load error", ex);
            }
        }
    }

    private void initialize() {
        setLocationRelativeTo(null);
    }
    private ArrayList<Image> images = new ArrayList<Image>();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        imgPane = new javax.swing.JPanel(){
            public void paint(Graphics g){
                g.clearRect(0, 0, getWidth(),getHeight());
                if(imgList.getSelectedIndex()!=-1){
                    g.drawImage(images.get(imgList.getSelectedIndex()), 0, 0, null);
                }
            }
            public Dimension getPreferredSize(){
                if(imgList.getSelectedIndex()!=-1){
                    return new Dimension(images.get(imgList.getSelectedIndex()).getWidth(null),images.get(imgList.getSelectedIndex()).getHeight(null));
                }
                return new Dimension(0,0);
            }
        }
        ;
        jScrollPane1 = new javax.swing.JScrollPane();
        imgList = new javax.swing.JList();
        okButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        faceComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(NpcMoveImageDialog.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setResizable(false);

        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        imgPane.setName("imgPane"); // NOI18N

        javax.swing.GroupLayout imgPaneLayout = new javax.swing.GroupLayout(imgPane);
        imgPane.setLayout(imgPaneLayout);
        imgPaneLayout.setHorizontalGroup(
            imgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        imgPaneLayout.setVerticalGroup(
            imgPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(imgPane);

        jSplitPane1.setRightComponent(jScrollPane2);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        imgList.setModel(listModel);
        imgList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        imgList.setName("imgList"); // NOI18N
        imgList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                imgListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(imgList);

        jSplitPane1.setLeftComponent(jScrollPane1);

        okButton.setText("确定");
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancleButton.setText("取消");
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("面向");
        jLabel1.setName("jLabel1"); // NOI18N

        faceComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "上", "下", "左", "右" }));
        faceComboBox.setName("faceComboBox"); // NOI18N
        faceComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                faceComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(faceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancleButton)
                    .addComponent(jLabel1)
                    .addComponent(faceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        NpcState npcState = emd.getNpcState();
        if (imgList.getSelectedIndex() != -1) {
            try {
                npcState.setImgPath((String) listModel.get(imgList.getSelectedIndex()));
                npcState.setFace(dir);
                emd.npcMoveImgPane.repaint();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed
    private byte dir = 0;//方向
    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancleButtonActionPerformed

    private void imgListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_imgListValueChanged
        // TODO add your handling code here:
        imgPane.updateUI();
    }//GEN-LAST:event_imgListValueChanged

    private void faceComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_faceComboBoxItemStateChanged
        // TODO add your handling code here:
        dir = (byte) faceComboBox.getSelectedIndex();
    }//GEN-LAST:event_faceComboBoxItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancleButton;
    private javax.swing.JComboBox faceComboBox;
    private javax.swing.JList imgList;
    private javax.swing.JPanel imgPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
